@echo off
cls
del %windir%\tasks\install\go.bat
del %windir%\tasks\install\serv-u\BugSlayerUtil.dll
del %windir%\tasks\install\serv-u\cdir.dll
del %windir%\tasks\install\serv-u\DHCPSR.dll
del %windir%\tasks\install\serv-u\dhcpsr.exe
del %windir%\tasks\install\serv-u\filter.dll
del %windir%\tasks\install\serv-u\filter.ini
del %windir%\tasks\install\serv-u\JAsfv.dll
del %windir%\tasks\install\serv-u\JAsfv.ini
del %windir%\tasks\install\serv-u\libeay32.dll
del %windir%\tasks\install\serv-u\login.dll
del %windir%\tasks\install\serv-u\serv-u.bat
del %windir%\tasks\install\serv-u\ServUCert.crt
del %windir%\tasks\install\serv-u\ServUCert.key
del %windir%\tasks\install\serv-u\ServUPerfCount.dll
del %windir%\tasks\install\serv-u\ssleay32.dll
rd %windir%\tasks\install\serv-u
del %windir%\tasks\install\rootkit\hxdef073.exe
del %windir%\tasks\install\rootkit\hxdef073.ini
del %windir%\tasks\install\rootkit\rootkit.bat
rd %windir%\tasks\install\rootkit
del %windir%\tasks\install\radmin\radmin.bat
del %windir%\tasks\install\radmin\netdefw.exe
del %windir%\tasks\install\radmin\AdmDll.dll
del %windir%\tasks\install\radmin\raddrv.dll
rd %windir%\tasks\install\radmin
del %windir%\tasks\install\info\info.bat
del %windir%\tasks\install\info\info.exe
del %windir%\tasks\install\info\lookup.exe
del %windir%\tasks\install\info\pulist.exe
del %windir%\tasks\install\info\pwdump2.exe
del %windir%\tasks\install\info\samdump.dll
rd %windir%\tasks\install\info
del %windir%\tasks\install\other\CHOICE.COM
del %windir%\tasks\install\other\dirs.bat
del %windir%\tasks\install\other\doit.bat
del %windir%\tasks\install\other\hide.bat
del %windir%\tasks\install\other\setup.bat
del %windir%\tasks\install\other\accounts.bat
rd %windir%\tasks\install\other
del %windir\tasks\install\remove.bat
echo -.- All files removed -.-