olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Virus.MSWord.Pinguin-855a0250c86d0113f0efcf879277a0419710074e
Type: Text
-------------------------------------------------------------------------------
VBA MACRO Virus.MSWord.Pinguin-855a0250c86d0113f0efcf879277a0419710074e 
in file: Virus.MSWord.Pinguin-855a0250c86d0113f0efcf879277a0419710074e - OLE stream: ''
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
if minute(now())>55 then msgbox "This computer is infected by Pinguin virus !", vbOKOnly&vbCritical, "Windows Alert Level : 3"

+----------+--------------------+---------------------------------------------+
|Type      |Keyword             |Description                                  |
+----------+--------------------+---------------------------------------------+
|Suspicious|Windows             |May enumerate application windows (if        |
|          |                    |combined with Shell.Application object)      |
+----------+--------------------+---------------------------------------------+

