olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Virus.MSWord.Reflex-b6437964faeedb089db98b3ddb6d43a85e9dacbe
Type: OLE
-------------------------------------------------------------------------------
VBA MACRO Emperor23 
in file: Virus.MSWord.Reflex-b6437964faeedb089db98b3ddb6d43a85e9dacbe - OLE stream: 'Emperor23'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(empty macro)
No suspicious keyword or IOC found.

