olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Virus.MSWord.Marker-based-0d56b28041d92ad67f373e2128755339b667ea90
Type: OLE
-------------------------------------------------------------------------------
VBA MACRO Dummy1 
in file: Virus.MSWord.Marker-based-0d56b28041d92ad67f373e2128755339b667ea90 - OLE stream: 'Dummy1'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Sub Dummy1()
End Sub
No suspicious keyword or IOC found.

