olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Virus.MSWord.Xaler.g-77bb6665ff08ccb867d8b6fc13b314f711029146
Type: OLE
-------------------------------------------------------------------------------
VBA MACRO ThisDocument.vba 
in file: Virus.MSWord.Xaler.g-77bb6665ff08ccb867d8b6fc13b314f711029146 - OLE stream: 'Macros/VBA/ThisDocument'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(empty macro)
No suspicious keyword or IOC found.

