olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Virus.MSWord.Beast-ee1e954cb7953b5752149b05268384b0c1cbeb03
Type: OLE
-------------------------------------------------------------------------------
VBA MACRO groovie 
in file: Virus.MSWord.Beast-ee1e954cb7953b5752149b05268384b0c1cbeb03 - OLE stream: 'groovie'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(empty macro)
No suspicious keyword or IOC found.

