olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Virus.MSWord.Marker-based-216dfaed1221e618d09834957d523f33880394bb
Type: OLE
-------------------------------------------------------------------------------
VBA MACRO Dummy1 
in file: Virus.MSWord.Marker-based-216dfaed1221e618d09834957d523f33880394bb - OLE stream: 'Dummy1'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Sub Dummy1()
End Sub
No suspicious keyword or IOC found.

