olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Virus.MSWord.Beast-bf88704cd37bba2860f77d3a758c08bbe5746acb
Type: OLE
-------------------------------------------------------------------------------
VBA MACRO AutoOpen 
in file: Virus.MSWord.Beast-bf88704cd37bba2860f77d3a758c08bbe5746acb - OLE stream: 'AutoOpen'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(empty macro)
-------------------------------------------------------------------------------
VBA MACRO Payload 
in file: Virus.MSWord.Beast-bf88704cd37bba2860f77d3a758c08bbe5746acb - OLE stream: 'Payload'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(empty macro)
-------------------------------------------------------------------------------
VBA MACRO VClose 
in file: Virus.MSWord.Beast-bf88704cd37bba2860f77d3a758c08bbe5746acb - OLE stream: 'VClose'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(empty macro)
-------------------------------------------------------------------------------
VBA MACRO groovie 
in file: Virus.MSWord.Beast-bf88704cd37bba2860f77d3a758c08bbe5746acb - OLE stream: 'groovie'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(empty macro)
+----------+--------------------+---------------------------------------------+
|Type      |Keyword             |Description                                  |
+----------+--------------------+---------------------------------------------+
|AutoExec  |AutoOpen            |Runs when the Word document is opened        |
|Suspicious|Base64 Strings      |Base64-encoded strings were detected, may be |
|          |                    |used to obfuscate strings (option --decode to|
|          |                    |see all)                                     |
+----------+--------------------+---------------------------------------------+

