olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Virus.MSWord.Beast-1170076c877db17b3b324a4a8f2223ec6bcf877d
Type: OLE
-------------------------------------------------------------------------------
VBA MACRO VClose 
in file: Virus.MSWord.Beast-1170076c877db17b3b324a4a8f2223ec6bcf877d - OLE stream: 'VClose'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(empty macro)
-------------------------------------------------------------------------------
VBA MACRO groovie 
in file: Virus.MSWord.Beast-1170076c877db17b3b324a4a8f2223ec6bcf877d - OLE stream: 'groovie'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(empty macro)
-------------------------------------------------------------------------------
VBA MACRO Payload 
in file: Virus.MSWord.Beast-1170076c877db17b3b324a4a8f2223ec6bcf877d - OLE stream: 'Payload'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(empty macro)
-------------------------------------------------------------------------------
VBA MACRO AutoOpen 
in file: Virus.MSWord.Beast-1170076c877db17b3b324a4a8f2223ec6bcf877d - OLE stream: 'AutoOpen'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(empty macro)
+----------+--------------------+---------------------------------------------+
|Type      |Keyword             |Description                                  |
+----------+--------------------+---------------------------------------------+
|AutoExec  |AutoOpen            |Runs when the Word document is opened        |
|Suspicious|Base64 Strings      |Base64-encoded strings were detected, may be |
|          |                    |used to obfuscate strings (option --decode to|
|          |                    |see all)                                     |
+----------+--------------------+---------------------------------------------+

