olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Trojan-Dropper.MSWord.Lafool.h-402d1bd5c9133d45dfcfe2955af62377a26d6dfa
Type: OLE
-------------------------------------------------------------------------------
VBA MACRO ThisDocument 
in file: Trojan-Dropper.MSWord.Lafool.h-402d1bd5c9133d45dfcfe2955af62377a26d6dfa - OLE stream: 'ThisDocument'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(empty macro)
-------------------------------------------------------------------------------
VBA MACRO NewMacros 
in file: Trojan-Dropper.MSWord.Lafool.h-402d1bd5c9133d45dfcfe2955af62377a26d6dfa - OLE stream: 'NewMacros'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Sub HANAMI()
Attribute HANAMI.VB_Description = "ºêÔÚ 2002-5-20 ÓÉ EFairy Â¼ÖÆ"
Attribute HANAMI.VB_ProcData.VB_Invoke_Func = "Project.NewMacros.HANAMI"
'
' HANAMI Macro
' ºêÔÚ 2002-5-20 ÓÉ EFairy Â¼ÖÆ
'
End Sub
No suspicious keyword or IOC found.

