olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Trojan-Dropper.MSWord.1Table.ai-7cae5f5f90682f0fed577f71d39e445b072bf18e
Type: OLE
-------------------------------------------------------------------------------
VBA MACRO ThisDocument.vba 
in file: Trojan-Dropper.MSWord.1Table.ai-7cae5f5f90682f0fed577f71d39e445b072bf18e - OLE stream: 'Macros/VBA/ThisDocument'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(empty macro)
No suspicious keyword or IOC found.

