olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Trojan-Dropper.MSWord.1Table.i-ad9ceb8da4bf5db8bf68188b20577ecc291f2e60
Type: OLE
-------------------------------------------------------------------------------
VBA MACRO ThisDocument.vba 
in file: Trojan-Dropper.MSWord.1Table.i-ad9ceb8da4bf5db8bf68188b20577ecc291f2e60 - OLE stream: 'Macros/VBA/ThisDocument'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(empty macro)
No suspicious keyword or IOC found.

