olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Trojan-Dropper.MSWord.Lafool.c-b4d723a2d2f3e30a2889d7d803ff323a553f8c13
Type: OLE
-------------------------------------------------------------------------------
VBA MACRO ThisDocument.cls 
in file: Trojan-Dropper.MSWord.Lafool.c-b4d723a2d2f3e30a2889d7d803ff323a553f8c13 - OLE stream: 'Macros/VBA/ThisDocument'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(empty macro)
-------------------------------------------------------------------------------
VBA MACRO NewMacros.bas 
in file: Trojan-Dropper.MSWord.Lafool.c-b4d723a2d2f3e30a2889d7d803ff323a553f8c13 - OLE stream: 'Macros/VBA/NewMacros'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Sub konami()
Attribute konami.VB_Description = "宏在 2004-1-6 由 tian 创建"
Attribute konami.VB_ProcData.VB_Invoke_Func = "Project.NewMacros.konami"
'
' konami Macro
' 宏在 2004-1-6 由 tian 创建
'

End Sub
No suspicious keyword or IOC found.

