olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Trojan-Dropper.MSWord.1Table.w-5066dd93ac555e5ca0f2757a66e87430ad369d46
Type: OLE
-------------------------------------------------------------------------------
VBA MACRO ThisDocument.vba 
in file: Trojan-Dropper.MSWord.1Table.w-5066dd93ac555e5ca0f2757a66e87430ad369d46 - OLE stream: 'Macros/VBA/ThisDocument'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(empty macro)
No suspicious keyword or IOC found.

